// Technical track — Swedish and Korean section title translations

export const a2ASectionSv = { intro: 'MCP kopplar agenter till verktyg. A2A kopplar agenter till andra agenter.', title: '7. A2A — Agent-till-Agent-protokollet', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }
export const a2ASectionKo = { intro: 'MCP는 에이전트를 도구에 연결합니다. A2A는 에이전트를 다른 에이전트에 연결합니다.', title: '7. A2A — 에이전트 간 프로토콜', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }

export const buildingAgentsSectionSv = { intro: 'Du behöver inget ramverk för att bygga en agent. Börja med rå funktionsanrop och skala upp vid behov.', title: '6. Bygga agenter', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }
export const buildingAgentsSectionKo = { intro: '에이전트를 구축하는 데 프레임워크가 필요하지 않습니다. 원시 함수 호출로 시작하고 필요에 따라 확장하세요.', title: '6. 에이전트 구축', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }

export const designPatternsSectionSv = { intro: 'Inte alla agenter fungerar likadant. Dessa är de centrala arkitekturmönstren.', title: '4. Designmönster för agenter', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }
export const designPatternsSectionKo = { intro: '모든 에이전트가 같은 방식으로 작동하지 않습니다. 핵심 아키텍처 패턴입니다.', title: '4. 에이전트 디자인 패턴', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }

export const functionCallingSectionSv = { intro: 'Funktionsanrop är hur LLM:er använder verktyg. Modellen tar emot verktygsscheman och bestämmer när den ska anropa dem.', title: '2. Funktionsanrop', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }
export const functionCallingSectionKo = { intro: '함수 호출은 LLM이 도구를 사용하는 방법입니다. 모델이 도구 스키마를 받고 언제 호출할지 결정합니다.', title: '2. 함수 호출', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }

export const mCPSectionSv = { intro: '', title: '3. MCP (Model Context Protocol)', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }
export const mCPSectionKo = { intro: '', title: '3. MCP (모델 컨텍스트 프로토콜)', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }

export const productionGovernanceSectionSv = { intro: 'Att driftsätta agenter i produktion skiljer sig fundamentalt från att driftsätta API:er.', title: '8. Produktionsstyrning — Tillit i skala', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }
export const productionGovernanceSectionKo = { intro: '에이전트를 프로덕션에 배포하는 것은 API 배포와 근본적으로 다릅니다.', title: '8. 프로덕션 거버넌스 — 대규모 신뢰', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }

export const skillsHarnessSectionSv = { intro: 'MCP ger agenter verktyg. Agent Skills ger dem arbetsflöden. AGENTS.md och Kiro steering ger dem projektkontext. Bedrock AgentCore ger dem en hanterad körtid. Ekosystemet har konvergerat till distinkta lager — de flesta öppna och donerade till Agentic AI Foundation (Linux Foundation, december 2025).', title: '8. Skills, Steering och den hanterade körtiden', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }
export const skillsHarnessSectionKo = { intro: 'MCP는 에이전트에게 도구를, Agent Skills는 워크플로우를, AGENTS.md와 Kiro steering은 프로젝트 컨텍스트를, Bedrock AgentCore는 관리형 런타임을 제공합니다. 에코시스템이 명확한 계층으로 수렴했고, 대부분 오픈 표준이며 Agentic AI Foundation(Linux Foundation, 2025년 12월)에 기증되었습니다.', title: '8. 스킬, 스티어링, 관리형 런타임', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }

export const whatAreAgentsSectionSv = { intro: 'En vanlig LLM genererar text. En agent kan ta handlingar — anropa API:er, fråga databaser, köra kod.', title: '1. Vad är AI-agenter?', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }
export const whatAreAgentsSectionKo = { intro: '일반 LLM은 텍스트를 생성합니다. 에이전트는 행동할 수 있습니다 — API 호출, 데이터베이스 조회, 코드 실행.', title: '1. AI 에이전트란?', p2: '', p3: '', p4: '', p5: '', p6: '', p7: '', p8: '', p9: '', p10: '', p11: '', p12: '', p13: '', p14: '', p15: '', p16: '', p17: '', p18: '', p19: '', p20: '' }
