/**
 * Centralized UI label translations for technical section components.
 * These are short labels, headings, and button text used across visualizations.
 *
 * Usage:
 *   import { tLabel } from '../../i18n'
 *   <h3>{tLabel(lang, 'pros')}</h3>
 */
import type { Language } from './LanguageContext'

const L: Record<string, Record<Language, string>> = {
  // Common UI
  yes: { en: 'Yes', sv: 'Ja', ko: '예' },
  no: { en: 'No', sv: 'Nej', ko: '아니요' },
  pros: { en: 'Pros', sv: 'Fördelar', ko: '장점' },
  cons: { en: 'Cons', sv: 'Nackdelar', ko: '단점' },
  tools: { en: 'Tools', sv: 'Verktyg', ko: '도구' },
  whenToUse: { en: 'When to use', sv: 'När man ska använda', ko: '사용 시기' },
  examples: { en: 'Examples: ', sv: 'Exempel: ', ko: '예시: ' },
  clickToReveal: { en: 'Click to reveal →', sv: 'Klicka för att visa →', ko: '클릭하여 확인 →' },
  startOver: { en: 'Start Over', sv: 'Börja om', ko: '처음부터' },
  upNext: { en: 'Up next: ', sv: 'Härnäst: ', ko: '다음: ' },
  dataRemaining: { en: 'Data remaining', sv: 'Data kvar', ko: '남은 데이터' },
  implementation: { en: 'Implementation:', sv: 'Implementering:', ko: '구현:' },
  mitigation: { en: 'Mitigation:', sv: 'Åtgärd:', ko: '완화:' },
  instruction: { en: 'Instruction: ', sv: 'Instruktion: ', ko: '지시: ' },
  response: { en: 'Response: ', sv: 'Svar: ', ko: '응답: ' },
  scoring: { en: 'Scoring', sv: 'Poängsättning', ko: '채점' },
  cosineSimilarity: { en: 'Cosine similarity:', sv: 'Cosinuslikhet:', ko: '코사인 유사도:' },

  // Table headers
  dimension: { en: 'Dimension', sv: 'Dimension', ko: '차원' },
  traditionalMl: { en: 'Traditional ML', sv: 'Traditionell ML', ko: '전통적 ML' },
  llms: { en: 'LLMs', sv: 'LLM:er', ko: 'LLM' },
  framework: { en: 'Framework', sv: 'Ramverk', ko: '프레임워크' },
  complexity: { en: 'Complexity', sv: 'Komplexitet', ko: '복잡도' },
  flexibility: { en: 'Flexibility', sv: 'Flexibilitet', ko: '유연성' },
  learningCurve: { en: 'Learning Curve', sv: 'Inlärningskurva', ko: '학습 곡선' },
  bestFor: { en: 'Best For', sv: 'Bäst för', ko: '최적 용도' },
  aspect: { en: 'Aspect', sv: 'Aspekt', ko: '측면' },
  functionCalling: { en: 'Function Calling', sv: 'Funktionsanrop', ko: '함수 호출' },
  topScores: { en: 'Top Scores (2026)', sv: 'Toppresultat (2026)', ko: '최고 점수 (2026)' },
  budget: { en: 'Budget: ', sv: 'Budget: ', ko: '예산: ' },
  fineTune: { en: 'Fine-tune: ', sv: 'Finjustering: ', ko: '파인튜닝: ' },

  // Section headings
  keyTrends: { en: 'Key Trends', sv: 'Nyckeltrender', ko: '주요 트렌드' },
  techniques: { en: 'Techniques', sv: 'Tekniker', ko: '기법' },
  realWorldModels: { en: 'Real-World Models', sv: 'Verkliga modeller', ko: '실제 모델' },
  tradeoffComparison: { en: 'Tradeoff Comparison', sv: 'Avvägningsjämförelse', ko: '트레이드오프 비교' },
  chunkSizeImpact: { en: 'Chunk Size Impact', sv: 'Effekt av chunk-storlek', ko: '청크 크기 영향' },
  bestPractices: { en: 'Best Practices', sv: 'Bästa praxis', ko: '모범 사례' },
  embeddingPipeline: { en: 'Embedding Pipeline', sv: 'Embedding-pipeline', ko: '임베딩 파이프라인' },
  fullRagPipeline: { en: 'Full RAG Pipeline', sv: 'Komplett RAG-pipeline', ko: '전체 RAG 파이프라인' },
  typesOfEvaluation: { en: 'Types of Evaluation', sv: 'Typer av utvärdering', ko: '평가 유형' },
  costCalculator: { en: 'Cost Calculator', sv: 'Kostnadskalkylator', ko: '비용 계산기' },
  gpuPricingReference: { en: 'GPU Pricing Reference', sv: 'GPU-prisreferens', ko: 'GPU 가격 참조' },
  theKvCache: { en: 'The KV Cache', sv: 'KV-cachen', ko: 'KV 캐시' },
  inferencePipeline: { en: 'Inference Pipeline', sv: 'Inferenspipeline', ko: '추론 파이프라인' },
  trainingDataRatio: { en: 'Training Data Ratio', sv: 'Träningsdatafördelning', ko: '학습 데이터 비율' },
  estimatedCapabilities: { en: 'Estimated Capabilities', sv: 'Uppskattade förmågor', ko: '예상 능력' },
  whenRagBeatsFt: { en: 'When RAG Beats Fine-tuning', sv: 'När RAG slår finjustering', ko: 'RAG가 파인튜닝을 이기는 경우' },
  howFunctionCalling: { en: 'How Function Calling Works', sv: 'Hur funktionsanrop fungerar', ko: '함수 호출 작동 방식' },
  scaleComparison: { en: 'Scale comparison', sv: 'Skalajämförelse', ko: '규모 비교' },
  garbageInOut: { en: 'Garbage In, Garbage Out', sv: 'Skräp in, skräp ut', ko: '쓰레기를 넣으면 쓰레기가 나온다' },
  industryReality: { en: 'Industry reality check', sv: 'Branschens verklighetscheck', ko: '업계 현실 점검' },
  sizePipeline: { en: 'Size pipeline', sv: 'Storlekspipeline', ko: '크기 파이프라인' },
  whenLlmsOverkill: { en: 'When LLMs Are Overkill', sv: 'När LLM:er är överdrivet', ko: 'LLM이 과한 경우' },
  whenMlWins: { en: 'When Classical ML Wins', sv: 'När klassisk ML vinner', ko: '클래식 ML이 이기는 경우' },
  sameProblem: { en: 'Same Problem, Two Approaches: Sentiment Analysis', sv: 'Samma problem, två metoder: Sentimentanalys', ko: '같은 문제, 두 가지 접근: 감성 분석' },
  lessEffort: { en: '← Less effort, less control', sv: '← Mindre ansträngning, mindre kontroll', ko: '← 적은 노력, 적은 제어' },
  moreEffort: { en: 'More effort, more control →', sv: 'Mer ansträngning, mer kontroll →', ko: '더 많은 노력, 더 많은 제어 →' },

  // Diagram labels
  yourApp: { en: 'Your App', sv: 'Din app', ko: '앱' },
  mcpServer: { en: 'MCP Server', sv: 'MCP-server', ko: 'MCP 서버' },
  denseFfn: { en: 'Dense FFN', sv: 'Dense FFN', ko: 'Dense FFN' },
  mixtureOfExperts: { en: 'Mixture of Experts', sv: 'Mixture of Experts', ko: 'Mixture of Experts' },
  graphRag: { en: 'GraphRAG', sv: 'GraphRAG', ko: 'GraphRAG' },
  agenticRag: { en: 'Agentic RAG', sv: 'Agentic RAG', ko: 'Agentic RAG' },
  qloraOnBudget: { en: 'QLoRA — LoRA on a budget', sv: 'QLoRA — LoRA med liten budget', ko: 'QLoRA — 저예산 LoRA' },
  llmGenerative: { en: 'LLM (Generative)', sv: 'LLM (Generativ)', ko: 'LLM (생성형)' },
  embeddingModel: { en: 'Embedding Model', sv: 'Embedding-modell', ko: '임베딩 모델' },
  inputToVector: { en: 'Input → Fixed-size vector', sv: 'Indata → Vektor med fast storlek', ko: '입력 → 고정 크기 벡터' },
  bm25Keyword: { en: 'BM25 Keyword (30%)', sv: 'BM25 Nyckelord (30%)', ko: 'BM25 키워드 (30%)' },
  goodMlDataset: { en: 'Good ML dataset', sv: 'Bra ML-dataset', ko: '좋은 ML 데이터셋' },
  llmPretraining: { en: 'LLM pre-training dataset', sv: 'LLM-förträningsdataset', ko: 'LLM 사전학습 데이터셋' },
  vector70: { en: 'Vector 70%', sv: 'Vektor 70%', ko: '벡터 70%' },
  bm2530: { en: 'BM25 30%', sv: 'BM25 30%', ko: 'BM25 30%' },
  modelSizeAxis: { en: 'Model Size (GB) — 7B model', sv: 'Modellstorlek (GB) — 7B-modell', ko: '모델 크기 (GB) — 7B 모델' },
  qualityAxis: { en: 'Quality (%)', sv: 'Kvalitet (%)', ko: '품질 (%)' },
  afterTraining: { en: 'After training — structured patterns', sv: 'Efter träning — strukturerade mönster', ko: '학습 후 — 구조화된 패턴' },
  beforeTraining: { en: 'Before training — random noise', sv: 'Före träning — slumpmässigt brus', ko: '학습 전 — 랜덤 노이즈' },
  tokenizerCallout: { en: 'Why this matters: The tokenizer determines how efficiently your model "sees" text. A compression rate of 3.94 bytes/token means every token carries ~4 characters of information. Better compression = shorter sequences = faster training = lower cost. nanochat\'s 32K vocab is deliberately small to keep the embedding table manageable for models you can train on a single GPU node.', sv: 'Varför detta spelar roll: Tokenizern bestämmer hur effektivt din modell "ser" text. En komprimeringsgrad på 3,94 bytes/token innebär att varje token bär ~4 tecken information. Bättre komprimering = kortare sekvenser = snabbare träning = lägre kostnad. nanochats 32K-vokabulär är medvetet liten för att hålla embedding-tabellen hanterbar för modeller du kan träna på en enda GPU-nod.', ko: '이것이 중요한 이유: 토크나이저는 모델이 텍스트를 얼마나 효율적으로 "보는지" 결정합니다. 3.94 bytes/token의 압축률은 각 토큰이 ~4자의 정보를 담는다는 의미입니다. 더 나은 압축 = 더 짧은 시퀀스 = 더 빠른 학습 = 더 낮은 비용. nanochat의 32K 어휘는 단일 GPU 노드에서 학습할 수 있는 모델을 위해 임베딩 테이블을 관리 가능하게 유지하려고 의도적으로 작습니다.' },
  trainingKeyInsight: { en: 'Key insight: Random weights = the model knows nothing. Ask it anything and you get gibberish. In nanochat, the --depth flag is the single dial that controls model size — all other hyperparameters (width, heads, learning rate, training horizon) are calculated automatically to be compute-optimal.', sv: 'Nyckelinsikt: Slumpmässiga vikter = modellen vet ingenting. Fråga den vad som helst och du får nonsens. I nanochat är --depth-flaggan den enda ratten som styr modellstorlek — alla andra hyperparametrar (bredd, huvuden, inlärningshastighet, träningshorisont) beräknas automatiskt för att vara beräkningsoptimala.', ko: '핵심 인사이트: 랜덤 가중치 = 모델은 아무것도 모릅니다. 무엇을 물어도 의미 없는 답이 나옵니다. nanochat에서 --depth 플래그는 모델 크기를 제어하는 유일한 다이얼입니다 — 다른 모든 하이퍼파라미터(너비, 헤드, 학습률, 학습 기간)는 계산 최적이 되도록 자동으로 계산됩니다.' },
  a2aIntro: { en: 'MCP connects agents to tools. A2A connects agents to other agents. Launched by Google in April 2025 and donated to the Linux Foundation, A2A defines how opaque agents discover each other, negotiate capabilities, exchange tasks, and stream results — regardless of framework or vendor.', sv: 'MCP kopplar agenter till verktyg. A2A kopplar agenter till andra agenter. Lanserat av Google i april 2025 och donerat till Linux Foundation definierar A2A hur agenter upptäcker varandra, förhandlar om förmågor, utbyter uppgifter och strömmar resultat — oavsett ramverk eller leverantör.', ko: 'MCP는 에이전트를 도구에 연결합니다. A2A는 에이전트를 다른 에이전트에 연결합니다. 2025년 4월 Google이 출시하고 Linux Foundation에 기부한 A2A는 불투명한 에이전트들이 서로를 발견하고, 기능을 협상하고, 작업을 교환하고, 결과를 스트리밍하는 방법을 정의합니다 — 프레임워크나 벤더에 관계없이.' },
  agentDef: { en: 'An agent is an LLM that can take actions — call APIs, query databases, run code — then use the results to keep reasoning. It closes the loop between thinking and doing.', sv: 'En agent är en LLM som kan utföra handlingar — anropa API:er, fråga databaser, köra kod — och sedan använda resultaten för att fortsätta resonera. Den sluter loopen mellan att tänka och att göra.', ko: '에이전트는 행동을 취할 수 있는 LLM입니다 — API 호출, 데이터베이스 쿼리, 코드 실행 — 그런 다음 결과를 사용하여 계속 추론합니다. 생각과 행동 사이의 루프를 닫습니다.' },
  fcKeyTakeaway: { en: 'Key takeaway: The model is a decision-maker, not an executor. It picks the right tool and arguments. Your application code runs the function, handles errors, and sends results back. This keeps the model sandboxed and your system in control.', sv: 'Nyckelpoäng: Modellen är en beslutsfattare, inte en utförare. Den väljer rätt verktyg och argument. Din applikationskod kör funktionen, hanterar fel och skickar tillbaka resultat. Detta håller modellen sandlådad och ditt system i kontroll.', ko: '핵심 요점: 모델은 의사결정자이지 실행자가 아닙니다. 올바른 도구와 인수를 선택합니다. 애플리케이션 코드가 함수를 실행하고, 오류를 처리하고, 결과를 반환합니다. 이렇게 하면 모델은 샌드박스에 있고 시스템이 제어권을 유지합니다.' },
  sweetSpot: { en: 'sweet spot', sv: 'sweet spot', ko: '최적점' },
  kvCache: { en: 'KV Cache', sv: 'KV-cache', ko: 'KV 캐시' },
  tokWhyIntro: { en: 'Neural networks do math — they multiply matrices, add vectors, compute gradients. They can\'t read the letter "A" any more than your calculator can. So before any text reaches a model, it gets chopped into tokens — small pieces that each map to a number. The question is: how do you chop?', sv: 'Neurala nätverk gör matematik — de multiplicerar matriser, adderar vektorer, beräknar gradienter. De kan inte läsa bokstaven "A" mer än din miniräknare kan. Så innan text når en modell delas den upp i tokens — små bitar som var och en mappas till ett nummer. Frågan är: hur delar man?', ko: '신경망은 수학을 합니다 — 행렬을 곱하고, 벡터를 더하고, 그래디언트를 계산합니다. 계산기가 글자를 읽을 수 없듯이 신경망도 마찬가지입니다. 그래서 텍스트가 모델에 도달하기 전에 토큰으로 잘립니다 — 각각 숫자에 매핑되는 작은 조각들입니다. 문제는: 어떻게 자르느냐입니다.' },
  tokBpeIntro: { en: 'Byte Pair Encoding starts with individual characters and repeatedly merges the most frequent adjacent pair. After enough merges, common words become single tokens while rare words stay split into recognizable pieces.', sv: 'Byte Pair Encoding börjar med enskilda tecken och slår ihop det vanligaste angränsande paret upprepade gånger. Efter tillräckligt många sammanslagningar blir vanliga ord enskilda tokens medan ovanliga ord förblir uppdelade i igenkännbara delar.', ko: 'Byte Pair Encoding은 개별 문자에서 시작하여 가장 빈번한 인접 쌍을 반복적으로 병합합니다. 충분한 병합 후 일반 단어는 단일 토큰이 되고 희귀 단어는 인식 가능한 조각으로 분할됩니다.' },
  tokEconIntro: { en: 'When you call an LLM API, you pay per token — both for input and output. Different kinds of text tokenize very differently, so the same "amount" of content can cost wildly different amounts.', sv: 'När du anropar ett LLM-API betalar du per token — både för indata och utdata. Olika typer av text tokeniseras väldigt olika, så samma "mängd" innehåll kan kosta vitt skilda belopp.', ko: 'LLM API를 호출할 때 토큰당 비용을 지불합니다 — 입력과 출력 모두. 다른 종류의 텍스트는 매우 다르게 토큰화되므로 같은 "양"의 콘텐츠가 크게 다른 비용이 될 수 있습니다.' },
  tokVocabIntro: { en: 'A tokenizer\'s vocabulary is just a big lookup table: token string → integer ID. Modern LLMs typically have 32K–128K tokens. The vocabulary lives in a JSON file alongside the model weights. Click around to explore:', sv: 'En tokenizers vokabulär är bara en stor uppslagstabell: token-sträng → heltals-ID. Moderna LLM:er har vanligtvis 32K–128K tokens. Vokabulären finns i en JSON-fil bredvid modellvikterna. Klicka runt för att utforska:', ko: '토크나이저의 어휘는 큰 조회 테이블입니다: 토큰 문자열 → 정수 ID. 현대 LLM은 보통 32K–128K 토큰을 가집니다. 어휘는 모델 가중치와 함께 JSON 파일에 저장됩니다. 클릭하여 탐색하세요:' },
  tokSpecialIntro: { en: 'Beyond regular text tokens, every tokenizer defines a handful of special tokens that control the model\'s behavior. These never appear in normal text — they\'re injected by the tokenizer automatically.', sv: 'Utöver vanliga texttokens definierar varje tokenizer en handfull specialtokens som styr modellens beteende. Dessa förekommer aldrig i normal text — de injiceras av tokenizern automatiskt.', ko: '일반 텍스트 토큰 외에도 모든 토크나이저는 모델의 동작을 제어하는 몇 가지 특수 토큰을 정의합니다. 이들은 일반 텍스트에 나타나지 않으며 토크나이저가 자동으로 삽입합니다.' },
  tokTrainIntro: { en: 'In Karpathy\'s nanochat — a minimal end-to-end LLM training harness — the tokenizer is the very first thing you build. Two scripts handle the entire lifecycle:', sv: 'I Karpathys nanochat — en minimal end-to-end LLM-träningsharness — är tokenizern det allra första du bygger. Två skript hanterar hela livscykeln:', ko: 'Karpathy의 nanochat — 최소한의 엔드투엔드 LLM 학습 하네스 — 에서 토크나이저는 가장 먼저 만드는 것입니다. 두 개의 스크립트가 전체 라이프사이클을 처리합니다:' },
  // Agent trace
  traceUser: { en: 'User', sv: 'Användare', ko: '사용자' },
  traceThought: { en: 'Thought', sv: 'Tanke', ko: '생각' },
  traceAction: { en: 'Action', sv: 'Handling', ko: '행동' },
  traceObservation: { en: 'Observation', sv: 'Observation', ko: '관찰' },
  traceAnswer: { en: 'Answer', sv: 'Svar', ko: '답변' },
  // Attention variants
  mhaDesc: { en: 'Each attention head has its own K and V projections. Maximum expressiveness but largest KV cache.', sv: 'Varje attention-huvud har egna K- och V-projektioner. Maximal uttrycksfullhet men störst KV-cache.', ko: '각 어텐션 헤드가 자체 K, V 프로젝션을 가집니다. 최대 표현력이지만 가장 큰 KV 캐시.' },
  gqaDesc: { en: 'Query heads are grouped, sharing K/V projections within each group. Best quality-speed tradeoff.', sv: 'Query-huvuden grupperas och delar K/V-projektioner inom varje grupp. Bästa avvägning mellan kvalitet och hastighet.', ko: '쿼리 헤드가 그룹화되어 각 그룹 내에서 K/V 프로젝션을 공유합니다. 최적의 품질-속도 트레이드오프.' },
  mqaDesc: { en: 'All query heads share a single K/V pair. Fastest inference but some quality loss.', sv: 'Alla query-huvuden delar ett enda K/V-par. Snabbast inferens men viss kvalitetsförlust.', ko: '모든 쿼리 헤드가 단일 K/V 쌍을 공유합니다. 가장 빠른 추론이지만 약간의 품질 손실.' },
  mlaDesc: { en: 'Compresses KV into a low-rank latent space. Tiny cache with quality close to full MHA.', sv: 'Komprimerar KV till ett lågrangs latent utrymme. Liten cache med kvalitet nära full MHA.', ko: 'KV를 저랭크 잠재 공간으로 압축합니다. 전체 MHA에 가까운 품질의 작은 캐시.' },
  // Scaling laws
  noteSmallResearch: { en: 'Small research experiment', sv: 'Litet forskningsexperiment', ko: '소규모 연구 실험' },
  noteGpt2Small: { en: 'GPT-2 Small scale', sv: 'GPT-2 Small-skala', ko: 'GPT-2 Small 규모' },
  noteMidResearch: { en: 'Mid-size research', sv: 'Medelstor forskning', ko: '중간 규모 연구' },
  noteGpt2Xl: { en: 'GPT-2 XL scale', sv: 'GPT-2 XL-skala', ko: 'GPT-2 XL 규모' },
  noteChinchilla4b: { en: 'Chinchilla-optimal 4B', sv: 'Chinchilla-optimal 4B', ko: 'Chinchilla 최적 4B' },
  noteLlama13b: { en: 'Llama 2 13B scale', sv: 'Llama 2 13B-skala', ko: 'Llama 2 13B 규모' },
  noteChinchilla70b: { en: 'Chinchilla 70B territory', sv: 'Chinchilla 70B-territorium', ko: 'Chinchilla 70B 영역' },
  noteFrontier: { en: 'Frontier dense models', sv: 'Frontier-modeller (dense)', ko: '프론티어 dense 모델' },
  // Chunking
  chunkFixed: { en: 'Split every N tokens regardless of content boundaries', sv: 'Dela var N:e token oavsett innehållsgränser', ko: '콘텐츠 경계에 관계없이 N 토큰마다 분할' },
  chunkSemantic: { en: 'Split on natural boundaries: paragraphs and sections', sv: 'Dela vid naturliga gränser: stycken och avsnitt', ko: '자연스러운 경계에서 분할: 단락과 섹션' },
  chunkRecursive: { en: 'Try headers first, then paragraphs, then sentences', sv: 'Prova rubriker först, sedan stycken, sedan meningar', ko: '헤더를 먼저 시도, 그다음 단락, 그다음 문장' },
  // RAG pipeline
  ragDocument: { en: 'Raw source data', sv: 'Rå källdata', ko: '원시 소스 데이터' },
  ragChunk: { en: 'Split into pieces', sv: 'Dela i bitar', ko: '조각으로 분할' },
  ragEmbed: { en: 'Convert to vectors', sv: 'Konvertera till vektorer', ko: '벡터로 변환' },
  ragStore: { en: 'Vector database', sv: 'Vektordatabas', ko: '벡터 데이터베이스' },
  ragQuery: { en: 'Embed user query', sv: 'Bädda in användarfråga', ko: '사용자 쿼리 임베딩' },
  ragRetrieve: { en: 'Find similar chunks', sv: 'Hitta liknande bitar', ko: '유사한 청크 찾기' },
  ragGenerate: { en: 'LLM generates answer', sv: 'LLM genererar svar', ko: 'LLM이 답변 생성' },
  // Embedding categories
  catAnimals: { en: 'Animals', sv: 'Djur', ko: '동물' },
  catColors: { en: 'Colors', sv: 'Färger', ko: '색상' },
  catEmotions: { en: 'Emotions', sv: 'Känslor', ko: '감정' },
  catVehicles: { en: 'Vehicles', sv: 'Fordon', ko: '차량' },
  // Inference pipeline
  promptTokens: { en: 'Prompt Tokens', sv: 'Prompt-tokens', ko: '프롬프트 토큰' },
  prefill: { en: 'Prefill', sv: 'Prefill', ko: '프리필' },
  decode: { en: 'Decode', sv: 'Avkodning', ko: '디코딩' },
  promptTokensDesc: { en: 'User input tokenized into IDs', sv: 'Användarindata tokeniserad till ID:n', ko: '사용자 입력이 ID로 토큰화' },
  prefillDesc: { en: 'Process all tokens at once — build initial KV cache', sv: 'Bearbeta alla tokens på en gång — bygg initial KV-cache', ko: '모든 토큰을 한 번에 처리 — 초기 KV 캐시 구축' },
  decodeDesc: { en: 'Generate one token at a time (autoregressive)', sv: 'Generera en token i taget (autoregressiv)', ko: '한 번에 하나의 토큰 생성 (자기회귀)' },
  kvWhyExists: { en: 'Avoids recomputing attention keys/values for all previous tokens at each decode step', sv: 'Undviker att beräkna om attention-nycklar/värden för alla tidigare tokens vid varje avkodningssteg', ko: '각 디코딩 단계에서 이전 모든 토큰의 어텐션 키/값을 재계산하는 것을 방지' },
  kvHowGrows: { en: 'Proportional to sequence_length × num_layers × num_heads × head_dim × 2 (K+V)', sv: 'Proportionell mot sequence_length × num_layers × num_heads × head_dim × 2 (K+V)', ko: 'sequence_length × num_layers × num_heads × head_dim × 2 (K+V)에 비례' },
  // System prompt builder
  spGoal: { en: 'Goal', sv: 'Mål', ko: '목표' },
  spContext: { en: 'Context', sv: 'Kontext', ko: '컨텍스트' },
  spFormat: { en: 'Format', sv: 'Format', ko: '형식' },
  spTone: { en: 'Tone', sv: 'Ton', ko: '톤' },
  spConstraints: { en: 'Constraints', sv: 'Begränsningar', ko: '제약 조건' },
  // Token economics
  tokEnglishProse: { en: 'English prose', sv: 'Engelsk prosa', ko: '영어 산문' },
  tokPythonCode: { en: 'Python code', sv: 'Python-kod', ko: 'Python 코드' },
  tokJsonData: { en: 'JSON data', sv: 'JSON-data', ko: 'JSON 데이터' },
  tokChineseText: { en: 'Chinese text', sv: 'Kinesisk text', ko: '중국어 텍스트' },
  tokNoteCommon: { en: 'Common words → fewer tokens', sv: 'Vanliga ord → färre tokens', ko: '일반 단어 → 적은 토큰' },
  tokNoteIndent: { en: 'Indentation & syntax add tokens', sv: 'Indrag & syntax lägger till tokens', ko: '들여쓰기 & 구문이 토큰 추가' },
  tokNotePunct: { en: 'Punctuation-heavy → more tokens', sv: 'Mycket skiljetecken → fler tokens', ko: '구두점 많음 → 더 많은 토큰' },
  tokNoteChinese: { en: 'Each character often = 2-3 tokens', sv: 'Varje tecken ofta = 2-3 tokens', ko: '각 문자가 보통 2-3 토큰' },
  // Training
  trainEmpty: { en: 'Empty — about to clone nanochat', sv: 'Tom — ska klona nanochat', ko: '비어 있음 — nanochat 클론 예정' },
  trainDepsInstalled: { en: 'Dependencies installed', sv: 'Beroenden installerade', ko: '의존성 설치됨' },
  trainUntrained: { en: 'Untrained model = gibberish', sv: 'Otränad modell = nonsens', ko: '학습되지 않은 모델 = 의미 없는 출력' },
  trainLoadBatch: { en: 'Load Batch', sv: 'Ladda batch', ko: '배치 로드' },
  trainForwardPass: { en: 'Forward Pass', sv: 'Forward pass', ko: '순전파' },
  trainComputeLoss: { en: 'Compute Loss', sv: 'Beräkna förlust', ko: '손실 계산' },
  trainBackwardPass: { en: 'Backward Pass', sv: 'Backward pass', ko: '역전파' },
  trainUpdateWeights: { en: 'Update Weights', sv: 'Uppdatera vikter', ko: '가중치 업데이트' },
  // Attention variants
  // Leaderboard
  dataContamination: { en: 'Data Contamination', sv: 'Datakontaminering', ko: '데이터 오염' },
  benchmarkGaming: { en: 'Benchmark Gaming', sv: 'Benchmark-manipulation', ko: '벤치마크 조작' },
  narrowMeasurement: { en: 'Narrow Measurement', sv: 'Smal mätning', ko: '좁은 측정' },
  saturation: { en: 'Saturation', sv: 'Mättnad', ko: '포화' },
  // Fine-tuning workspace
  ftProjectSetup: { en: 'Project setup', sv: 'Projektuppställning', ko: '프로젝트 설정' },
  ftBaseLoaded: { en: 'Base model loaded in 4-bit', sv: 'Basmodell laddad i 4-bit', ko: '기본 모델 4비트로 로드됨' },
  ftLoraConfigured: { en: 'LoRA adapter configured', sv: 'LoRA-adapter konfigurerad', ko: 'LoRA 어댑터 구성됨' },
  ftTrainingComplete: { en: 'Training complete', sv: 'Träning klar', ko: '학습 완료' },
  ftAdapterSaved: { en: 'Adapter saved', sv: 'Adapter sparad', ko: '어댑터 저장됨' },
  // Evaluation/merging workspace
  ftStartingAdapter: { en: 'Starting with trained adapter', sv: 'Startar med tränad adapter', ko: '학습된 어댑터로 시작' },
  ftEvalComplete: { en: 'Evaluation complete', sv: 'Utvärdering klar', ko: '평가 완료' },
  ftMergedModel: { en: 'Merged model (standalone)', sv: 'Sammanslagen modell (fristående)', ko: '병합된 모델 (독립형)' },
  ftQuantizedGguf: { en: 'Quantized GGUF', sv: 'Kvantiserad GGUF', ko: '양자화된 GGUF' },
  ftRunningOllama: { en: 'Running locally via Ollama', sv: 'Körs lokalt via Ollama', ko: 'Ollama로 로컬 실행' },
  // Conversion pipeline
  cpOriginal: { en: 'Original SafeTensors model (14 GB)', sv: 'Original SafeTensors-modell (14 GB)', ko: '원본 SafeTensors 모델 (14 GB)' },
  cpGgufFp16: { en: 'After GGUF conversion (FP16)', sv: 'Efter GGUF-konvertering (FP16)', ko: 'GGUF 변환 후 (FP16)' },
  cpQuantized: { en: 'After Q4_K_M quantization (4 GB)', sv: 'Efter Q4_K_M-kvantisering (4 GB)', ko: 'Q4_K_M 양자화 후 (4 GB)' },
  cpModelfile: { en: 'Modelfile for Ollama', sv: 'Modelfile för Ollama', ko: 'Ollama용 Modelfile' },
  cpRegistered: { en: 'Registered in Ollama', sv: 'Registrerad i Ollama', ko: 'Ollama에 등록됨' },
  // Cost calculator
  apiProvider: { en: 'API Provider', sv: 'API-leverantör', ko: 'API 제공자' },
  selfHosted: { en: 'Self-Hosted', sv: 'Självhostad', ko: '셀프 호스팅' },
}

/** Get a translated label. Falls back to English, then to the key itself. */
export function tLabel(lang: Language, key: string): string {
  return L[key]?.[lang] ?? L[key]?.en ?? key
}
