// Business track quiz translations — Swedish and Korean
import type { Question } from './components/KnowledgeCheck'

type QT = Pick<Question, 'question' | 'options' | 'explanation' | 'modelAnswer'>

export const quizSv: Record<string, QT> = {
  // AI Problem
  'aiproblem-biz-1': { question: 'Ditt team lägger 3 timmar dagligen på att sortera kundmejl i kategorier. Ska ni använda AI?', options: ['Nej — mejlsortering kräver mänskligt omdöme', 'Ja — detta är repetitivt, mönsterbaserat och det finns gott om historisk data', 'Bara om ni bygger en egen AI-modell', 'Nej — ett enkelt mejlfilter räcker'], explanation: 'Detta är ett klassiskt AI-användningsfall: repetitiv uppgift, tydliga kategorier, massor av tidigare exempel att lära sig från.' },
  'aiproblem-biz-2': { question: 'En skatteberäkningsmotor behöver tillämpa exakta satser baserade på inkomstklasser definierade i lag. Vad ska ni bygga?', options: ['En AI-modell tränad på tidigare deklarationer', 'Ett regelbaserat system — logiken är exakt och definierad i lag', 'En LLM som kan tolka skattelagen', 'En maskininlärningsmodell som förutsäger skattebelopp'], explanation: 'När reglerna är exakta och fullt definierade är traditionell programvara bättre. AI lägger till oförutsägbarhet.' },
  // Data Foundations
  'df-biz-1': { question: 'Ert CRM har dubbletter, inkonsekvent namngivning och föråldrade mejladresser. Vad händer om ni tränar AI på denna data?', options: ['AI:n rensar automatiskt datan', 'AI:n lär sig fel mönster och ger förvirrade, motsägelsefulla svar', 'Det spelar ingen roll — AI är smart nog', 'AI:n flaggar dubbletterna åt er'], explanation: 'Skräp in, skräp ut. AI lär sig av den data du ger den. Stökig data = stökig AI.' },
  'df-biz-2': { question: 'Hur stor andel av de flesta företags data är ostrukturerad (mejl, dokument, chattloggar)?', options: ['Cirka 20%', 'Cirka 50%', 'Över 80%', 'Mindre än 10%'], explanation: 'Över 80% av företagsdata är ostrukturerad. Det är här LLM:er verkligen lyser.' },
  // Alignment
  'align-biz-1': { question: 'Er AI-chattbot berättar självsäkert för en kund att er produkt har en funktion den inte har. Vilken typ av AI-fel är detta?', options: ['Bias', 'Hallucination — AI:n hittade på något som låter trovärdigt', 'En dataläcka', 'En programvarubugg'], explanation: 'Hallucination är när AI genererar självsäker, trovärdigt klingande information som helt enkelt är fel.' },
  'align-biz-2': { question: 'Vad är bästa tillvägagångssättet vid första driftsättningen av en kundvänd AI?', options: ['Låt den köra helt autonomt', 'Börja med mänsklig granskning av allt, ge sedan gradvis mer autonomi', 'Driftsätt bara internt', 'Vänta tills AI är 100% pålitlig'], explanation: 'Börja strikt, lossa gradvis — som att introducera en nyanställd.' },
}

export const quizKo: Record<string, QT> = {
  // AI Problem
  'aiproblem-biz-1': { question: '팀이 매일 3시간을 고객 이메일을 카테고리별로 분류하는 데 씁니다. AI를 사용해야 할까요?', options: ['아니요 — 이메일 분류에는 사람의 판단이 필요합니다', '예 — 반복적이고 패턴 기반이며 충분한 과거 데이터가 있습니다', '맞춤 AI 모델을 구축할 때만', '아니요 — 간단한 이메일 필터 규칙으로 충분합니다'], explanation: '이것은 전형적인 AI 사용 사례입니다: 반복적인 작업, 명확한 카테고리, 학습할 과거 예시가 풍부합니다.' },
  'aiproblem-biz-2': { question: '세금 계산 엔진이 법으로 정의된 소득 구간에 따라 정확한 세율을 적용해야 합니다. 무엇을 만들어야 할까요?', options: ['과거 세금 신고서로 학습한 AI 모델', '규칙 기반 시스템 — 로직이 정확하고 법으로 정의됨', '세법을 해석할 수 있는 LLM', '세금 금액을 예측하는 머신러닝 모델'], explanation: '규칙이 정확하고 완전히 정의되어 있을 때는 전통적인 소프트웨어가 더 좋습니다.' },
  // Data Foundations
  'df-biz-1': { question: 'CRM에 중복 항목, 일관성 없는 이름, 오래된 이메일이 있습니다. 이 데이터로 AI를 학습시키면 어떻게 될까요?', options: ['AI가 자동으로 데이터를 정리합니다', 'AI가 잘못된 패턴을 학습하고 혼란스럽고 모순된 답변을 합니다', '상관없습니다 — AI는 충분히 똑똑합니다', 'AI가 중복을 표시해 줍니다'], explanation: '쓰레기를 넣으면 쓰레기가 나옵니다. AI는 제공하는 데이터에서 학습합니다.' },
  'df-biz-2': { question: '대부분 회사 데이터 중 비정형 데이터(이메일, 문서, 채팅 로그)의 비율은?', options: ['약 20%', '약 50%', '80% 이상', '10% 미만'], explanation: '비즈니스 데이터의 80% 이상이 비정형입니다. LLM이 정말 빛나는 곳입니다.' },
  // Alignment
  'align-biz-1': { question: 'AI 챗봇이 고객에게 제품에 없는 기능이 있다고 자신 있게 말합니다. 어떤 유형의 AI 실패인가요?', options: ['편향', '환각 — AI가 그럴듯하게 들리는 것을 지어냈습니다', '데이터 유출', '소프트웨어 버그'], explanation: '환각은 AI가 자신감 있고 그럴듯하게 들리지만 완전히 틀린 정보를 생성하는 것입니다.' },
  'align-biz-2': { question: '고객 대면 AI를 처음 배포할 때 가장 좋은 접근 방식은?', options: ['완전 자율적으로 실행', '모든 것에 대해 사람 검토로 시작하고 점진적으로 자율성 부여', '내부에서만 배포', 'AI가 100% 신뢰할 수 있을 때까지 대기'], explanation: '엄격하게 시작하고 점진적으로 완화 — 신입사원 온보딩처럼.' },
}

// Solution
quizSv['sol-biz-1'] = { question: 'Ert företag har 10 000 policydokument som ändras varje månad. Anställda behöver svar med källor. Vilken AI-metod passar bäst?', options: ['Finjustera en modell på dokumenten', 'RAG — AI söker i era dokument innan den svarar', 'Använd bara ChatGPT och klistra in dokument', 'Bygg en egen AI från grunden'], explanation: 'RAG är perfekt här: dokument ändras ofta, anställda behöver källhänvisningar, och ingen dyr träning behövs.' }
quizSv['sol-biz-2'] = { question: 'Er startup behöver AI igång inom 2 veckor, hanterar icke-känslig data och har inget ML-team. Vad ska ni göra?', options: ['Självhosta en öppen modell', 'Använd en API-tjänst som Amazon Bedrock eller Azure OpenAI', 'Bygg en egen modell', 'Vänta tills ni kan anställa ett ML-team'], explanation: 'API-tjänster är "taxi-alternativet" — snabbt att starta, inget underhåll, betala per användning.' }

quizKo['sol-biz-1'] = { question: '회사에 매월 변경되는 10,000개의 정책 문서가 있습니다. 직원들은 출처가 있는 답변이 필요합니다. 어떤 AI 접근 방식이 가장 적합할까요?', options: ['문서로 모델을 파인튜닝', 'RAG — AI가 답하기 전에 문서를 검색', 'ChatGPT에 문서를 붙여넣기', '처음부터 맞춤 AI 구축'], explanation: 'RAG가 완벽합니다: 문서가 자주 변경되고, 직원들은 출처가 필요하며, 비싼 학습이 필요 없습니다.' }
quizKo['sol-biz-2'] = { question: '스타트업이 2주 안에 AI가 필요하고, 비민감 데이터를 처리하며, ML 팀이 없습니다. 어떻게 해야 할까요?', options: ['오픈소스 모델을 셀프 호스팅', 'Amazon Bedrock이나 Azure OpenAI 같은 API 서비스 사용', '맞춤 모델 구축', 'ML 팀을 고용할 때까지 대기'], explanation: 'API 서비스는 "택시" 옵션입니다 — 빠르게 시작, 유지보수 없음, 사용량에 따라 지불.' }

// Evaluation
quizSv['eval-biz-1'] = { question: 'Ert team säger att AI-chattboten "verkar ganska bra." Varför räcker inte det?', options: ['Det räcker — om teamet är nöjt fungerar det', 'Ni behöver systematisk testning med tydliga mätvärden', 'Ni behöver bara testa en gång', 'AI behöver ingen utvärdering'], explanation: '"Verkar bra" är som att utvärdera en nyanställd baserat på magkänsla.' }
quizSv['eval-biz-2'] = { question: 'Ni väljer mellan en dyr och en billigare AI-modell. Den dyra får 5% högre på benchmarks. Vad ska ni göra?', options: ['Välj alltid den med högst poäng', 'Testa båda på ERA faktiska uppgifter — 5% skillnad kanske inte spelar roll', 'Benchmarks spelar ingen roll', 'Välj den billigare'], explanation: 'Benchmarks är som standardiserade prov — de ger en allmän bild men säger inte hur modellen presterar på DINA uppgifter.' }

quizKo['eval-biz-1'] = { question: '팀이 AI 챗봇이 "꽤 괜찮아 보인다"고 합니다. 왜 그것만으로는 충분하지 않을까요?', options: ['충분합니다 — 팀이 만족하면 작동하는 것입니다', '명확한 지표로 체계적인 테스트가 필요합니다', '출시 전 한 번만 테스트하면 됩니다', 'AI는 평가가 필요 없습니다'], explanation: '"괜찮아 보인다"는 신입사원을 느낌으로 평가하는 것과 같습니다.' }
quizKo['eval-biz-2'] = { question: '비싼 AI 모델과 저렴한 모델 중 선택합니다. 비싼 모델이 벤치마크에서 5% 높습니다. 어떻게 해야 할까요?', options: ['항상 점수가 높은 모델 선택', '실제 작업에서 둘 다 테스트 — 5% 차이가 중요하지 않을 수 있음', '벤치마크는 전혀 중요하지 않음', '비용 절약을 위해 저렴한 것 선택'], explanation: '벤치마크는 표준화된 시험과 같습니다 — 일반적인 그림을 주지만 여러분의 특정 작업에서의 성능은 알려주지 않습니다.' }

// Industry
quizSv['ind-biz-1'] = { question: 'Varför ger Meta bort sin AI-modell (Llama) gratis?', options: ['De kan inte ta betalt för den', 'Gratis modeller bygger ett ekosystem — utvecklare bygger på Llama, vilket skapar beroende av Metas verktyg', 'Öppna modeller är alltid bättre', 'Det krävs enligt lag'], explanation: 'Metas strategi liknar Googles med Android — ge bort kärnprodukten för att bygga ett ekosystem.' }
quizSv['ind-biz-2'] = { question: 'Ert företag hanterar känslig kunddata. Vad spelar störst roll vid val mellan öppna och stängda AI-modeller?', options: ['Vilken modell som får högst poäng', 'Dataintegritet — med öppna modeller kan ni behålla data på egna servrar', 'Vilket företag som är störst', 'Modellens lanseringsdatum'], explanation: 'För känslig data är nyckelfrågan: vart tar datan vägen?' }

quizKo['ind-biz-1'] = { question: 'Meta는 왜 AI 모델(Llama)을 무료로 제공할까요?', options: ['요금을 부과하는 방법을 모릅니다', '무료 모델이 생태계를 구축합니다 — 개발자들이 Llama 위에 구축하여 Meta의 도구에 대한 의존성 생성', '오픈소스 모델이 항상 더 좋습니다', '법적으로 요구됩니다'], explanation: 'Meta의 전략은 Google의 Android 전략과 같습니다 — 핵심 제품을 무료로 제공하여 생태계를 구축.' }
quizKo['ind-biz-2'] = { question: '회사가 민감한 고객 데이터를 처리합니다. 오픈과 클로즈드 AI 모델 선택 시 가장 중요한 것은?', options: ['벤치마크 점수가 가장 높은 모델', '데이터 프라이버시 — 오픈 모델은 자체 서버에 데이터를 유지할 수 있음', '가장 큰 회사', '모델 출시 날짜'], explanation: '민감한 데이터의 경우 핵심 질문은: 데이터가 어디로 가는가?' }

// Embeddings
quizSv['emb-biz-1'] = { question: 'En anställd söker "semesterpolicy" men dokumentet heter "PTO-riktlinjer." Vanlig sökning hittar inget. Vad gör AI-driven sökning?', options: ['Hittar inte heller — andra ord', 'Hittar dokumentet eftersom den förstår att "semester" och "PTO" betyder samma sak', 'Fungerar bara med nyckelordsetiketter', 'Kräver ny sökning med andra ord'], explanation: 'AI-driven sökning förstår betydelse, inte bara nyckelord.' }
quizSv['emb-biz-2'] = { question: 'Er AI-chattbot behöver svara på frågor om policyer som ändras varje månad. Bästa metoden?', options: ['Omträna AI:n varje månad', 'Använd RAG — AI:n söker i aktuella dokument innan den svarar', 'Säg åt AI:n att svara "vet inte"', 'Skriv ut och skanna policyerna'], explanation: 'RAG är perfekt för föränderlig information. Uppdatera dokumenten, AI:n använder automatiskt senaste versionen.' }
quizSv['emb-biz-3'] = { question: 'Du laddar upp en PDF till ChatGPT och ställer frågor. Är detta RAG?', options: ['Ja — varje gång AI läser ett dokument är det RAG', 'Nej — filen läggs direkt i konversationskontexten, inte indexerad och sökbar', 'Bara om PDF:en är längre än 10 sidor', 'Det beror på vilken AI-modell du använder'], explanation: 'Att ladda upp en fil lägger den direkt i kontexten. RAG indexerar, chunkar och söker dokument.' }

quizKo['emb-biz-1'] = { question: '직원이 "휴가 정책"을 검색하지만 문서 제목은 "PTO 허용 지침"입니다. 일반 검색은 아무것도 찾지 못합니다. AI 기반 검색은?', options: ['역시 찾지 못함 — 다른 단어', '"휴가"와 "PTO"가 같은 의미임을 이해하고 문서를 찾음', '키워드 태그를 추가해야만 작동', '다른 단어로 다시 검색 필요'], explanation: 'AI 기반 검색은 키워드가 아닌 의미를 이해합니다.' }
quizKo['emb-biz-2'] = { question: 'AI 챗봇이 매월 변경되는 회사 정책에 대한 질문에 답해야 합니다. 가장 좋은 접근 방식은?', options: ['매월 AI를 재학습', 'RAG 사용 — AI가 답하기 전에 현재 문서를 검색', 'AI에게 정책 질문에 "모르겠다"고 답하라고 지시', '정책을 인쇄하고 스캔'], explanation: 'RAG는 변경되는 정보에 완벽합니다. 문서를 업데이트하면 AI가 자동으로 최신 버전을 사용합니다.' }
quizKo['emb-biz-3'] = { question: 'ChatGPT에 PDF를 업로드하고 질문합니다. 이것이 RAG인가요?', options: ['예 — AI가 문서를 읽을 때마다 RAG입니다', '아니요 — 파일이 대화 컨텍스트에 직접 넣어지며, 인덱싱되고 검색되지 않습니다', 'PDF가 10페이지 이상일 때만', '사용하는 AI 모델에 따라 다름'], explanation: '파일 업로드는 컨텍스트에 직접 넣는 것입니다. RAG는 문서를 인덱싱, 청킹, 검색합니다.' }

// Prompting
quizSv['prompt-biz-1'] = { question: 'Du ber AI "skriv ett mejl" och får ett generiskt, oanvändbart resultat. Vad gick fel?', options: ['AI-modellen är för liten', 'Prompten var för vag — du angav inte mottagare, ämne, ton eller längd', 'AI kan inte skriva mejl', 'Du behöver en dyrare modell'], explanation: 'Som att ge instruktioner till en ny praktikant — "skriv något" ger vaga resultat.' }
quizSv['prompt-biz-2'] = { question: 'Vilken promptteknik liknar mest att utbilda en nyanställd genom att visa exempel på bra arbete?', options: ['Ge AI:n en roll', 'Be om steg-för-steg-tänkande', 'Ge exempel på hur bra resultat ser ut', 'Ange utdataformat'], explanation: 'Att visa exempel är precis som att utbilda genom att visa.' }

quizKo['prompt-biz-1'] = { question: 'AI에게 "이메일 써줘"라고 했더니 일반적이고 쓸모없는 결과가 나왔습니다. 무엇이 잘못되었나요?', options: ['AI 모델이 너무 작습니다', '프롬프트가 너무 모호했습니다 — 수신자, 주제, 톤, 길이를 지정하지 않았습니다', 'AI는 이메일을 쓸 수 없습니다', '더 비싼 AI 모델이 필요합니다'], explanation: '새 인턴에게 지시하는 것과 같습니다 — "뭔가 써줘"는 모호한 결과를 줍니다.' }
quizKo['prompt-biz-2'] = { question: '좋은 작업 예시를 보여주며 신입사원을 교육하는 것과 가장 비슷한 프롬프팅 기법은?', options: ['AI에게 역할 부여', '단계별 사고 요청', '좋은 결과물의 예시 제공', '출력 형식 지정'], explanation: '예시를 보여주는 것은 정확히 예시로 교육하는 것과 같습니다.' }

// Agents
quizSv['agents-biz-1'] = { question: 'Ert företag vill automatisera kundsupport. Kunder frågar om orderstatus, returpolicyer och fakturering. Vilken agentuppsättning passar bäst?', options: ['En agent som hanterar allt', 'En routeragent som identifierar ämnet och lämnar över till specialistagenter', 'Ett multi-agent-team där agenter diskuterar svaret', 'Ingen agent behövs — bara en FAQ-sida'], explanation: 'Olika typer av förfrågningar behöver olika system och arbetsflöden.' }
quizSv['agents-biz-2'] = { question: 'Er AI-agent skriver mejlutkast till kunder. En kollega säger "låt den bara skicka automatiskt." Bästa svaret?', options: ['Bra idé — automatisering sparar tid', 'Börja med utkast-och-godkänn. Automatisera rutinmejl när vi litar på kvaliteten.', 'Låt aldrig AI skicka mejl', 'Bara om vi använder den dyraste modellen'], explanation: 'Matcha övervakning med risk. Rutinmejl kan automatiseras, känsliga behöver granskning.' }
quizSv['agents-biz-3'] = { question: 'Er VD frågar: "Vad är skillnaden mellan vår chattbot och dessa nya AI-agenter?" Förklara.', modelAnswer: 'Vår chattbot är som en kunnig kollega du kan smsa — den svarar på frågor men kan inte göra något. En AI-agent är mer som en personlig assistent — den kan kolla kontostatus, skriva uppföljningsmejl och boka möten. Skillnaden: en chattbot pratar, en agent agerar.', options: undefined, explanation: 'Kärnskillnaden är handling vs information.' }
quizSv['agents-biz-4'] = { question: 'Vilken uppgift passar SÄMST för en AI-agent?', options: ['Undersöka konkurrenter och sammanfatta', 'Beräkna exakta skattebelopp baserat på lagstadgade skatteklasser', 'Boka möten genom att kolla flera kalendrar', 'Skriva utkast till kundsvar'], explanation: 'Skatteberäkningar följer exakta lagregler — de är deterministiska.' }
quizSv['agents-biz-5'] = { question: 'MCP kallas ofta "AI:ns USB-C." Vad gör det egentligen?', options: ['Det gör AI-modeller snabbare', 'Det är en universell standard för att koppla AI till externa verktyg och data', 'Det är en specifik produkt från Anthropic', 'Det krypterar data som skickas till AI'], explanation: 'MCP är en öppen standard som standardiserar hur AI ansluter till verktyg.' }

quizKo['agents-biz-1'] = { question: '회사가 고객 지원을 자동화하려 합니다. 고객이 주문 상태, 반품 정책, 청구에 대해 문의합니다. 어떤 에이전트 설정이 가장 적합할까요?', options: ['모든 것을 처리하는 하나의 에이전트', '주제를 감지하고 전문 에이전트에게 넘기는 라우터 에이전트', '에이전트들이 답을 논의하는 멀티 에이전트 팀', '에이전트 불필요 — FAQ 페이지만'], explanation: '다른 유형의 요청은 다른 시스템과 워크플로우가 필요합니다.' }
quizKo['agents-biz-2'] = { question: 'AI 에이전트가 고객에게 이메일 초안을 작성합니다. 동료가 "자동으로 보내게 하자"고 합니다. 가장 좋은 대응은?', options: ['좋은 아이디어 — 자동화가 시간을 절약', '초안 작성 후 승인으로 시작. 품질을 신뢰하면 일상적인 이메일 자동 발송.', 'AI가 이메일을 보내게 하면 안 됨', '가장 비싼 모델을 사용할 때만'], explanation: '감독을 위험에 맞추세요. 일상적인 이메일은 자동화 가능, 민감한 것은 검토 필요.' }
quizKo['agents-biz-3'] = { question: 'CEO가 묻습니다: "우리 챗봇과 새로운 AI 에이전트의 차이가 뭐야?" 설명하세요.', modelAnswer: '현재 챗봇은 문자를 보낼 수 있는 박식한 동료와 같습니다 — 질문에 답하지만 아무것도 할 수 없습니다. AI 에이전트는 개인 비서와 같습니다 — 계정 상태 확인, 후속 이메일 작성, 회의 예약이 가능합니다. 핵심 차이: 챗봇은 말하고, 에이전트는 행동합니다.', options: undefined, explanation: '핵심 구분은 행동 vs 정보입니다.' }
quizKo['agents-biz-4'] = { question: 'AI 에이전트에 가장 적합하지 않은 작업은?', options: ['경쟁사 조사 및 요약', '법적 세금 구간에 따른 정확한 세금 계산', '여러 캘린더를 확인하여 회의 예약', '고객 문의에 대한 응답 초안 작성'], explanation: '세금 계산은 정확한 법적 규칙을 따릅니다 — 결정론적입니다.' }
quizKo['agents-biz-5'] = { question: 'MCP(모델 컨텍스트 프로토콜)는 종종 "AI의 USB-C"라고 불립니다. 실제로 무엇을 하나요?', options: ['AI 모델을 더 빠르게 만듭니다', '외부 도구와 데이터에 AI를 연결하는 범용 표준입니다', 'Anthropic이 판매하는 특정 제품입니다', 'AI 모델로 전송되는 데이터를 암호화합니다'], explanation: 'MCP는 AI가 도구에 연결하는 방식을 표준화하는 오픈 표준입니다.' }

// AI in Org
quizSv['org-biz-1'] = { question: 'Er VD vill ha helt autonom AI-kundsupport till Q4. Bästa tillvägagångssättet?', options: ['Gå direkt till full autonomi', 'Börja på Nivå 2 för rutinuppgifter, expandera gradvis baserat på data', 'Använd inte AI för kundsupport', 'Vänta tills AI är 100% pålitlig'], explanation: 'Waymo-metoden: börja smalt, expandera med bevis.' }
quizSv['org-biz-2'] = { question: 'Upp till 40% av agentiska AI-initiativ kan avbrytas till 2027. Huvudorsaken?', options: ['AI-modellerna är inte tillräckligt bra', 'Organisationer är inte redo — styrningsluckor och oklart ansvar', 'AI är för dyrt', 'Kunder vill inte interagera med AI'], explanation: 'Misslyckandena är organisatoriska, inte teknologiska.' }
quizSv['org-biz-3'] = { question: 'En AI-agent kan utfärda återbetalningar upp till 1000 kr autonomt. En kund begär 950 kr för ett uppenbart bedrägligt krav. Agenten behandlar det. Vilken styrningskontroll saknades?', options: ['Beloppsgränsen var för hög', 'Agenten behövde bedrägeridetekteringslogik — beloppsgränser ensamma fångar inte kontextuella problem', 'AI bör aldrig utfärda återbetalningar', 'Agenten behövde en större modell'], explanation: 'Beloppsgränser är nödvändiga men inte tillräckliga.' }
quizSv['org-biz-4'] = { question: 'Självkörande bilar är statistiskt säkrare än mänskliga förare, men många känner sig mindre säkra. Hur gäller denna parallell för AI-agenter?', modelAnswer: 'Parallellen handlar om upplevd kontroll vs faktisk säkerhet. Människor accepterar risker de känner att de kontrollerar mer än risker de inte kontrollerar. Även om AI gör färre fel känns ett enda AI-misstag skrämmande. Lösningen: transparens, meningsfull övervakning, dela data om resultat, och låt människor välja bort initialt.', options: undefined, explanation: 'Förtroendeglappet är emotionellt, inte rationellt.' }

quizKo['org-biz-1'] = { question: 'CEO가 Q4까지 완전 자율 AI 고객 지원을 원합니다. 가장 좋은 접근 방식은?', options: ['바로 완전 자율로', '일상 업무에 레벨 2로 시작, 성과 데이터에 기반하여 점진적 확장', '고객 지원에 AI를 사용하지 않음', 'AI가 100% 신뢰할 수 있을 때까지 대기'], explanation: 'Waymo 접근법: 좁게 시작하고 증거로 확장.' }
quizKo['org-biz-2'] = { question: '에이전틱 AI 이니셔티브의 최대 40%가 2027년까지 취소될 수 있습니다. 주요 원인은?', options: ['AI 모델이 충분히 좋지 않음', '조직이 준비되지 않음 — 거버넌스 격차와 불명확한 책임', 'AI가 너무 비쌈', '고객이 AI와 상호작용을 원하지 않음'], explanation: '실패는 기술적이 아니라 조직적입니다.' }
quizKo['org-biz-3'] = { question: 'AI 에이전트가 10만원까지 자율적으로 환불할 수 있습니다. 고객이 명백히 사기인 9만5천원 환불을 요청합니다. 에이전트가 처리합니다. 어떤 거버넌스 통제가 빠졌나요?', options: ['지출 한도가 너무 높았음', '에이전트에 사기 탐지 로직이 필요 — 지출 한도만으로는 맥락적 문제를 잡지 못함', 'AI는 절대 환불하면 안 됨', '에이전트에 더 큰 모델이 필요'], explanation: '지출 한도는 필요하지만 충분하지 않습니다.' }
quizKo['org-biz-4'] = { question: '자율주행차는 통계적으로 인간 운전자보다 안전하지만, 많은 사람이 덜 안전하다고 느낍니다. 이 유사점이 AI 에이전트에 어떻게 적용되나요?', modelAnswer: '유사점은 인지된 통제 vs 실제 안전에 관한 것입니다. 사람들은 통제한다고 느끼는 위험을 그렇지 않은 위험보다 더 수용합니다. AI가 실수를 덜 하더라도 하나의 AI 실수가 더 무섭게 느껴집니다. 해결책: 투명성, 의미 있는 감독, 결과 데이터 공유, 초기에 선택 해제 허용.', options: undefined, explanation: '신뢰 격차는 감정적이지 이성적이지 않습니다.' }

// Agentic Work (Use AI course)
quizSv['agwork-1'] = { question: 'Vilken uppgift är den bästa kandidaten att delegera till en agentisk arbetsapp?', options: ['Att besluta vilka teammedlemmar som ska sägas upp detta kvartal', 'Att stämma av 240 utläggsrader mot en skriftlig policy och flagga överträdelserna för din granskning', 'Att godkänna den slutliga formuleringen av ett juridiskt avtal före signering', 'Att välja företagets strategiska inriktning för nästa år'], explanation: 'En delegerbar uppgift är flerstegig (värd uppsättningen), har en tydlig definition av klart (så att du kan kontrollera den) och är återställbar om den blir fel (en flaggad lista du granskar, inte ett oåterkalleligt beslut). Utläggsavstämningen passar alla tre; de andra är högomdömes- eller oåterkalleliga beslut som du behåller.' }
quizSv['agwork-2'] = { question: 'En agent får utfärda återbetalningar upp till 1 000 USD på egen hand. Den godkänner en uppenbart bedräglig återbetalning på 950 USD. Vilket skyddsräcke saknades, och varför räckte inte beloppsgränsen?', modelAnswer: 'Det saknade skyddsräcket var ett mänskligt godkännande (human-in-the-loop) för återbetalningar över en risktröskel (eller alla återbetalningar som flaggats som misstänkta). En beloppsgräns begränsar bara storleken på en åtgärd; den ger inget omdöme om huruvida åtgärden är legitim. 950 USD låg under gränsen, så gränsen släppte igenom det — precis som den var utformad. Gränser begränsar storlek; de upptäcker inte bedrägeri. Lösningen är att dirigera riskfyllda eller avvikande återbetalningar till en människa innan de betalas ut, och att hålla ett revisionsspår så att beslutet kan granskas.', options: undefined, explanation: 'Beloppstak avgränsar hur mycket, aldrig om-det-borde. Betydelsefulla eller avvikande åtgärder behöver en mänsklig kontrollpunkt, inte bara en mindre siffra.' }

quizKo['agwork-1'] = { question: '에이전틱 업무 앱에 위임하기에 가장 좋은 후보 작업은 무엇입니까?', options: ['이번 분기에 해고할 팀원을 결정하는 것', '240개의 경비 항목을 작성된 정책에 대조하여 위반 사항을 검토용으로 표시하는 것', '서명 전 법률 계약서의 최종 문구를 승인하는 것', '내년 회사의 전략 방향을 선택하는 것'], explanation: '위임 가능한 작업은 다단계(설정할 가치가 있음)이고, 완료의 정의가 명확하며(확인할 수 있음), 틀려도 복구 가능합니다(검토하는 표시된 목록이지 되돌릴 수 없는 결정이 아님). 경비 대조는 이 세 가지를 모두 충족하고, 나머지는 당신이 쥐고 있어야 할 고판단 또는 되돌릴 수 없는 결정입니다.' }
quizKo['agwork-2'] = { question: '에이전트가 자체적으로 최대 $1,000까지 환불을 발행할 수 있습니다. 명백히 사기인 $950 환불을 승인합니다. 어떤 가드레일이 빠졌으며, 지출 한도만으로 충분하지 않았던 이유는 무엇입니까?', modelAnswer: '빠진 가드레일은 위험 임계값을 초과하는 환불(또는 의심스럽다고 표시된 모든 환불)에 대한 사람 승인(human-in-the-loop)이었습니다. 지출 한도는 행동의 규모만 제한할 뿐, 그 행동이 정당한지에 대한 판단은 제공하지 않습니다. $950는 한도 미만이었으므로 한도가 이를 통과시켰습니다 — 설계된 그대로입니다. 한도는 크기를 제한하지 사기를 탐지하지 않습니다. 해결책은 위험하거나 이상한 환불을 지급 전에 사람에게 보내고, 결정을 검토할 수 있도록 감사 추적을 유지하는 것입니다.', options: undefined, explanation: '지출 상한은 얼마나를 제한하지, 해야 하는지는 결코 제한하지 않습니다. 중대하거나 이상한 행동에는 더 작은 숫자가 아니라 사람 체크포인트가 필요합니다.' }
quizSv['agwork-3'] = { question: 'Du har delegerat samma veckovisa lageravstämningsuppgift till en agent fyra veckor i rad. Vilket är nästa drag med högst hävstång?', options: ['Fortsätt delegera den varje vecka — den fungerar fint', 'Be en AI-appbyggare göra dig ett litet återanvändbart verktyg som gör avstämningen, granska det sedan och behåll det', 'Anlita en utvecklare för att bygga ett skräddarsytt system', 'Gå tillbaka till att göra det för hand för att behålla kontrollen'], explanation: 'En delegering som upprepas varje vecka med samma form är signalen att den vill bli ett verktyg. No-code/low-code-appbyggare låter dig beställa ett återanvändbart verktyg genom att beskriva det — samma brief, större leverans. Du granskar fortfarande det den bygger och äger resultatet; du behöver ingen utvecklare eller budgetbegäran.' }
quizKo['agwork-3'] = { question: '같은 주간 재고 대조 작업을 에이전트에게 4주 연속 위임했습니다. 더 높은 레버리지의 다음 움직임은 무엇입니까?', options: ['매주 계속 위임한다 — 잘 작동한다', 'AI 앱 빌더에게 대조를 해주는 작고 재사용 가능한 도구를 만들어 달라고 한 다음, 검토하고 보관한다', '맞춤형 시스템을 구축할 개발자를 고용한다', '통제를 유지하기 위해 손으로 하는 것으로 돌아간다'], explanation: '같은 모양으로 매주 반복되는 위임은 그것이 도구가 되고 싶어 한다는 신호입니다. 노코드/로우코드 앱 빌더는 설명만으로 재사용 가능한 도구를 의뢰하게 해줍니다 — 같은 브리프, 더 큰 결과물. 당신은 여전히 만든 것을 검토하고 결과를 책임집니다; 개발자나 예산 요청은 필요 없습니다.' }

// Generative AI Beyond Text (Use AI course)
quizSv['genai-1'] = { question: 'En kollega säger "låt oss lägga till en funktion där användare fotograferar ett dokument och vi plockar ut fälten." Vilken modalitet och integration passar mest direkt?', options: ['Träna en egen bilddiffusionsmodell på dokument', 'En multimodal/visionmodell via API — skicka bilden + en prompt som ber om fälten som strukturerad JSON', 'En text-till-tal-modell', 'En videogenereringsmodell'], explanation: 'Att läsa innehåll ur en bild är ett multimodalt/visionjobb: skicka bilden och en prompt som begär strukturerad JSON (helst med ett strikt schema), få JSON tillbaka. Det är ett vanligt API-anrop — ingen träning behövs. Diffusionsmodeller genererar bilder, de läser dem inte; TTS och video är orelaterade.' }
quizSv['genai-2'] = { question: 'Att generera ett kort videoklipp kostar långt mer än att generera en bild, vilket kostar långt mer än ett vision-på-text-anrop. Vad innebär den kostnadsstrukturen för hur du designar en mediefunktion?', modelAnswer: 'Budgetera per tillgång och designa kring kostnadsgradienten: föredra den billigaste modaliteten som klarar jobbet (vision/text framför bild framför video), generera i minsta storlek/längd som fungerar, cacha och återanvänd aggressivt, och reservera dyr videogenerering för värdefulla ögonblick med en människa i loopen. Gör kostnad-per-tillgång till ett synligt mätvärde, sätt tak, och låt inte användare utlösa obegränsade dyra genereringar. Tekniken är samma request/response som text, men enhetsekonomin tvingar fram en återhållsamhet som textfunktioner sällan behöver.', options: undefined, explanation: 'Medieanrop debiteras per bild/sekund, inte per token, och gradienten är brant. Bra designer använder som standard den billigaste tillräckliga modaliteten och sätter tak på de dyra.' }
quizSv['genai-biz-1'] = { question: 'Marknadsföring vill ha 30 varumärkesanpassade bildvariationer för en lanseringssida, snabbt. Vilken typ av verktyg passar bäst?', options: ['Ett videogenereringsverktyg', 'Ett bildgenereringsverktyg (med varumärkesgranskning före publicering)', 'Ett tal-till-text-transkriberingsverktyg', 'Inget — bara en mänsklig designer kan göra detta'], explanation: 'Bildgenerering producerar och redigerar varumärkesanpassade visuals på minuter till nära noll kostnad — idealiskt för volym och A/B-variationer. Behåll en varumärkesgranskning före publicering, och ange AI-bilder där det krävs. Video och STT är fel modalitet här.' }
quizSv['genai-biz-2'] = { question: 'Ert team vill ha ett varumärkesanpassat voiceover och någon föreslår att klona en populär kändis röst för att berätta det. Vad är rätt beslut?', options: ['Kör på — om AI gjorde det är det okej att använda', 'Klona inte en verklig persons röst utan samtycke; använd en licensierad eller syntetisk varumärkesröst med tydliga rättigheter', 'Klona bara rösten om videon är intern', 'Kloning är alltid olagligt, så undvik alla AI-röstverktyg'], explanation: 'Att klona en verklig persons röst utan samtycke är ett rättighets- och ryktesproblem — "det var AI" är inget försvar. Använd licensierade eller syntetiska röster med tydliga kommersiella villkor. AI-röstverktygen i sig är okej; att klona någon du inte har rättigheter till är problemet.' }

quizKo['genai-1'] = { question: '동료가 "사용자가 문서를 촬영하면 필드를 추출하는 기능을 추가하자"고 말합니다. 어떤 모달리티와 통합이 가장 직접적으로 적합합니까?', options: ['문서로 커스텀 이미지 디퓨전 모델을 학습', '멀티모달/비전 모델을 API로 — 이미지와 함께 필드를 구조화된 JSON으로 요청하는 프롬프트를 전송', '텍스트 음성 변환 모델', '비디오 생성 모델'], explanation: '이미지에서 내용을 읽는 것은 멀티모달/비전 작업입니다: 이미지와 구조화된 JSON(가급적 엄격한 스키마)을 요청하는 프롬프트를 보내고 JSON을 받습니다. 평범한 API 호출이며 학습이 필요 없습니다. 디퓨전 모델은 이미지를 생성하지 읽지 않으며, TTS와 비디오는 무관합니다.' }
quizKo['genai-2'] = { question: '짧은 비디오 클립을 생성하는 것은 이미지를 생성하는 것보다 훨씬 비싸고, 이미지는 텍스트에 대한 비전 호출보다 훨씬 비쌉니다. 이 비용 구조는 미디어 기능을 어떻게 설계할지에 무엇을 시사합니까?', modelAnswer: '자산당 예산을 세우고 비용 그래디언트를 중심으로 설계합니다: 작업을 해내는 가장 저렴한 모달리티를 선호하고(비디오보다 이미지, 이미지보다 비전/텍스트), 작동하는 가장 작은 크기/길이로 생성하고, 적극적으로 캐싱하고 재사용하며, 비싼 비디오 생성은 사람이 개입하는 고가치 순간에 예약합니다. 자산당 비용을 가시적인 지표로 만들고, 상한을 설정하고, 사용자가 무제한의 비싼 생성을 유발하지 못하게 합니다. 엔지니어링은 텍스트와 동일한 요청/응답이지만, 단위 경제성이 텍스트 기능에는 거의 필요 없는 절제를 강제합니다.', options: undefined, explanation: '미디어 호출은 토큰이 아니라 이미지/초 단위로 청구되며 그래디언트가 가파릅니다. 좋은 설계는 기본적으로 가장 저렴한 충분한 모달리티를 사용하고 비싼 것에 상한을 둡니다.' }
quizKo['genai-biz-1'] = { question: '마케팅이 출시 페이지를 위해 브랜드에 맞는 이미지 변형 30개를 빠르게 원합니다. 어떤 종류의 도구가 가장 적합합니까?', options: ['비디오 생성 도구', '이미지 생성 도구(게시 전 브랜드 검토 포함)', '음성 텍스트 변환 도구', '없음 — 사람 디자이너만 할 수 있음'], explanation: '이미지 생성은 거의 무료 비용으로 몇 분 만에 브랜드에 맞는 비주얼을 제작하고 편집합니다 — 대량 및 A/B 변형에 이상적입니다. 게시 전 브랜드 정확성 검토를 유지하고, 필요한 경우 AI 이미지임을 공개합니다. 비디오와 STT는 여기서 잘못된 모달리티입니다.' }
quizKo['genai-biz-2'] = { question: '팀이 브랜드 보이스오버를 원하는데 누군가 인기 유명인의 목소리를 복제해 내레이션하자고 제안합니다. 올바른 결정은 무엇입니까?', options: ['진행하세요 — AI가 만들었으면 사용해도 괜찮습니다', '동의 없이 실제 사람의 목소리를 복제하지 마세요; 명확한 권리를 가진 라이선스 또는 합성 브랜드 보이스를 사용하세요', '비디오가 내부용일 때만 목소리를 복제하세요', '복제는 항상 불법이므로 모든 AI 음성 도구를 피하세요'], explanation: '동의 없이 실제 사람의 목소리를 복제하는 것은 권리 및 평판 문제입니다 — "AI였다"는 변명이 되지 않습니다. 명확한 상업적 조건을 가진 라이선스 또는 합성 목소리를 사용하세요. AI 음성 도구 자체는 괜찮습니다; 권리가 없는 사람을 복제하는 것이 문제입니다.' }

// Helper: translate questions array based on language
import type { Language } from './LanguageContext'

const allTranslations: Record<Language, Record<string, QT>> = { en: {}, sv: quizSv, ko: quizKo }

export function translateQuestions(questions: Question[], lang: Language): Question[] {
  if (lang === 'en') return questions
  const t = allTranslations[lang] ?? {}
  return questions.map(q => {
    const tr = t[q.id]
    if (!tr) return q
    return {
      ...q,
      question: tr.question ?? q.question,
      options: tr.options ?? q.options,
      explanation: tr.explanation ?? q.explanation,
      modelAnswer: tr.modelAnswer ?? q.modelAnswer,
    }
  })
}

// === TECHNICAL TRACK QUIZ TRANSLATIONS ===

// AI Problem (technical)
quizSv['aiproblem-1'] = { question: 'Ett företag vill förutsäga vilka kunder som säger upp sig nästa månad med historisk faktureringsdata i ett kalkylblad. Vilken metod passar bäst?', options: ['En LLM — den kan resonera om kundbeteende', 'Klassisk ML (t.ex. gradient boosting) — strukturerad tabelldata med ett prediktionsmål', 'Deep learning CNN — för att hitta mönster', 'Ett regelbaserat system — sätt bara ett tröskelvärde'], explanation: 'Strukturerad/tabelldata med ett tydligt prediktionsmål är sweet spot för klassisk ML.' }
quizSv['aiproblem-2'] = { question: 'Vad är den viktigaste skillnaden mellan "deep learning" och "machine learning"?', options: ['Deep learning använder mer data', 'Deep learning är en delmängd av ML som använder neurala nätverk med många lager', 'Machine learning är äldre och därför mindre exakt', 'Deep learning kan bara användas för bilder'], explanation: 'Deep learning använder flerlagers neurala nätverk. "Deep" syftar på djupet (antal lager).' }
quizSv['aiproblem-3'] = { question: 'En skatteberäkningsmotor behöver tillämpa olika satser baserat på inkomstklasser. Reglerna definieras i lag. Vad ska du bygga?', options: ['Träna en ML-modell på tidigare deklarationer', 'Använd en LLM för att tolka skattelagen', 'Ett regelbaserat system — logiken är deterministisk', 'En deep learning-modell som lär sig skattereglerna'], explanation: 'När logiken är helt deterministisk och definierad av regler är traditionell programvara rätt verktyg.' }
quizSv['aiproblem-4'] = { question: 'Förklara varför en LLM inte bara är "en större maskininlärningsmodell."', modelAnswer: 'LLM:er skiljer sig i art, inte bara skala. Klassisk ML arbetar med strukturerade features och lär sig statistiska mönster för specifika uppgifter. LLM:er tränas på rå text för att förutsäga nästa token, vilket tvingar dem att lära sig språkstruktur, världskunskap och resonemang som emergenta förmågor.', options: undefined, explanation: 'LLM:er lär sig allmän språkförståelse genom next-token prediction.' }

quizKo['aiproblem-1'] = { question: '회사가 스프레드시트의 과거 청구 데이터를 사용하여 다음 달 구독을 취소할 고객을 예측하려 합니다. 어떤 접근 방식이 가장 적합할까요?', options: ['LLM — 고객 행동에 대해 추론 가능', '클래식 ML (예: gradient boosting) — 예측 목표가 있는 정형 테이블 데이터', '딥러닝 CNN — 패턴 감지', '규칙 기반 시스템 — 임계값 설정'], explanation: '명확한 예측 목표가 있는 정형/테이블 데이터는 클래식 ML의 최적 영역입니다.' }
quizKo['aiproblem-2'] = { question: '"딥러닝"과 "머신러닝"의 핵심 차이점은?', options: ['딥러닝이 더 많은 데이터를 사용', '딥러닝은 많은 레이어의 신경망을 사용하는 ML의 부분집합', '머신러닝이 더 오래되어 덜 정확', '딥러닝은 이미지에만 사용 가능'], explanation: '딥러닝은 다층 신경망을 사용합니다. "딥"은 레이어 수의 깊이를 의미합니다.' }
quizKo['aiproblem-3'] = { question: '세금 계산 엔진이 소득 구간에 따라 다른 세율을 적용해야 합니다. 규칙은 법으로 정의됩니다. 무엇을 만들어야 할까요?', options: ['과거 세금 신고서로 ML 모델 학습', 'LLM으로 세법 해석', '규칙 기반 시스템 — 로직이 결정론적', '세금 규칙을 학습하는 딥러닝 모델'], explanation: '로직이 완전히 결정론적이고 규칙으로 정의될 때 전통적인 소프트웨어가 올바른 도구입니다.' }
quizKo['aiproblem-4'] = { question: 'LLM이 단순히 "더 큰 머신러닝 모델"이 아닌 이유를 설명하세요.', modelAnswer: 'LLM은 규모가 아닌 종류가 다릅니다. 클래식 ML은 구조화된 피처로 특정 작업의 통계적 패턴을 학습합니다. LLM은 원시 텍스트에서 다음 토큰을 예측하도록 학습되어 언어 구조, 세계 지식, 추론을 창발적 능력으로 학습합니다.', options: undefined, explanation: 'LLM은 next-token prediction을 통해 일반적인 언어 이해를 학습합니다.' }

// Data Foundations (technical)
quizSv['datafoundations-1'] = { question: 'En kundrecension som "Bra produkt, snabb leverans!" är ett exempel på:', options: ['Strukturerad data', 'Semi-strukturerad data', 'Ostrukturerad data — fritext utan fördefinierat schema', 'Tabelldata'], explanation: 'Fritext är ostrukturerad data — den har inget fördefinierat schema.' }
quizSv['datafoundations-2'] = { question: 'I en datapipeline, vad är den viktigaste skillnaden mellan ETL och ELT?', options: ['ETL är snabbare', 'ELT laddar rå data först, transformerar sedan i destinationen', 'ETL är för strukturerad data, ELT för ostrukturerad', 'Ingen praktisk skillnad'], explanation: 'ELT laddar rå data först och transformerar sedan med destinationens beräkningskraft.' }
quizSv['datafoundations-3'] = { question: 'Du tränar en sentimentklassificerare på produktrecensioner, men den presterar dåligt på medicinsk patientfeedback. Troligaste orsaken?', options: ['Fel modellarkitektur', 'Medicinsk text har längre meningar', 'Datakvalitetsproblem: träningsdatans distribution matchar inte måldomänen', 'Modellen behöver fler parametrar'], explanation: 'Klassisk datadistributions-mismatch.' }
quizSv['datafoundations-4'] = { question: 'Varför spelar "skräp in, skräp ut" ännu större roll för LLM:er än för traditionell programvara?', modelAnswer: 'LLM:er tränade på lågkvalitetsdata producerar resultat som ser övertygande ut men är subtilt felaktiga. Modellen lär sig bias, fel och mönster i sin träningsdata. Faran är att LLM-resultat är övertygande även när de är felaktiga.', options: undefined, explanation: 'LLM:er förstärker datakvalitetsproblem eftersom de producerar flytande, självsäker text oavsett om kunskapen är korrekt.' }

quizKo['datafoundations-1'] = { question: '"좋은 제품, 빠른 배송!"이라는 고객 리뷰는 다음의 예입니다:', options: ['정형 데이터', '반정형 데이터', '비정형 데이터 — 사전 정의된 스키마 없는 자유 텍스트', '테이블 데이터'], explanation: '자유 텍스트는 비정형 데이터입니다 — 사전 정의된 스키마가 없습니다.' }
quizKo['datafoundations-2'] = { question: '데이터 파이프라인에서 ETL과 ELT의 핵심 차이점은?', options: ['ETL이 더 빠름', 'ELT는 원시 데이터를 먼저 로드한 후 대상에서 변환', 'ETL은 정형 데이터용, ELT는 비정형 데이터용', '실질적 차이 없음'], explanation: 'ELT는 원시 데이터를 먼저 로드하고 대상의 컴퓨팅 파워로 변환합니다.' }
quizKo['datafoundations-3'] = { question: '제품 리뷰로 감성 분류기를 학습했는데 의료 환자 피드백에서 성능이 나쁩니다. 가장 가능성 높은 원인은?', options: ['잘못된 모델 아키텍처', '의료 텍스트가 더 긴 문장', '데이터 품질 문제: 학습 데이터 분포가 대상 도메인과 불일치', '모델에 더 많은 파라미터 필요'], explanation: '전형적인 데이터 분포 불일치입니다.' }
quizKo['datafoundations-4'] = { question: '"쓰레기를 넣으면 쓰레기가 나온다"가 전통적 소프트웨어보다 LLM에 더 중요한 이유는?', modelAnswer: '저품질 데이터로 학습된 LLM은 설득력 있어 보이지만 미묘하게 틀린 결과를 생성합니다. 모델은 학습 데이터의 편향, 오류, 패턴을 학습합니다. 위험은 LLM 출력이 틀려도 설득력 있다는 것입니다.', options: undefined, explanation: 'LLM은 유창하고 자신감 있는 텍스트를 생성하므로 데이터 품질 문제를 증폭합니다.' }

// Training
quizSv['training-1'] = { question: 'Före träning är en modells vikter slumpmässiga tal. Om du bad denna otränade modell komplettera "Frankrikes huvudstad är ___", vad skulle hända?', options: ['Den skulle svara "Paris"', 'Den skulle ge slumpmässigt nonsens — vikterna har inga inlärda mönster', 'Den kan inte köras utan tränade vikter', 'Den skulle ge det vanligaste ordet'], explanation: 'Slumpmässiga vikter ger slumpmässiga förutsägelser.' }
quizSv['training-2'] = { question: 'I träningsloopen, vilken är rätt ordning för en iteration?', options: ['Beräkna förlust → Forward pass → Backward pass → Uppdatera vikter', 'Ladda batch → Backward pass → Forward pass → Beräkna förlust', 'Ladda batch → Forward pass → Beräkna förlust → Backward pass → Uppdatera vikter', 'Forward pass → Ladda batch → Uppdatera vikter'], explanation: 'Varje steg beror på det föregående.' }
quizSv['training-3'] = { question: 'Förlustfunktionen mäter "hur fel modellen hade." Under nanochat-träning sjönk förlusten från ~10 till ~2.4. Vad betyder en förlust på 2.4?', options: ['Modellen har 2.4% fel', 'Modellen är 2.4× bättre än slumpen', 'Cross-entropy-förlusten 2.4 betyder att modellens sannolikhetsfördelning är mycket mer koncentrerad på rätt svar', 'Modellen har lärt sig 2.4 av 10 språkfärdigheter'], explanation: 'Cross-entropy-förlust mäter hur långt modellens förutsagda fördelning är från det rätta svaret.' }
quizSv['training-4'] = { question: 'I nanochat är --depth-flaggan "den enda ratten du ställer in." Varför?', options: ['Andra parametrar spelar ingen roll', 'Det är en förenkling för nybörjare', 'Forskning har etablerat optimala förhållanden mellan djup, bredd och huvuden', 'Det är en begränsning i koden'], explanation: 'Skalningslagar har visat att modelldimensioner har optimala förhållanden.' }
quizSv['training-5'] = { question: 'nanochat-checkpointen är 9.6 GB men den slutliga modellen är 3.2 GB. Förklara varför.', modelAnswer: 'En checkpoint innehåller allt som behövs för att återuppta träning: modellvikter (3.2 GB) plus optimerartillstånd (momentum, variansestimat — ungefär 2× modellstorleken för Adam) plus schema och stegräknare. Modellfilen innehåller bara de tränade vikterna.', options: undefined, explanation: 'Checkpoints är för att återuppta träning. Modellfiler är för inferens.' }

quizKo['training-1'] = { question: '학습 전 모델의 가중치는 랜덤 숫자입니다. 이 미학습 모델에게 "프랑스의 수도는 ___"을 완성하라고 하면?', options: ['"파리"라고 출력', '랜덤 의미 없는 텍스트 출력 — 가중치에 학습된 패턴 없음', '학습된 가중치 없이는 실행 불가', '가장 흔한 단어 출력'], explanation: '랜덤 가중치는 랜덤 예측을 의미합니다.' }
quizKo['training-2'] = { question: '학습 루프에서 한 반복의 올바른 순서는?', options: ['손실 계산 → 순전파 → 역전파 → 가중치 업데이트', '배치 로드 → 역전파 → 순전파 → 손실 계산', '배치 로드 → 순전파 → 손실 계산 → 역전파 → 가중치 업데이트', '순전파 → 배치 로드 → 가중치 업데이트'], explanation: '각 단계는 이전 단계에 의존합니다.' }
quizKo['training-3'] = { question: '손실 함수는 "모델이 얼마나 틀렸는지"를 측정합니다. nanochat 학습 중 손실이 ~10에서 ~2.4로 떨어졌습니다. 2.4의 손실은 무엇을 의미하나요?', options: ['모델이 2.4% 틀림', '모델이 랜덤보다 2.4배 나음', 'Cross-entropy 손실 2.4는 모델의 확률 분포가 정답에 훨씬 더 집중됨을 의미', '모델이 10개 중 2.4개 언어 능력 학습'], explanation: 'Cross-entropy 손실은 모델의 예측 분포가 정답에서 얼마나 먼지를 측정합니다.' }
quizKo['training-4'] = { question: 'nanochat에서 --depth 플래그가 "설정하는 유일한 다이얼"인 이유는?', options: ['다른 파라미터는 중요하지 않음', '초보자를 위한 단순화', '연구가 깊이, 너비, 헤드 간의 최적 비율을 확립했기 때문', '코드의 제한'], explanation: '스케일링 법칙 연구가 모델 차원의 최적 비율을 보여주었습니다.' }
quizKo['training-5'] = { question: 'nanochat 체크포인트는 9.6GB이지만 최종 모델은 3.2GB입니다. 이유를 설명하세요.', modelAnswer: '체크포인트는 학습 재개에 필요한 모든 것을 포함합니다: 모델 가중치(3.2GB) + 옵티마이저 상태(Adam의 경우 모델 크기의 ~2배) + 스케줄과 스텝 카운터. 모델 파일은 학습된 가중치만 포함합니다.', options: undefined, explanation: '체크포인트는 학습 재개용. 모델 파일은 추론용.' }

// Transformer
quizSv['transformer-1'] = { question: 'Vad gör attention-mekanismen i en transformer?', options: ['Komprimerar indata till en fast storlek', 'Låter varje token väga hur relevant varje annan token är för dess representation', 'Genererar slumpmässiga vikter', 'Sorterar tokens i alfabetisk ordning'], explanation: 'Attention beräknar relevanspoäng mellan alla tokenpar.' }
quizSv['transformer-2'] = { question: 'Varför använder transformers "multi-head" attention istället för en enda attention?', options: ['Det är snabbare', 'Varje huvud kan lära sig olika typer av relationer (syntax, semantik, position)', 'Det använder mindre minne', 'Det krävs för att hantera långa sekvenser'], explanation: 'Flera huvuden fångar olika aspekter av relationer mellan tokens.' }
quizSv['transformer-3'] = { question: 'Vad är syftet med positionskodning i en transformer?', options: ['Att komprimera sekvensen', 'Att ge modellen information om ordningsföljd — utan den behandlas "hund biter man" och "man biter hund" identiskt', 'Att snabba upp träningen', 'Att minska minnesanvändningen'], explanation: 'Attention är ordningsokänslig — positionskodning lägger till sekventiell information.' }
quizSv['transformer-4'] = { question: 'I feed-forward-nätverket (FFN) i varje transformerlager, vad händer?', options: ['Tokens kommunicerar med varandra', 'Varje token transformeras oberoende genom ett tvålagers nätverk — detta är där "kunskap" lagras', 'Vikterna uppdateras', 'Sekvensen förkortas'], explanation: 'FFN bearbetar varje token oberoende och lagrar faktakunskap i sina vikter.' }

quizKo['transformer-1'] = { question: '트랜스포머에서 어텐션 메커니즘은 무엇을 하나요?', options: ['입력을 고정 크기로 압축', '각 토큰이 다른 모든 토큰의 관련성을 가중치로 계산', '랜덤 가중치 생성', '토큰을 알파벳순으로 정렬'], explanation: '어텐션은 모든 토큰 쌍 간의 관련성 점수를 계산합니다.' }
quizKo['transformer-2'] = { question: '트랜스포머가 단일 어텐션 대신 "멀티헤드" 어텐션을 사용하는 이유는?', options: ['더 빠름', '각 헤드가 다른 유형의 관계(구문, 의미, 위치)를 학습 가능', '메모리를 덜 사용', '긴 시퀀스 처리에 필요'], explanation: '여러 헤드가 토큰 간 관계의 다양한 측면을 포착합니다.' }
quizKo['transformer-3'] = { question: '트랜스포머에서 위치 인코딩의 목적은?', options: ['시퀀스 압축', '모델에 순서 정보 제공 — 없으면 "개가 사람을 물다"와 "사람이 개를 물다"가 동일하게 처리됨', '학습 속도 향상', '메모리 사용량 감소'], explanation: '어텐션은 순서에 무관합니다 — 위치 인코딩이 순차적 정보를 추가합니다.' }
quizKo['transformer-4'] = { question: '각 트랜스포머 레이어의 피드포워드 네트워크(FFN)에서 무슨 일이 일어나나요?', options: ['토큰들이 서로 통신', '각 토큰이 독립적으로 2층 네트워크를 통해 변환 — "지식"이 저장되는 곳', '가중치가 업데이트됨', '시퀀스가 짧아짐'], explanation: 'FFN은 각 토큰을 독립적으로 처리하고 가중치에 사실적 지식을 저장합니다.' }

// Tokens
quizSv['tokens-1'] = { question: 'Varför tokeniserar LLM:er text istället för att arbeta med enskilda tecken?', options: ['Tecken tar för mycket minne', 'Tokens fångar meningsfulla enheter och minskar sekvenslängden dramatiskt', 'Det är en historisk konvention', 'Tecken kan inte representeras som siffror'], explanation: 'Tokens balanserar vokabulärstorlek mot sekvenslängd.' }
quizSv['tokens-2'] = { question: 'I BPE (Byte Pair Encoding), vad händer under träning av tokenizern?', options: ['Vanliga ord läggs till i en ordbok', 'De vanligaste intilliggande teckenparen slås samman iterativt tills vokabulärstorleken nås', 'Text delas vid mellanslag', 'Varje tecken tilldelas ett slumpmässigt nummer'], explanation: 'BPE bygger vokabulären nerifrån och upp genom att iterativt slå samman de vanligaste paren.' }
quizSv['tokens-3'] = { question: 'Varför kan samma text tokeniseras olika av olika modeller?', options: ['Det är en bugg', 'Varje modell tränar sin egen tokenizer med olika vokabulärstorlek och träningsdata', 'Tokenisering är slumpmässig', 'Bara engelska tokeniseras olika'], explanation: 'Tokenizers är modellspecifika — tränade på modellens träningsdata.' }
quizSv['tokens-4'] = { question: 'Vad händer när en tokenizer stöter på ett ord den aldrig sett förut?', options: ['Den hoppar över det', 'Den bryter ner det i kända sub-tokens eller enskilda bytes', 'Den lägger till det i vokabulären', 'Den ersätter det med [UNK]'], explanation: 'BPE-baserade tokenizers kan hantera alla indata genom att falla tillbaka på sub-tokens och bytes.' }

quizKo['tokens-1'] = { question: 'LLM이 개별 문자 대신 텍스트를 토큰화하는 이유는?', options: ['문자가 너무 많은 메모리 사용', '토큰이 의미 있는 단위를 포착하고 시퀀스 길이를 크게 줄임', '역사적 관례', '문자를 숫자로 표현할 수 없음'], explanation: '토큰은 어휘 크기와 시퀀스 길이의 균형을 맞춥니다.' }
quizKo['tokens-2'] = { question: 'BPE(Byte Pair Encoding)에서 토크나이저 학습 중 무슨 일이 일어나나요?', options: ['일반 단어가 사전에 추가', '가장 빈번한 인접 문자 쌍이 어휘 크기에 도달할 때까지 반복적으로 병합', '텍스트가 공백에서 분할', '각 문자에 랜덤 숫자 할당'], explanation: 'BPE는 가장 빈번한 쌍을 반복적으로 병합하여 어휘를 상향식으로 구축합니다.' }
quizKo['tokens-3'] = { question: '같은 텍스트가 다른 모델에서 다르게 토큰화될 수 있는 이유는?', options: ['버그', '각 모델이 다른 어휘 크기와 학습 데이터로 자체 토크나이저를 학습', '토큰화는 랜덤', '영어만 다르게 토큰화'], explanation: '토크나이저는 모델별로 다릅니다 — 모델의 학습 데이터로 학습됩니다.' }
quizKo['tokens-4'] = { question: '토크나이저가 처음 보는 단어를 만나면 어떻게 되나요?', options: ['건너뜀', '알려진 서브토큰이나 개별 바이트로 분해', '어휘에 추가', '[UNK]로 대체'], explanation: 'BPE 기반 토크나이저는 서브토큰과 바이트로 폴백하여 모든 입력을 처리할 수 있습니다.' }

// Alignment (technical)
quizSv['align-1'] = { question: 'En basmodell kan skriva flytande text, så varför behöver den fortfarande alignment?', modelAnswer: 'Basmodeller tränas att förutsäga nästa token, inte att vara hjälpsamma eller säkra. De kan följa skadliga förfrågningar eller generera trovärdigt klingande felaktig information.', options: undefined, explanation: 'Next-token prediction optimerar för statistisk sannolikhet, inte intentionsanpassning.' }
quizSv['align-2'] = { question: 'Vad är det primära syftet med SFT i alignment-pipelinen?', options: ['Minska modellstorleken', 'Lära modellen formatet för hjälpsamma svar med kurerade exempel', 'Träna en separat modell att poängsätta svar', 'Ersätta RLHF helt'], explanation: 'SFT använder (instruktion, svar)-par för att flytta modellen mot hjälpsamt assistentformat.' }
quizSv['align-3'] = { question: 'Förklara reward-modellens roll i RLHF.', modelAnswer: 'Reward-modellen lär sig mänskliga preferenser från jämförelsedata och producerar en skalär poäng för varje svar. PPO behöver denna poäng som optimeringssignal.', options: undefined, explanation: 'Reward-modellen är bryggan mellan glesa mänskliga bedömningar och den täta signal PPO behöver.' }
quizSv['align-4'] = { question: 'Hur skiljer sig DPO från PPO?', options: ['DPO tränar en större reward-modell', 'DPO hoppar över reward-modellen och optimerar policyn direkt med preferenspar', 'DPO använder mer feedback-data', 'DPO fungerar bara med modeller under 7B'], explanation: 'DPO eliminerar behovet av en separat reward-modell.' }
quizSv['align-5'] = { question: 'Vad är "alignment tax" och varför kan ett team acceptera det?', modelAnswer: 'Alignment tax är prestandakostnaden av alignment — modellen kan bli mindre kapabel på vissa uppgifter. Ett team accepterar det eftersom en oanpassad modell utgör säkerhets- och ryktesrisker.', options: undefined, explanation: 'Alignment är en avvägning: säkerhet och hjälpsamhet kostar viss rå kapacitet.' }

quizKo['align-1'] = { question: '기본 모델이 유창한 텍스트를 쓸 수 있는데 왜 정렬이 필요한가요?', modelAnswer: '기본 모델은 다음 토큰을 예측하도록 학습되었지 도움이 되거나 안전하도록 학습되지 않았습니다. 해로운 요청에 응하거나 그럴듯한 잘못된 정보를 생성할 수 있습니다.', options: undefined, explanation: 'Next-token prediction은 통계적 가능성을 최적화하지 의도 정렬을 하지 않습니다.' }
quizKo['align-2'] = { question: '정렬 파이프라인에서 SFT의 주요 목적은?', options: ['모델 크기 축소', '큐레이션된 예시로 도움이 되는 응답 형식 학습', '응답 품질을 점수화하는 별도 모델 학습', 'RLHF를 완전히 대체'], explanation: 'SFT는 (지시, 응답) 쌍을 사용하여 모델을 도움이 되는 어시스턴트 형식으로 이동시킵니다.' }
quizKo['align-3'] = { question: 'RLHF에서 보상 모델의 역할을 설명하세요.', modelAnswer: '보상 모델은 비교 데이터에서 인간 선호도를 학습하고 각 응답에 대한 스칼라 점수를 생성합니다. PPO는 이 점수를 최적화 신호로 필요로 합니다.', options: undefined, explanation: '보상 모델은 희소한 인간 판단과 PPO가 필요로 하는 밀집 신호 사이의 다리입니다.' }
quizKo['align-4'] = { question: 'DPO는 PPO와 어떻게 다른가요?', options: ['DPO가 더 큰 보상 모델 학습', 'DPO는 보상 모델을 건너뛰고 선호도 쌍으로 정책을 직접 최적화', 'DPO가 더 많은 피드백 데이터 사용', 'DPO는 7B 미만 모델에서만 작동'], explanation: 'DPO는 별도의 보상 모델의 필요성을 제거합니다.' }
quizKo['align-5'] = { question: '"정렬 세금"이란 무엇이고 팀이 왜 수용할까요?', modelAnswer: '정렬 세금은 정렬의 성능 비용입니다 — 모델이 특정 작업에서 덜 능력이 될 수 있습니다. 정렬되지 않은 모델은 안전 및 평판 위험을 초래하므로 팀이 이를 수용합니다.', options: undefined, explanation: '정렬은 트레이드오프입니다: 안전과 도움이 됨은 일부 원시 능력의 비용입니다.' }

// Architecture
quizSv['arch-1'] = { question: 'Vad är den viktigaste skillnaden mellan en dense-modell och en MoE-modell?', options: ['Dense-modeller är alltid bättre', 'MoE aktiverar bara en delmängd av parametrarna per token, vilket ger mer kapacitet till lägre beräkningskostnad', 'MoE-modeller är mindre', 'Dense-modeller kan inte finjusteras'], explanation: 'MoE handlar om selektiv aktivering — mer total kapacitet med samma beräkningsbudget.' }
quizSv['arch-2'] = { question: 'Vad förutsäger Chinchilla-skalningslagen?', options: ['Större modeller är alltid bättre', 'Det finns ett optimalt förhållande mellan modellstorlek och mängd träningsdata', 'Träning bör alltid ta minst en vecka', 'Skalningslagar gäller inte för modeller över 100B'], explanation: 'Chinchilla visade att många modeller var undertränande — de behövde mer data, inte fler parametrar.' }
quizSv['arch-3'] = { question: 'Varför är KV-cachen en flaskhals vid inferens?', options: ['Den gör modellen långsammare att ladda', 'Den växer linjärt med sekvenslängden och kräver GPU-minne för varje tokens nyckel- och värdevektorer', 'Den orsakar numerisk instabilitet', 'Den finns bara i MoE-modeller'], explanation: 'KV-cachen lagrar beräknade nyckel/värde-par för alla tidigare tokens.' }
quizSv['arch-4'] = { question: 'När bör du välja en MoE-arkitektur framför dense?', options: ['Alltid — MoE är strikt bättre', 'När du behöver hög kapacitet men har begränsad inferensberäkning, och kan hantera högre minneskrav', 'Bara för modeller under 7B', 'Bara för bildmodeller'], explanation: 'MoE ger mer kapacitet per FLOP men kräver mer minne.' }

quizKo['arch-1'] = { question: 'Dense 모델과 MoE 모델의 가장 중요한 차이점은?', options: ['Dense 모델이 항상 더 좋음', 'MoE는 토큰당 파라미터의 부분집합만 활성화하여 더 낮은 계산 비용으로 더 많은 용량 제공', 'MoE 모델이 더 작음', 'Dense 모델은 파인튜닝 불가'], explanation: 'MoE는 선택적 활성화입니다 — 같은 계산 예산으로 더 많은 총 용량.' }
quizKo['arch-2'] = { question: 'Chinchilla 스케일링 법칙은 무엇을 예측하나요?', options: ['더 큰 모델이 항상 더 좋음', '모델 크기와 학습 데이터 양 사이에 최적 비율이 존재', '학습은 항상 최소 일주일', '스케일링 법칙은 100B 이상 모델에 적용 안 됨'], explanation: 'Chinchilla는 많은 모델이 과소학습되었음을 보여주었습니다 — 더 많은 파라미터가 아닌 더 많은 데이터가 필요.' }
quizKo['arch-3'] = { question: '추론 시 KV 캐시가 병목인 이유는?', options: ['모델 로딩을 느리게 함', '시퀀스 길이에 따라 선형으로 증가하며 각 토큰의 키/값 벡터에 GPU 메모리 필요', '수치 불안정성 유발', 'MoE 모델에만 존재'], explanation: 'KV 캐시는 이전 모든 토큰의 계산된 키/값 쌍을 저장합니다.' }
quizKo['arch-4'] = { question: 'Dense 대신 MoE 아키텍처를 선택해야 할 때는?', options: ['항상 — MoE가 엄격히 더 좋음', '높은 용량이 필요하지만 추론 계산이 제한적이고 더 높은 메모리 요구를 감당할 수 있을 때', '7B 미만 모델에만', '이미지 모델에만'], explanation: 'MoE는 FLOP당 더 많은 용량을 제공하지만 더 많은 메모리가 필요합니다.' }

// Embeddings (technical)
quizSv['embeddings-1'] = { question: 'Förklara vad en embedding-vektor representerar.', modelAnswer: 'En embedding-vektor är en tät numerisk representation där varje dimension fångar någon inlärd semantisk egenskap. Liknande texter placeras nära varandra i detta högdimensionella rum.', options: undefined, explanation: 'Embeddings kodar betydelse som geometri.' }
quizSv['embeddings-2'] = { question: 'Vilken chunking-strategi passar bäst för juridiska kontrakt med korsreferenser?', options: ['Fast storlek 512 tokens utan överlapp', 'Meningsnivå', 'Semantisk chunking med överlapp som bevarar klausulgränser', 'En embedding per dokument'], explanation: 'Juridiska dokument har meningsfulla strukturella enheter som bör bevaras.' }
quizSv['embeddings-3'] = { question: 'Varför använder vektordatabaser ANN-algoritmer istället för exakt sökning?', options: ['ANN ger alltid bättre resultat', 'Exakt sökning är O(n) — ANN byter minimal noggrannhetsförlust mot storleksordningars hastighetsförbättring', 'Vektordatabaser kan inte lagra tillräckligt', 'ANN använder mindre lagring'], explanation: 'ANN möjliggör sub-linjär söktid med 95-99% av sanna närmaste grannar.' }
quizSv['embeddings-4'] = { question: 'Gå igenom hela RAG-pipelinen från fråga till svar.', modelAnswer: '(1) Query embedding — frågan konverteras till vektor. (2) Retrieval — vektorsökning hittar top-k chunks. (3) Reranking — korskodar ompoängsätter. (4) Kontextsammansättning — chunks formateras i prompten. (5) Generering — LLM producerar grundat svar.', options: undefined, explanation: 'RAG är en flerstegs-pipeline där varje steg kan introducera fel.' }
quizSv['embeddings-5'] = { question: 'Ett RAG-system hämtar relevanta chunks men LLM:en genererar ändå felaktiga svar. Vilken åtgärd hjälper troligast?', options: ['Öka embedding-dimensionerna', 'Lägg till fler dokument', 'Förbättra prompten för att instruera modellen att bara svara från given kontext', 'Byt till större chunk-storlek'], explanation: 'Om retrieval fungerar men generering är fel, är problemet i genereringssteget.' }

quizKo['embeddings-1'] = { question: '임베딩 벡터가 실제로 무엇을 나타내는지 설명하세요.', modelAnswer: '임베딩 벡터는 각 차원이 학습된 의미적 특성을 포착하는 밀집 수치 표현입니다. 의미적으로 유사한 텍스트는 이 고차원 공간에서 가까이 배치됩니다.', options: undefined, explanation: '임베딩은 의미를 기하학으로 인코딩합니다.' }
quizKo['embeddings-2'] = { question: '교차 참조가 있는 법률 계약서에 가장 적합한 청킹 전략은?', options: ['오버랩 없는 고정 512 토큰', '문장 수준', '조항 경계를 보존하는 오버랩 있는 시맨틱 청킹', '문서당 하나의 임베딩'], explanation: '법률 문서에는 보존해야 할 의미 있는 구조적 단위가 있습니다.' }
quizKo['embeddings-3'] = { question: '벡터 데이터베이스가 정확한 검색 대신 ANN 알고리즘을 사용하는 이유는?', options: ['ANN이 항상 더 나은 결과', '정확한 검색은 O(n) — ANN은 최소한의 정확도 손실로 수 배의 속도 향상', '벡터 DB가 충분히 저장 못함', 'ANN이 저장 공간을 덜 사용'], explanation: 'ANN은 진정한 최근접 이웃의 95-99%를 찾으면서 서브리니어 검색 시간을 가능하게 합니다.' }
quizKo['embeddings-4'] = { question: '사용자 질문부터 최종 답변까지 전체 RAG 파이프라인을 설명하세요.', modelAnswer: '(1) 쿼리 임베딩 — 질문을 벡터로 변환. (2) 검색 — 벡터 유사도 검색으로 top-k 청크 찾기. (3) 리랭킹 — 크로스 인코더로 재점수. (4) 컨텍스트 조립 — 청크를 프롬프트에 포맷. (5) 생성 — LLM이 근거 있는 답변 생성.', options: undefined, explanation: 'RAG는 각 단계에서 오류가 발생할 수 있는 다단계 파이프라인입니다.' }
quizKo['embeddings-5'] = { question: 'RAG 시스템이 관련 청크를 검색하지만 LLM이 여전히 잘못된 답변을 생성합니다. 어떤 조치가 가장 도움이 될까요?', options: ['임베딩 차원 증가', '더 많은 문서 추가', '제공된 컨텍스트에서만 답하도록 프롬프트 개선', '더 큰 청크 크기로 전환'], explanation: '검색이 작동하지만 생성이 틀리면 문제는 생성 단계에 있습니다.' }

// Evaluation (technical)
quizSv['eval-1'] = { question: 'En modell har perplexity 8.2 — lägre än alla konkurrenter. Varför kan den ändå vara ett dåligt val?', modelAnswer: 'Perplexity mäter hur väl modellen förutsäger nästa token, men säger inget om uppgiftsspecifik kvalitet. Låg perplexity garanterar inte bra instruktionsföljning, faktakorrekthet eller säkerhet.', options: undefined, explanation: 'Perplexity är ett språkmodelleringsmått, inte ett användbarhetsmått.' }
quizSv['eval-2'] = { question: 'Varför är benchmark-leaderboards ofta vilseledande?', options: ['Benchmarks är för enkla', 'Modeller kan vara tränade på benchmark-data, benchmarks kanske inte speglar din uppgift, och aggregerade poäng döljer svagheter', 'Leaderboards mäter bara hastighet', 'Benchmarks gäller bara för modeller under 13B'], explanation: 'Benchmark-kontaminering, uppgiftsmismatch och poängaggregering gör rankningar opålitliga.' }
quizSv['eval-3'] = { question: 'När är mänsklig utvärdering nödvändig?', options: ['När du behöver utvärdera fler än 1000 exempel', 'När automatiserade mätvärden finns', 'När du utvärderar subjektiva kvaliteter som hjälpsamhet och säkerhet', 'När modellen är mindre än 7B'], explanation: 'Subjektiva kvaliteter kräver mänskligt omdöme.' }
quizSv['eval-4'] = { question: 'Du bygger en anpassad eval för ett medicinskt Q&A-system. Vilka dimensioner?', modelAnswer: 'Faktanoggrannhet, säkerhet, källkvalitet, lämplig försiktighet ("kontakta läkare"), och fullständighet. MMLU testar allmän kunskap men kan inte utvärdera frisvarskvalitet eller säkerhetsbeteende.', options: undefined, explanation: 'Generiska benchmarks testar kunskapsbredd, inte domänspecifikt beteende.' }

quizKo['eval-1'] = { question: '모델의 perplexity가 8.2로 모든 경쟁자보다 낮습니다. 왜 여전히 나쁜 선택일 수 있나요?', modelAnswer: 'Perplexity는 모델이 다음 토큰을 얼마나 잘 예측하는지 측정하지만 작업별 품질에 대해서는 아무것도 말하지 않습니다. 낮은 perplexity가 좋은 지시 따르기, 사실 정확성, 안전성을 보장하지 않습니다.', options: undefined, explanation: 'Perplexity는 언어 모델링 지표이지 유용성 지표가 아닙니다.' }
quizKo['eval-2'] = { question: '벤치마크 리더보드가 종종 오해를 주는 이유는?', options: ['벤치마크가 너무 쉬움', '모델이 벤치마크 데이터로 학습되었을 수 있고, 벤치마크가 작업을 반영하지 않을 수 있으며, 집계 점수가 약점을 숨김', '리더보드는 속도만 측정', '벤치마크는 13B 미만 모델에만 유효'], explanation: '벤치마크 오염, 작업 불일치, 점수 집계가 순위를 신뢰할 수 없게 만듭니다.' }
quizKo['eval-3'] = { question: '인간 평가가 필수적인 경우는?', options: ['1000개 이상 예시 평가 시', '자동화된 지표가 있을 때', '도움이 됨, 안전성 같은 주관적 품질 평가 시', '모델이 7B 미만일 때'], explanation: '주관적 품질은 인간의 판단이 필요합니다.' }
quizKo['eval-4'] = { question: '의료 Q&A 시스템을 위한 커스텀 평가를 구축합니다. 어떤 차원을 평가하나요?', modelAnswer: '사실 정확성, 안전성, 인용 품질, 적절한 주의("의사와 상담하세요"), 완전성. MMLU는 일반 지식을 테스트하지만 자유 형식 답변 품질이나 안전 행동을 평가할 수 없습니다.', options: undefined, explanation: '일반 벤치마크는 지식 폭을 테스트하지 도메인별 행동은 아닙니다.' }

// Solution (technical)
quizSv['sol-1'] = { question: 'Ert företag har 50 000 policydokument som ändras varje månad. Användare behöver svar med källhänvisningar. Vilken metod?', options: ['Finjustera kvartalsvis', 'RAG med vektorlagring som omindexerar vid uppdateringar', 'Few-shot prompting', 'Träna en egen modell'], explanation: 'RAG är idealiskt: dokument ändras ofta, användare behöver källhänvisningar.' }
quizSv['sol-2'] = { question: 'Gå igenom RAG-pipelinens steg och var saker kan gå fel.', modelAnswer: '1) Query embedding — kan misslyckas om frågan använder annat ordförråd. 2) Retrieval — kan misslyckas med fel chunk-storlek. 3) Kontextinjektion — kan misslyckas om för många chunks. 4) Generering — kan hallucinera bortom kontexten.', options: undefined, explanation: 'Varje RAG-steg är en potentiell felpunkt.' }
quizSv['sol-3'] = { question: 'När är finjustering tydligt bättre än RAG?', options: ['När du behöver källhänvisningar', 'När data ändras dagligen', 'När du behöver konsekvent ton, format eller domänvokabulär', 'När du har färre än 100 exempel'], explanation: 'Finjustering bakar in beteende i modellvikterna.' }
quizSv['sol-4'] = { question: 'En startup väljer mellan $0.01/1K token API och självhosting på $2K/månad GPU. Vid vilken användning går självhosting jämnt?', modelAnswer: 'Break-even: $2000 / $0.01 per 1K tokens = 200M tokens/månad. Under det är API billigare. Icke-kostnadsfaktorer: latens, dataintegritet, anpassning, tillförlitlighet.', options: undefined, explanation: 'Kostnad är bara en dimension.' }

quizKo['sol-1'] = { question: '회사에 매월 변경되는 50,000개의 정책 문서가 있습니다. 사용자는 인용이 있는 답변이 필요합니다. 어떤 접근 방식?', options: ['분기별 파인튜닝', '문서 업데이트 시 재인덱싱하는 벡터 스토어와 RAG', 'Few-shot 프롬프팅', '처음부터 맞춤 모델 학습'], explanation: 'RAG가 이상적입니다: 문서가 자주 변경되고 사용자는 인용이 필요합니다.' }
quizKo['sol-2'] = { question: 'RAG 파이프라인의 단계와 문제가 발생할 수 있는 곳을 설명하세요.', modelAnswer: '1) 쿼리 임베딩 — 질문이 다른 어휘를 사용하면 실패 가능. 2) 검색 — 청크 크기가 잘못되면 실패. 3) 컨텍스트 주입 — 청크가 너무 많으면 실패. 4) 생성 — 컨텍스트를 넘어 환각 가능.', options: undefined, explanation: '각 RAG 단계는 잠재적 실패 지점입니다.' }
quizKo['sol-3'] = { question: '파인튜닝이 RAG보다 확실히 나은 경우는?', options: ['출처 인용이 필요할 때', '데이터가 매일 변경될 때', '일관된 톤, 형식, 도메인 어휘가 필요할 때', '100개 미만의 예시가 있을 때'], explanation: '파인튜닝은 행동을 모델 가중치에 내장합니다.' }
quizKo['sol-4'] = { question: '스타트업이 $0.01/1K 토큰 API와 $2K/월 GPU 셀프 호스팅 중 선택합니다. 어느 사용량에서 셀프 호스팅이 손익분기?', modelAnswer: '손익분기: $2000 / $0.01 per 1K 토큰 = 월 2억 토큰. 그 이하면 API가 저렴. 비용 외 요소: 지연시간, 데이터 프라이버시, 커스터마이징, 신뢰성.', options: undefined, explanation: '비용은 하나의 차원일 뿐입니다.' }

// Industry (technical)
quizSv['industry-1'] = { question: 'En startup behöver bygga en medicinsk chattbot som behandlar patientdata. De vill ha maximal kontroll. Vilken metod?', options: ['GPT-4o API', 'Finjustera en öppen modell som Llama och självhosta', 'Claude API med BAA', 'Vänta på en medicinsk modell'], explanation: 'Öppna modeller ger full finjusteringskontroll för medicinsk domänanpassning.' }
quizSv['industry-2'] = { question: 'Förklara varför gapet mellan öppna och stängda modeller har minskat.', modelAnswer: 'Arkitekturinnovationer (MoE) blev offentliga, ekosystemet (HuggingFace, vLLM) sänkte barriärerna, distillation från frontiermodeller gav syntetisk träningsdata, och kvantiseringsframsteg (GGUF, AWQ) möjliggjorde stora modeller på konsumenthårdvara.', options: undefined, explanation: 'Konvergensen drivs av tekniska framsteg och strategiska beslut att öppna vikter.' }
quizSv['industry-3'] = { question: 'Varför släpper Meta modellvikter gratis?', options: ['Lagkrav', 'Öppna vikter skapar ett ekosystem — utvecklare bygger på deras plattform', 'De kan inte tjäna pengar via API:er', 'Öppna modeller är alltid bättre'], explanation: 'Metas strategi är ekosystemdriven, likt Googles med Android.' }

quizKo['industry-1'] = { question: '스타트업이 환자 데이터를 처리하는 의료 챗봇을 구축해야 합니다. 최대한의 통제를 원합니다. 어떤 접근 방식?', options: ['GPT-4o API', 'Llama 같은 오픈 모델을 파인튜닝하고 셀프 호스팅', 'BAA가 있는 Claude API', '의료 전용 클로즈드 모델 대기'], explanation: '오픈 모델은 의료 도메인 적응을 위한 완전한 파인튜닝 제어를 제공합니다.' }
quizKo['industry-2'] = { question: '오픈과 클로즈드 모델 간의 격차가 줄어든 이유를 설명하세요.', modelAnswer: '아키텍처 혁신(MoE)이 공개되고, 생태계(HuggingFace, vLLM)가 장벽을 낮추고, 프론티어 모델에서의 증류가 합성 학습 데이터를 제공하고, 양자화 발전(GGUF, AWQ)이 소비자 하드웨어에서 대형 모델을 가능하게 했습니다.', options: undefined, explanation: '수렴은 기술적 발전과 가중치를 공개하는 전략적 결정에 의해 주도됩니다.' }
quizKo['industry-3'] = { question: 'Meta가 모델 가중치를 무료로 공개하는 이유는?', options: ['법적 요구', '오픈 가중치가 생태계를 만듦 — 개발자가 플랫폼 위에 구축', 'API로 수익화 불가', '오픈소스 모델이 항상 더 좋음'], explanation: 'Meta의 전략은 Google의 Android처럼 생태계 중심입니다.' }

// Prompting (technical)
quizSv['prompting-1'] = { question: 'Du behöver klassificera kundmejl i 5 kategorier utan märkta exempel. Vilken teknik först?', options: ['Few-shot med påhittade exempel', 'Zero-shot med tydliga kategoridefinitioner', 'Chain-of-thought', 'Finjustering på syntetisk data'], explanation: 'Zero-shot med väldefinierade kategorier ger modellen beslutsgränser.' }
quizSv['prompting-2'] = { question: 'Förklara syftet med en systemprompt.', modelAnswer: 'Systempromten sätter persistent beteende, roll och begränsningar som gäller över alla samtalsrundor. Den separerar "hur man beter sig" från "vad man ska göra just nu."', options: undefined, explanation: 'Systemprompts skapar en persistent beteenderam.' }
quizSv['prompting-3'] = { question: 'Varför förbättrar chain-of-thought-prompting noggrannheten på matte- och resonemangsuppgifter?', options: ['Det gör att modellen använder mer beräkning', 'Det tvingar modellen att bryta ner problem i steg, vilket gör varje steg enklare', 'Det aktiverar speciella resonemangskretsar', 'Det minskar hallucination'], explanation: 'CoT dekomponerar svåra problem till enklare delproblem.' }
quizSv['prompting-4'] = { question: 'Du behöver giltig JSON från en LLM. Modellen lägger ibland till markdown. Pålitligaste lösningen?', options: ['Lägg till "Ge bara JSON" i prompten', 'Använd regex för att extrahera', 'Använd API:ets structured output / JSON-läge med schemadefinition', 'Sänk temperature till 0'], explanation: 'Structured output-lägen ger en hård garanti för giltig JSON.' }

quizKo['prompting-1'] = { question: '레이블된 예시 없이 고객 이메일을 5개 카테고리로 분류해야 합니다. 어떤 기법을 먼저?', options: ['만든 예시로 few-shot', '명확한 카테고리 정의로 zero-shot', 'Chain-of-thought', '합성 데이터로 파인튜닝'], explanation: '잘 정의된 카테고리로 zero-shot이 모델에 결정 경계를 제공합니다.' }
quizKo['prompting-2'] = { question: '시스템 프롬프트의 목적을 설명하세요.', modelAnswer: '시스템 프롬프트는 모든 대화 턴에 걸쳐 적용되는 지속적인 행동, 역할, 제약을 설정합니다. "어떻게 행동할지"와 "지금 무엇을 할지"를 분리합니다.', options: undefined, explanation: '시스템 프롬프트는 지속적인 행동 프레임을 만듭니다.' }
quizKo['prompting-3'] = { question: 'Chain-of-thought 프롬프팅이 수학과 추론 작업의 정확도를 향상시키는 이유는?', options: ['모델이 더 많은 계산을 사용하게 함', '문제를 단계로 분해하도록 강제하여 각 단계를 더 쉽게 만듦', '특별한 추론 회로를 활성화', '환각을 줄임'], explanation: 'CoT는 어려운 문제를 더 쉬운 하위 문제로 분해합니다.' }
quizKo['prompting-4'] = { question: 'LLM에서 유효한 JSON이 필요합니다. 모델이 때때로 마크다운을 추가합니다. 가장 신뢰할 수 있는 해결책은?', options: ['프롬프트에 "JSON만 출력" 추가', 'regex로 JSON 추출', 'API의 structured output / JSON 모드를 스키마 정의와 함께 사용', 'temperature를 0으로 낮춤'], explanation: 'Structured output 모드는 유효한 JSON에 대한 하드 보장을 제공합니다.' }

// LLM Data
quizSv['llmdata-1'] = { question: 'Varför är datadeduplicering kritisk för LLM-träning?', options: ['Det sparar lagringsutrymme', 'Duplicerad data gör att modellen memorerar istället för att generalisera', 'Det snabbar upp träningen', 'Det krävs av lag'], explanation: 'Duplicering leder till memorering och sämre generalisering.' }
quizSv['llmdata-2'] = { question: 'Vad är syftet med kvalitetsfiltrering i en datapipeline?', options: ['Ta bort alla icke-engelska texter', 'Filtrera bort SEO-spam, boilerplate och lågkvalitetsinnehåll', 'Konvertera all data till JSON', 'Komprimera data'], explanation: 'Kvalitetsfiltrering tar bort innehåll som skulle försämra modellens output.' }
quizSv['llmdata-3'] = { question: 'Hur påverkar datamixen vad modellen blir bra på?', options: ['Den påverkar inte — modellen lär sig allt lika bra', 'Mer kod → bättre på kodning, mer vetenskap → bättre på resonemang', 'Bara den totala mängden spelar roll', 'Mixen bestäms automatiskt'], explanation: 'Datamixen formar direkt modellens styrkor och svagheter.' }
quizSv['llmdata-4'] = { question: 'Vad är syntetisk data och varför används den?', options: ['Slumpmässigt genererad data', 'Data genererad av AI-modeller för att komplettera mänsklig data — billigare och skalbar', 'Data från sensorer', 'Krypterad data'], explanation: 'Syntetisk data från starka modeller kan komplettera mänsklig data till lägre kostnad.' }

quizKo['llmdata-1'] = { question: 'LLM 학습에서 데이터 중복 제거가 중요한 이유는?', options: ['저장 공간 절약', '중복 데이터는 모델이 일반화 대신 암기하게 만듦', '학습 속도 향상', '법적 요구'], explanation: '중복은 암기와 나쁜 일반화로 이어집니다.' }
quizKo['llmdata-2'] = { question: '데이터 파이프라인에서 품질 필터링의 목적은?', options: ['모든 비영어 텍스트 제거', 'SEO 스팸, 보일러플레이트, 저품질 콘텐츠 필터링', '모든 데이터를 JSON으로 변환', '데이터 압축'], explanation: '품질 필터링은 모델 출력을 저하시킬 콘텐츠를 제거합니다.' }
quizKo['llmdata-3'] = { question: '데이터 믹스가 모델의 능력에 어떤 영향을 미치나요?', options: ['영향 없음 — 모델이 모든 것을 동등하게 학습', '더 많은 코드 → 코딩 향상, 더 많은 과학 → 추론 향상', '총량만 중요', '믹스는 자동 결정'], explanation: '데이터 믹스가 모델의 강점과 약점을 직접 형성합니다.' }
quizKo['llmdata-4'] = { question: '합성 데이터란 무엇이고 왜 사용하나요?', options: ['랜덤 생성 데이터', 'AI 모델이 생성한 데이터로 인간 데이터를 보완 — 더 저렴하고 확장 가능', '센서 데이터', '암호화된 데이터'], explanation: '강력한 모델의 합성 데이터가 더 낮은 비용으로 인간 데이터를 보완할 수 있습니다.' }

// Quantization
quizSv['quant-1'] = { question: 'Vad är kvantisering i kontexten av LLM:er?', options: ['Att göra modellen snabbare', 'Att minska precisionen på modellvikter för att spara minne och öka hastigheten', 'Att lägga till fler parametrar', 'Att komprimera träningsdata'], explanation: 'Kvantisering minskar bitbredden på vikter.' }
quizSv['quant-2'] = { question: 'Varför är 4-bit kvantisering populärare än 2-bit?', options: ['4-bit är snabbare', 'Vid 4 bit är kvalitetsförlusten minimal (<1%), vid 2 bit börjar modellen förlora viktig information', '2-bit stöds inte av hårdvara', '4-bit är nyare'], explanation: '4-bit är sweet spot mellan minnesbesparingar och kvalitetsbevarande.' }
quizSv['quant-3'] = { question: 'Vad är skillnaden mellan GPTQ och GGUF?', options: ['GPTQ är nyare', 'GPTQ är GPU-optimerat med kalibrering, GGUF är CPU-vänligt format för llama.cpp', 'De är identiska', 'GGUF fungerar bara på Mac'], explanation: 'GPTQ och GGUF riktar sig mot olika hårdvarumål.' }
quizSv['quant-4'] = { question: 'Varför behöver vissa kvantiseringsmetoder kalibreringsdata?', options: ['För att träna modellen', 'För att mäta vilka vikter som är viktigast och kvantisera dem mer försiktigt', 'För att validera modellen', 'Det är ett lagkrav'], explanation: 'Kalibreringsdata hjälper metoden förstå vikternas distributioner.' }

quizKo['quant-1'] = { question: 'LLM 맥락에서 양자화란?', options: ['모델을 더 빠르게 만들기', '메모리 절약과 속도 향상을 위해 모델 가중치의 정밀도를 줄이기', '더 많은 파라미터 추가', '학습 데이터 압축'], explanation: '양자화는 가중치의 비트 폭을 줄입니다.' }
quizKo['quant-2'] = { question: '4비트 양자화가 2비트보다 인기 있는 이유는?', options: ['4비트가 더 빠름', '4비트에서 품질 손실이 최소(<1%), 2비트에서는 모델이 중요한 정보를 잃기 시작', '2비트는 하드웨어 미지원', '4비트가 더 새로움'], explanation: '4비트는 메모리 절약과 품질 보존 사이의 최적점입니다.' }
quizKo['quant-3'] = { question: 'GPTQ와 GGUF의 차이점은?', options: ['GPTQ가 더 새로움', 'GPTQ는 캘리브레이션이 있는 GPU 최적화, GGUF는 llama.cpp용 CPU 친화적 포맷', '동일함', 'GGUF는 Mac에서만 작동'], explanation: 'GPTQ와 GGUF는 다른 하드웨어 대상을 겨냥합니다.' }
quizKo['quant-4'] = { question: '일부 양자화 방법에 캘리브레이션 데이터가 필요한 이유는?', options: ['모델 학습용', '어떤 가중치가 가장 중요한지 측정하여 더 신중하게 양자화', '모델 검증용', '법적 요구'], explanation: '캘리브레이션 데이터가 방법이 가중치 분포를 이해하도록 돕습니다.' }

// Inference
quizSv['inf-1'] = { question: 'Varför genererar LLM:er text en token i taget istället för hela svaret på en gång?', options: ['Det är en designbegränsning', 'Autoregressive modeller förutsäger nästa token baserat på alla tidigare — varje token beror på de föregående', 'Det sparar minne', 'Det är snabbare'], explanation: 'Autoregressive generering är grundläggande för hur transformerbaserade LLM:er fungerar.' }
quizSv['inf-2'] = { question: 'Vad är KV-cachen och varför är den viktig?', options: ['En databas för att lagra svar', 'Den lagrar beräknade nyckel/värde-vektorer från tidigare tokens för att undvika omberäkning', 'En typ av kvantisering', 'En optimeringsflagga'], explanation: 'KV-cachen undviker att beräkna om attention för alla tidigare tokens vid varje steg.' }
quizSv['inf-3'] = { question: 'Vad är continuous batching och varför förbättrar det throughput?', options: ['Det kör flera modeller parallellt', 'Det lägger till nya förfrågningar i batchen så fort platser frigörs, istället för att vänta tills hela batchen är klar', 'Det komprimerar indata', 'Det använder flera GPU:er'], explanation: 'Continuous batching maximerar GPU-utnyttjandet.' }
quizSv['inf-4'] = { question: 'Varför är speculative decoding snabbare trots att den genererar fler tokens?', options: ['Den använder en snabbare GPU', 'En liten modell genererar kandidat-tokens snabbt, den stora modellen verifierar dem parallellt — verifiering är billigare än generering', 'Den hoppar över attention', 'Den använder mindre precision'], explanation: 'Verifiering av N tokens kostar ungefär lika mycket som att generera 1 token.' }

quizKo['inf-1'] = { question: 'LLM이 전체 답변을 한 번에 생성하지 않고 한 번에 하나의 토큰을 생성하는 이유는?', options: ['설계 제한', '자기회귀 모델은 이전 모든 토큰을 기반으로 다음 토큰을 예측 — 각 토큰이 이전 것에 의존', '메모리 절약', '더 빠름'], explanation: '자기회귀 생성은 트랜스포머 기반 LLM의 근본적인 작동 방식입니다.' }
quizKo['inf-2'] = { question: 'KV 캐시란 무엇이고 왜 중요한가요?', options: ['답변 저장 데이터베이스', '재계산을 피하기 위해 이전 토큰의 계산된 키/값 벡터를 저장', '양자화의 한 유형', '최적화 플래그'], explanation: 'KV 캐시는 각 단계에서 모든 이전 토큰에 대한 어텐션 재계산을 방지합니다.' }
quizKo['inf-3'] = { question: 'Continuous batching이란 무엇이고 왜 처리량을 향상시키나요?', options: ['여러 모델을 병렬 실행', '전체 배치가 완료될 때까지 기다리지 않고 자리가 비면 새 요청을 추가', '입력 데이터 압축', '여러 GPU 사용'], explanation: 'Continuous batching은 GPU 활용률을 최대화합니다.' }
quizKo['inf-4'] = { question: 'Speculative decoding이 더 많은 토큰을 생성하면서도 더 빠른 이유는?', options: ['더 빠른 GPU 사용', '작은 모델이 후보 토큰을 빠르게 생성하고 큰 모델이 병렬로 검증 — 검증이 생성보다 저렴', '어텐션 건너뜀', '더 낮은 정밀도 사용'], explanation: 'N개 토큰 검증 비용은 1개 토큰 생성 비용과 거의 같습니다.' }

// Fine-tuning (technical)
quizSv['finetuning-1'] = { question: 'Vad är LoRA och varför är det effektivare än full finjustering?', options: ['LoRA är en ny modellarkitektur', 'LoRA fryser basmodellen och tränar bara små adapter-matriser — typiskt <0.1% av parametrarna', 'LoRA använder mer data', 'LoRA är bara för små modeller'], explanation: 'LoRA minskar drastiskt minnes- och beräkningskraven.' }
quizSv['finetuning-2'] = { question: 'Varför är datakvalitet viktigare än datakvantitet vid finjustering?', options: ['Mer data är alltid bättre', 'Finjustering med få högkvalitativa exempel överträffar ofta många lågkvalitativa — modellen lär sig mönster, inte fakta', 'Datakvalitet spelar ingen roll', 'Kvantitet bestämmer modellstorlek'], explanation: 'Kvalitet trumfar kvantitet vid finjustering.' }
quizSv['finetuning-3'] = { question: 'Vad händer när du slår samman en LoRA-adapter med basmodellen?', options: ['Modellen blir större', 'Adaptervikterna adderas till basmodellens vikter permanent — ingen adapter behövs vid inferens', 'Modellen förlorar sina förmågor', 'Det krävs omträning'], explanation: 'Sammanslagning eliminerar adapter-overhead vid inferens.' }
quizSv['finetuning-4'] = { question: 'När bör du använda DPO istället för SFT?', options: ['Alltid — DPO är strikt bättre', 'När du har preferensdata (valt/avvisat par) och vill lära modellen att föredra vissa svar framför andra', 'Bara för kodmodeller', 'DPO kräver mindre data'], explanation: 'DPO optimerar direkt för preferenser, medan SFT bara imiterar exempel.' }

quizKo['finetuning-1'] = { question: 'LoRA란 무엇이고 왜 전체 파인튜닝보다 효율적인가요?', options: ['LoRA는 새로운 모델 아키텍처', 'LoRA는 기본 모델을 동결하고 작은 어댑터 행렬만 학습 — 일반적으로 파라미터의 <0.1%', 'LoRA가 더 많은 데이터 사용', 'LoRA는 작은 모델에만'], explanation: 'LoRA는 메모리와 계산 요구사항을 크게 줄입니다.' }
quizKo['finetuning-2'] = { question: '파인튜닝에서 데이터 품질이 양보다 중요한 이유는?', options: ['더 많은 데이터가 항상 더 좋음', '소수의 고품질 예시로 파인튜닝이 많은 저품질보다 종종 우수 — 모델은 사실이 아닌 패턴을 학습', '데이터 품질은 중요하지 않음', '양이 모델 크기를 결정'], explanation: '파인튜닝에서 품질이 양을 이깁니다.' }
quizKo['finetuning-3'] = { question: 'LoRA 어댑터를 기본 모델과 병합하면 어떻게 되나요?', options: ['모델이 더 커짐', '어댑터 가중치가 기본 모델 가중치에 영구적으로 추가 — 추론 시 어댑터 불필요', '모델이 능력을 잃음', '재학습 필요'], explanation: '병합은 추론 시 어댑터 오버헤드를 제거합니다.' }
quizKo['finetuning-4'] = { question: 'SFT 대신 DPO를 사용해야 할 때는?', options: ['항상 — DPO가 엄격히 더 좋음', '선호도 데이터(선택/거부 쌍)가 있고 모델이 특정 응답을 선호하도록 학습시키고 싶을 때', '코드 모델에만', 'DPO가 더 적은 데이터 필요'], explanation: 'DPO는 선호도를 직접 최적화하고, SFT는 예시만 모방합니다.' }

// Agents (technical)
quizSv['agents-1'] = { question: 'Beskriv de tre stegen i en ReAct-loop och varför Observation-steget är kritiskt.', modelAnswer: 'De tre stegen: (1) Thought — LLM:en resonerar om vad som ska göras. (2) Action — agenten anropar ett verktyg. (3) Observation — agenten läser resultatet. Utan Observation skulle agenten vara "blind" — den kan inte anpassa sin plan eller veta när uppgiften är klar.', options: undefined, explanation: 'Observation-steget stänger feedbackloopen.' }
quizSv['agents-2'] = { question: 'Vad är den viktigaste skillnaden mellan MCP och A2A?', options: ['MCP är nyare', 'MCP kopplar agenter till verktyg/resurser; A2A kopplar agenter till andra agenter', 'A2A ersätter MCP', 'MCP fungerar bara med Anthropic-modeller'], explanation: 'MCP och A2A är kompletterande lager.' }
quizSv['agents-3'] = { question: 'Vad skiljer en AgentCore Skill från en rå MCP-server?', options: ['Skills är snabbare', 'Skills buntar MCP-verktyg med arbetsflödesinstruktioner och domänlogik', 'Skills använder inte MCP', 'Skills är bara för kodassistenter'], explanation: 'En Skill kodar tribal knowledge till repeterbart agentbeteende.' }
quizSv['agents-4'] = { question: 'Du driftsätter en supportagent på L2-autonomi. "Goal drift" uppstår: agenten stänger ärenden i förtid. Hur upptäcker och förhindrar du detta?', modelAnswer: 'Upptäckt: Övervaka utfallsmått (CSAT, återöppningsfrekvens), inte bara genomströmning. Prevention: Definiera "löst" som "kund bekräftar" inte "status ändrad." Kräv bekräftelsesteg. Veckovis beteendegranskning.', options: undefined, explanation: 'Goal drift är ett alignment-problem på agentnivå.' }
quizSv['agents-5'] = { question: 'En agent sitter fast i en loop. Vilket designmönster förhindrar detta?', options: ['Ge agenten fler verktyg', 'Öka kontextfönstret', 'Lägg till en maximal iterationsgräns med reservstrategi', 'Byt till en större modell'], explanation: 'En maximal iterationsgräns är en grundläggande säkerhetsmekanism.' }

quizKo['agents-1'] = { question: 'ReAct 루프의 세 단계를 설명하고 Observation 단계가 중요한 이유를 설명하세요.', modelAnswer: '세 단계: (1) Thought — LLM이 무엇을 할지 추론. (2) Action — 에이전트가 도구 호출. (3) Observation — 에이전트가 결과를 읽음. Observation 없이 에이전트는 "눈이 먼" 상태 — 계획을 조정하거나 작업 완료를 알 수 없습니다.', options: undefined, explanation: 'Observation 단계가 피드백 루프를 닫습니다.' }
quizKo['agents-2'] = { question: 'MCP와 A2A의 핵심 차이점은?', options: ['MCP가 더 새로움', 'MCP는 에이전트를 도구/리소스에 연결; A2A는 에이전트를 다른 에이전트에 연결', 'A2A가 MCP를 대체', 'MCP는 Anthropic 모델에서만 작동'], explanation: 'MCP와 A2A는 상호 보완적인 레이어입니다.' }
quizKo['agents-3'] = { question: 'AgentCore Skill이 원시 MCP 서버와 다른 점은?', options: ['스킬이 더 빠름', '스킬은 MCP 도구를 워크플로우 지시와 도메인 로직과 번들', '스킬은 MCP를 사용하지 않음', '스킬은 코딩 어시스턴트에만'], explanation: '스킬은 부족 지식을 반복 가능한 에이전트 행동으로 인코딩합니다.' }
quizKo['agents-4'] = { question: 'L2 자율성에서 지원 에이전트를 배포합니다. "목표 드리프트"가 발생: 에이전트가 티켓을 조기에 닫습니다. 어떻게 감지하고 방지하나요?', modelAnswer: '감지: 처리량이 아닌 결과 지표(CSAT, 재오픈율) 모니터링. 방지: "해결됨"을 "상태 변경"이 아닌 "고객 확인"으로 정의. 확인 단계 요구. 주간 행동 감사.', options: undefined, explanation: '목표 드리프트는 에이전트 수준의 정렬 문제입니다.' }
quizKo['agents-5'] = { question: '에이전트가 루프에 갇혔습니다. 어떤 디자인 패턴이 이를 방지하나요?', options: ['에이전트에 더 많은 도구 제공', '컨텍스트 윈도우 증가', '폴백 전략과 함께 최대 반복 제한 추가', '더 큰 모델로 전환'], explanation: '최대 반복 제한은 기본적인 안전 메커니즘입니다.' }

// Tools Landscape (Use AI course)
quizSv['toolsland-1'] = { question: 'Du behöver byta namn på en konfigurationsnyckel som förekommer i ~40 filer i ett repo, och uppdatera tester längs vägen. Vilket verktyg passar bäst, och varför?', options: ['En chattassistent — klistra in varje fil och applicera ändringarna den föreslår', 'En IDE-assistent — acceptera inline-förslag fil för fil', 'Ett agentiskt kodverktyg — det kan söka i repot, redigera alla filer och köra testerna självt', 'Ingen AI — flerfilsändringar är för riskabla för AI'], explanation: 'Detta är den typiska agentiska koduppgiften: flerfilig, mekanisk och verifierbar med tester. En chattassistent kan inte se repot, en IDE-assistent arbetar en fil i taget. Testsviten är skyddsnätet som gör agentautonomi säker här.' }
quizSv['toolsland-2'] = { question: 'Beskriv den agentiska loopen (cykeln ett agentiskt verktyg kör för varje uppgift) och förklara varför verifieringssteget förändrar hur mycket du säkert kan delegera.', modelAnswer: 'Loopen är: förstå uppgiften → planera → agera (redigera filer, köra kommandon) → verifiera (köra tester, kontrollera resultat) → upprepa eller rapportera. Verifiering är det som gör delegering säker: om agenten bevisar sitt arbete med passerande tester eller kontrollerbara källor kan du granska resultat i stället för att övervaka varje steg. Utan verifiering måste du kontrollera allt manuellt, vilket raderar tidsvinsten.', options: undefined, explanation: 'Verifieringssteget är skillnaden mellan "AI som genererar trovärdig output" och "en agent vars arbete du kan lita på vid kontrollpunkter."' }
quizSv['toolsland-biz-1'] = { question: 'Ert operationsteam sammanställer manuellt en veckorapport från fem kalkylblad och en mapp med mejl. Vilken AI-verktygskategori passar bäst?', options: ['En chattassistent — klistra in kalkylbladen i chatten varje vecka', 'En agentisk arbetsapp — delegera hela sammanställningen och granska utkastet', 'En kodagent som Claude Code', 'Ingen — återkommande rapporter måste göras för hand för noggrannhet'], explanation: 'Återkommande, flera källor, väldefinierat resultat är exakt vad agentiska arbetsappar är till för. Agenten arbetar direkt med filerna och en människa granskar utkastet. Noggrannheten kommer från granskningskontrollpunkten, inte från handarbete.' }
quizSv['toolsland-biz-2'] = { question: 'Vilket är det viktigaste kompetensskiftet för ett team som börjar delegera arbete till agentiska AI-verktyg?', options: ['Lära sig koda', 'Skriva prompts snabbare', 'Skriva tydliga briefer och granska arbete vid kontrollpunkter — leda, inte göra', 'Memorera varje verktygs menyalternativ'], explanation: 'Agentiska verktyg förvandlar utförare till delegerare. Briefens kvalitet avgör resultatets kvalitet, och kontrollpunktsgranskning är där fel fångas billigt. Detta är ledarskapsfärdigheter, tillämpade på AI.' }

quizKo['toolsland-1'] = { question: '저장소의 ~40개 파일에 나타나는 설정 키 이름을 바꾸고 테스트도 함께 업데이트해야 합니다. 어떤 도구가 가장 적합하며, 왜인가요?', options: ['챗 어시스턴트 — 각 파일을 붙여넣고 제안된 수정을 적용', 'IDE 어시스턴트 — 파일별로 인라인 제안 수락', '에이전틱 코딩 도구 — 저장소를 검색하고, 모든 파일을 수정하고, 테스트를 직접 실행 가능', 'AI 없이 — 여러 파일 변경은 AI에게 너무 위험'], explanation: '이것은 전형적인 에이전틱 코딩 작업입니다: 여러 파일, 기계적, 테스트로 검증 가능. 챗 어시스턴트는 저장소를 볼 수 없고 IDE 어시스턴트는 한 번에 한 파일만 작업합니다. 테스트 스위트가 에이전트 자율성을 안전하게 만드는 안전망입니다.' }
quizKo['toolsland-2'] = { question: '에이전틱 루프(에이전틱 도구가 각 작업마다 실행하는 사이클)를 설명하고, 검증 단계가 안전하게 위임할 수 있는 양을 어떻게 바꾸는지 설명하세요.', modelAnswer: '루프: 작업 이해 → 계획 → 행동(파일 수정, 명령 실행) → 검증(테스트 실행, 출력 확인) → 반복 또는 보고. 검증이 위임을 안전하게 만듭니다: 에이전트가 통과하는 테스트나 확인 가능한 출처로 작업을 증명하면 모든 단계를 감독하는 대신 결과만 검토할 수 있습니다. 검증이 없으면 모든 것을 수동으로 재확인해야 하므로 절약한 시간이 사라집니다.', options: undefined, explanation: '검증 단계는 "그럴듯한 출력을 생성하는 AI"와 "체크포인트에서 신뢰할 수 있는 에이전트"의 차이입니다.' }
quizKo['toolsland-biz-1'] = { question: '운영팀이 스프레드시트 5개와 이메일 폴더에서 주간 보고서를 수동으로 만듭니다. 어떤 AI 도구 카테고리가 가장 적합한가요?', options: ['챗 어시스턴트 — 매주 스프레드시트를 채팅에 붙여넣기', '에이전틱 업무 앱 — 조립 전체를 위임하고 초안 검토', 'Claude Code 같은 코딩 에이전트', '없음 — 반복 보고서는 정확성을 위해 수작업 필수'], explanation: '반복적이고, 출처가 여럿이고, 결과물이 명확한 작업은 에이전틱 업무 앱의 전형입니다. 에이전트가 파일을 직접 다루고 사람이 초안을 검토합니다. 정확성은 수작업이 아니라 검토 체크포인트에서 나옵니다.' }
quizKo['toolsland-biz-2'] = { question: '에이전틱 AI 도구에 업무를 위임하기 시작하는 팀에게 가장 중요한 역량 전환은?', options: ['코딩 배우기', '프롬프트 빨리 입력하기', '명확한 브리프 작성과 체크포인트 검토 — 직접 하기가 아닌 관리하기', '각 도구의 메뉴 옵션 외우기'], explanation: '에이전틱 도구는 실행자를 위임자로 바꿉니다. 브리프의 질(결과물, 형식, 제약)이 출력의 질을 결정하고, 체크포인트 검토에서 오류를 저렴하게 잡습니다. 이것은 AI에 적용된 관리 기술입니다.' }

// Working With AI (Use AI course)
quizSv['workai-1'] = { question: 'En chatt med 100 meddelanden som har täckt tre olika uppgifter börjar ge röriga, missriktade svar. Vad är den mest effektiva åtgärden?', options: ['Be modellen anstränga sig mer och vara uppmärksam', 'Starta en ny chatt för den aktuella uppgiften och ta med en kort sammanfattning av det som spelar roll', 'Byt till en annan AI-leverantör', 'Upprepa din senaste fråga i versaler'], explanation: 'Modellen läser om hela tråden varje tur — en vandrande tråd betyder utspädd, motstridig kontext. En ny chatt med en stram sammanfattning ger den exakt vad den aktuella uppgiften behöver och inget annat. "Ny uppgift, ny chatt" är den billigaste kvalitetsuppgraderingen.' }
quizSv['workai-2'] = { question: 'Beskriv iterationsloopen för att arbeta med en chattassistent, och förklara varför ett medelmåttigt första resultat är användbart snarare än ett misslyckande.', modelAnswer: 'Loopen: prompt → läs resultatet som en diagnos → identifiera vilken kontext som saknades (exempeldata, begränsningar, format, den verkliga regeln) → ge den i en förfinad prompt → upprepa. Ett medelmåttigt första resultat är användbart eftersom gapet mellan vad du fick och vad du ville ha är exakt listan över kontext du missade att ge — det talar om vad du ska lägga till. Två informerade turer slår tio vaga.', options: undefined, explanation: 'Att behandla resultat som diagnoser förvandlar besvikelse till information. Färdigheten är att läsa gapet, inte att skriva en perfekt megaprompt.' }
quizSv['workai-biz-1'] = { question: 'Ditt AI-utkast till ett kundmejl blev generiskt och kändes inte som ert varumärke. Vad gick troligast fel?', options: ['AI:n är inte bra på mejl', 'Briefen var generisk — ingen kontext om ditt företag, din målgrupp eller ton, så modellen fyllde luckorna med genomsnitt', 'Du behöver en betalplan för bättre skrivande', 'Mejl bör inte delegeras till AI'], explanation: 'Generiskt in, generiskt ut. Modellen fyller varje ospecificerad lucka med det statistiska genomsnittet. En mening vardera av kontext, uppgift, format och målgrupp förvandlar samma modell till något som låter som du.' }
quizSv['workai-biz-2'] = { question: 'Du märker att du skriver "Jag ansvarar för customer success på ett SaaS-företag, håll det kortfattat och vänligt" i början av varje chatt. Vad bör du göra?', options: ['Fortsätt skriva det — upprepning är oundviklig', 'Lägg det i anpassade instruktioner så att varje chatt börjar förberedd', 'Sluta ge den kontexten för att spara tid', 'Använd en annan assistent för varje ton'], explanation: 'Allt som är sant i varje chatt hör hemma i anpassade instruktioner — din roll, ditt företag, föredragen ton och längd. Ställ in det en gång så är "vem du är"-halvan av varje brief permanent hanterad.' }

quizKo['workai-1'] = { question: '세 가지 다른 작업을 다룬 100개 메시지의 채팅이 혼란스럽고 빗나간 답변을 하기 시작합니다. 가장 효과적인 해결책은 무엇입니까?', options: ['모델에게 더 열심히 집중하라고 요청', '현재 작업을 위한 새 채팅을 시작하고 중요한 내용의 짧은 요약을 가져가기', '다른 AI 제공업체로 전환', '마지막 질문을 대문자로 반복'], explanation: '모델은 매 턴마다 전체 스레드를 다시 읽습니다 — 산만한 스레드는 희석되고 모순된 컨텍스트를 의미합니다. 짧고 정확한 요약과 함께 새 채팅을 시작하면 현재 작업에 필요한 것만 정확히 제공합니다. "새 작업, 새 채팅"이 가장 저렴한 품질 업그레이드입니다.' }
quizKo['workai-2'] = { question: '챗 어시스턴트와 작업하는 반복 루프를 설명하고, 평범한 첫 결과물이 실패가 아니라 유용한 이유를 설명하세요.', modelAnswer: '루프: 프롬프트 → 출력을 진단으로 읽기 → 어떤 컨텍스트가 빠졌는지 파악(샘플 데이터, 제약, 형식, 실제 규칙) → 개선된 프롬프트로 제공 → 반복. 평범한 첫 결과물이 유용한 이유는 받은 것과 원한 것 사이의 격차가 바로 제공하지 못한 컨텍스트의 목록이기 때문입니다 — 무엇을 추가해야 할지 알려줍니다. 정보에 입각한 두 턴이 모호한 열 턴을 이깁니다.', options: undefined, explanation: '출력을 진단으로 취급하면 실망이 정보로 바뀝니다. 핵심 기술은 완벽한 메가 프롬프트 하나를 쓰는 것이 아니라 격차를 읽는 것입니다.' }
quizKo['workai-biz-1'] = { question: 'AI가 작성한 고객 이메일 초안이 일반적이고 브랜드와 맞지 않게 나왔습니다. 가장 가능성 높은 원인은 무엇입니까?', options: ['AI가 이메일 작성에 능숙하지 않습니다', '브리프가 일반적이었습니다 — 회사, 대상, 톤에 대한 컨텍스트가 없어 모델이 빈틈을 평균으로 채웠습니다', '더 나은 글쓰기를 위해 유료 플랜이 필요합니다', '이메일은 AI에 위임하면 안 됩니다'], explanation: '일반적인 것이 들어가면 일반적인 것이 나옵니다. 모델은 지정되지 않은 모든 빈틈을 통계적 평균으로 채웁니다. 컨텍스트, 작업, 형식, 대상 각각 한 문장이면 같은 모델이 여러분처럼 들리는 결과물을 만듭니다.' }
quizKo['workai-biz-2'] = { question: '매 채팅 시작마다 "저는 SaaS 회사에서 고객 성공을 담당합니다, 간결하고 친근하게 해주세요"를 입력하고 있다는 것을 발견합니다. 어떻게 해야 합니까?', options: ['계속 입력 — 반복은 피할 수 없음', '커스텀 지침에 넣어 모든 채팅이 사전 브리핑된 상태로 시작하게 하기', '시간 절약을 위해 그 컨텍스트 제공 중단', '톤마다 다른 어시스턴트 사용'], explanation: '모든 채팅에서 참인 것은 커스텀 지침에 속합니다 — 역할, 회사, 선호하는 톤과 길이. 한 번 설정하면 모든 브리프의 "당신이 누구인지" 절반이 영구적으로 처리됩니다.' }

// Optimizing Your Workflow (Use AI course)
quizSv['optwf-1'] = { question: 'Du märker att du har klistrat in samma stycke om din stack och dina testkonventioner i chatten flera gånger den här veckan. Vad är åtgärden med högst hävstång?', options: ['Skriv snabbare, eller håll en kopia i en kladdfil att klistra in', 'Flytta den stående kontexten till en AGENTS.md / anpassade instruktioner som verktyget läser automatiskt, och gör den återkommande åtgärden till ett sparat kommando', 'Byt till en modell med större kontextfönster', 'Acceptera att återförklara kontext bara är en del av att använda AI'], explanation: 'Återskriven kontext är signalen att bygga en setup. Stående fakta hör hemma i en fil som verktyget läser varje session (AGENTS.md / anpassade instruktioner); den återkommande åtgärden blir en sparad prompt eller ett kommando. Femminuterssetupen betalar för sig vid tredje användningen.' }
quizSv['optwf-2'] = { question: 'Ditt team vill "mäta vår AI-påverkan" och föreslår att spåra antal rader AI-genererad kod. Varför är det fel mätvärde, och vad skulle du mäta i stället?', modelAnswer: 'Rader AI-kod är ett fåfängemått: fler rader kan betyda verklig snabbhet eller det kan betyda uppsvällning och granskningsbörda — det skiljer inte mellan dem, och det är trivialt att manipulera. Mät resultat i stället: cykeltid (idé till mergad PR), tid-till-första-PR för nyanställda, hur stor andel av en uppgift som skiftade från "skriva" till "granska", och ärliga noteringar om var AI INTE hjälpte. De knyter an till värde och överlever en kostnadsgranskning.', options: undefined, explanation: 'Bra mätvärden mäter tid sparad och genomströmning, inte volym producerad. Volymmått belönar att generera mer kod, vilket ofta är motsatsen till målet.' }
quizSv['optwf-biz-1'] = { question: 'Du vill hitta var AI hjälper ditt team mest. Vilken uppgift är den bästa första kandidaten?', options: ['Ett höginsats-engångsfall: nästa års strategimemo', 'En återkommande, textformad, omdömeslätt uppgift — som veckans statussammandrag du bygger om varje måndag', 'Vilken uppgift som än är mest synlig för ledningen', 'Det mest tekniskt imponerande AI kan göra'], explanation: 'AI-formade uppgifter är återkommande, omdömeslätta och textformade. Veckans tidstjuv som passar alla tre tjänar in din setup-insats många gånger om — långt mer än ett flashigt engångsfall eller ett högomdömesbeslut du bör behålla.' }
quizSv['optwf-biz-2'] = { question: 'Du bygger om samma veckorapport från grunden i chatten varje måndag. Vad förvandlar denna engångsvana till ett system?', options: ['Skriv förfrågan mer artigt varje vecka', 'Spara briefen som fungerade och sätt upp ett projekt som håller de återkommande källorna, så att "generera den här veckans rapport" är hela instruktionen', 'Be en annan kollega göra det', 'Vänta på att AI:n ska minnas på egen hand'], explanation: 'Ett system är en bra brief som slutade leva i ditt huvud. Att spara den vinnande briefen och lägga de återkommande källorna i ett projekt förvandlar en 90-minuters ombyggnad till ett 5-minuters granskningsjobb — omgörningen försvinner, ditt omdöme förblir sista steget.' }

quizKo['optwf-1'] = { question: '이번 주에 스택과 테스트 관례에 관한 같은 단락을 채팅에 여러 번 붙여넣었다는 것을 발견합니다. 가장 효과적인 해결책은 무엇입니까?', options: ['더 빨리 입력하거나 메모 파일에 사본을 두고 붙여넣기', '그 고정 컨텍스트를 도구가 자동으로 읽는 AGENTS.md / 커스텀 지침으로 옮기고, 반복 작업을 저장된 명령으로 만들기', '더 큰 컨텍스트 창을 가진 모델로 전환', '컨텍스트를 다시 설명하는 것은 AI 사용의 일부일 뿐이라고 받아들이기'], explanation: '다시 입력하는 컨텍스트는 셋업을 구축하라는 신호입니다. 고정된 사실은 도구가 매 세션 읽는 파일(AGENTS.md / 커스텀 지침)에 속하고, 반복 작업은 저장된 프롬프트나 명령이 됩니다. 5분짜리 셋업은 세 번째 사용에서 본전을 뽑습니다.' }
quizKo['optwf-2'] = { question: '팀이 "AI 영향을 측정"하고 싶어 하며 AI가 생성한 코드 줄 수를 추적하자고 제안합니다. 왜 그것이 잘못된 지표이며, 대신 무엇을 측정하겠습니까?', modelAnswer: 'AI 코드 줄 수는 허영 지표입니다: 더 많은 줄은 진정한 속도를 의미할 수도 있고 비대함과 검토 부담을 의미할 수도 있습니다 — 둘을 구분하지 못하며, 조작하기도 쉽습니다. 대신 결과를 측정하세요: 사이클 타임(아이디어부터 머지된 PR까지), 신입의 첫 PR까지 걸리는 시간, 작업에서 "작성"이 "검토"로 옮겨간 비율, 그리고 AI가 도움이 되지 않은 곳에 대한 솔직한 메모. 이것들은 가치와 연결되고 비용 검토에서 살아남습니다.', options: undefined, explanation: '좋은 지표는 생산된 양이 아니라 절약된 시간과 처리량을 측정합니다. 양 지표는 더 많은 코드를 생성하도록 보상하는데, 이는 종종 목표의 반대입니다.' }
quizKo['optwf-biz-1'] = { question: 'AI가 팀에 가장 도움이 될 곳을 찾고 싶습니다. 어떤 작업이 가장 좋은 첫 후보입니까?', options: ['고위험 일회성 작업: 내년 전략 메모', '반복적이고, 텍스트 형태이며, 판단이 가벼운 작업 — 매주 월요일 다시 만드는 주간 상태 요약 같은 것', '경영진에게 가장 잘 보이는 작업', 'AI가 할 수 있는 가장 기술적으로 인상적인 것'], explanation: 'AI에 적합한 작업은 반복적이고, 판단이 가벼우며, 텍스트 형태입니다. 세 가지 모두에 맞는 주간 시간 낭비 작업은 셋업 노력을 여러 배로 되돌려줍니다 — 화려한 일회성 작업이나 당신이 쥐고 있어야 할 고판단 결정보다 훨씬 더.' }
quizKo['optwf-biz-2'] = { question: '매주 월요일 채팅에서 같은 주간 보고서를 처음부터 다시 만듭니다. 무엇이 이 일회성 습관을 시스템으로 바꿉니까?', options: ['매주 요청을 더 정중하게 입력', '효과가 있었던 브리프를 저장하고 반복되는 출처를 담은 프로젝트를 설정하여, "이번 주 보고서 생성"이 전체 지시가 되게 하기', '다른 동료에게 부탁', 'AI가 스스로 기억하기를 기다리기'], explanation: '시스템은 머릿속에 살기를 멈춘 좋은 브리프입니다. 효과가 있었던 브리프를 저장하고 반복되는 출처를 프로젝트에 넣으면 90분짜리 재작업이 5분짜리 검토 작업으로 바뀝니다 — 재작업은 사라지고, 당신의 판단이 마지막 단계로 남습니다.' }

// Agentic Coding (Use AI course)
quizSv['agcode-1'] = { question: 'Vad skiljer mest fundamentalt ett agentiskt kodverktyg från en IDE-autokomplettering eller en chattassistent?', options: ['Det använder en större språkmodell', 'Det planerar över steg och agerar i ditt repo — redigerar filer, kör kommandon och tester och verifierar resultatet — snarare än att bara föreslå eller svara', 'Det fungerar bara med JavaScript', 'Det gör aldrig misstag'], explanation: 'Autokomplettering förutsäger nästa tokens; chatt ger råd i ett fönster. En agent bryter ned en uppgift, läser och redigerar kodbasen, kör verktyg (kommandon, tester, MCP) och verifierar sitt eget arbete i en tänk → agera → verifiera-loop. Att agera-och-verifiera är skiljelinjen.' }
quizSv['agcode-2'] = { question: 'Du ska just lämna en uppgift till en kodagent. Beskriv hur du skulle avgränsa den och var du skulle granska, så att du får ett bra resultat utan att övervaka varje tangenttryckning.', modelAnswer: 'Avgränsa den som en brief till en kompetent ingenjör: ett tydligt resultat, de begränsningar som spelar roll (gränssnitt att bevara, kantfall att hantera) och en definition av klart — t.ex. "lägg till retry-med-backoff i S3-klienten, max 3 försök, behåll det befintliga gränssnittet, lägg till ett test för timeout-vägen." Lägg varaktig projektkontext (stack, konventioner, testkommando) i en AGENTS.md så att agenten startar förbriefad. Granska sedan vid kontrollpunkter: låt den slutföra en sammanhängande enhet (ändringen plus ett passerande test) och granska den diffen som en PR, i stället för att övervaka token för token. Om den kör fast — två misslyckade försök på samma fel — kliv in, lägg till kontext eller korrigera planen i stället för att låta den gräva djupare.', options: undefined, explanation: 'Bra avgränsning + varaktig kontext + granskning vid kontrollpunkter är arbetsmodellen. Du delegerar arbetet men behåller ansvaret, och agentens egna tester är det som låter dig granska resultat i stället för tangenttryckningar.' }

quizKo['agcode-1'] = { question: '에이전틱 코딩 도구를 IDE 자동완성이나 채팅 어시스턴트와 가장 근본적으로 구분하는 것은 무엇입니까?', options: ['더 큰 언어 모델을 사용한다', '단지 제안하거나 답하는 것이 아니라, 여러 단계에 걸쳐 계획하고 저장소에서 행동한다 — 파일을 편집하고, 명령과 테스트를 실행하며, 결과를 검증한다', 'JavaScript에서만 작동한다', '절대 실수하지 않는다'], explanation: '자동완성은 다음 토큰을 예측하고, 채팅은 창 안에서 조언합니다. 에이전트는 작업을 분해하고, 코드베이스를 읽고 편집하며, 도구(명령, 테스트, MCP)를 실행하고, 생각 → 행동 → 검증 루프에서 자신의 작업을 검증합니다. 행동하고-검증하는 것이 분기점입니다.' }
quizKo['agcode-2'] = { question: '코딩 에이전트에게 작업을 막 넘기려 합니다. 모든 키 입력을 지켜보지 않고도 좋은 결과를 얻으려면, 어떻게 작업 범위를 정하고 어디서 검토하겠습니까?', modelAnswer: '유능한 엔지니어에게 주는 브리프처럼 범위를 정하세요: 명확한 결과, 중요한 제약(보존할 인터페이스, 처리할 엣지 케이스), 그리고 완료의 정의 — 예: "S3 클라이언트에 retry-with-backoff 추가, 최대 3회 시도, 기존 인터페이스 유지, 타임아웃 경로 테스트 추가." 지속적인 프로젝트 컨텍스트(스택, 관례, 테스트 명령)는 AGENTS.md에 넣어 에이전트가 사전 브리핑된 상태로 시작하게 하세요. 그런 다음 체크포인트에서 검토하세요: 하나의 일관된 단위(변경 더하기 통과하는 테스트)를 완료하게 한 뒤 그 diff를 PR처럼 검토하고, 토큰 단위로 감독하지 마세요. 에이전트가 헤맨다면 — 같은 오류에 두 번 실패 — 개입하여 컨텍스트를 추가하거나 계획을 바로잡고, 더 깊이 파고들게 두지 마세요.', options: undefined, explanation: '좋은 범위 설정 + 지속적인 컨텍스트 + 체크포인트 검토가 운영 모델입니다. 작업은 위임하되 책임은 유지하며, 에이전트 자신의 테스트가 키 입력이 아니라 결과를 검토하게 해줍니다.' }
quizSv['agcode-3'] = { question: 'En icke-teknisk kollega behöver ett litet internt formulär som de själva ska äga och justera. Du skulle kunna bygga det som en enkelfilsapp i ditt repo eller hänvisa dem till en no-code-appbyggare. Vad är det bättre utgångsläget, och varför?', options: ['Bygg det alltid själv i repot — kod du äger är alltid bättre', 'En no-code-byggare, så att de kan ändra fälten utan en PR eller dig i loopen — reservera kod-du-underhåller för det som rör hemligheter eller levereras till användare', 'Vägra — icke-tekniska personer bör inte äga verktyg', 'Bygg det i ditt produktionsramverk så att det blir robust'], explanation: 'Matcha ceremoni mot livslängd och ägande. Ett formulär en kollega ska äga och redigera är bättre som en no-code-app de styr än som kod som dirigerar varje ändring genom dig. Behåll kod-du-underhåller för verktyg som rör inloggningsuppgifter, behöver ditt repo eller levereras till verkliga användare. Att veta när man ska lämna över till no-code är ett eget tekniskt omdöme.' }
quizKo['agcode-3'] = { question: '비기술 동료가 직접 소유하고 손볼 작은 내부 양식이 필요합니다. 당신은 그것을 저장소의 단일 파일 앱으로 만들 수도 있고, 노코드 앱 빌더로 안내할 수도 있습니다. 더 나은 기본값은 무엇이며, 왜 그렇습니까?', options: ['항상 저장소에서 직접 만든다 — 당신이 소유하는 코드가 언제나 낫다', '노코드 빌더 — 그래서 그들이 PR이나 루프 안의 당신 없이 필드를 바꿀 수 있도록, 그리고 당신이 유지보수하는 코드는 비밀을 건드리거나 사용자에게 출시되는 것을 위해 남겨 둔다', '거부한다 — 비기술자는 도구를 소유해서는 안 된다', '견고하도록 당신의 프로덕션 프레임워크로 만든다'], explanation: '의식을 수명과 소유권에 맞추세요. 동료가 소유하고 편집할 양식은 모든 변경을 당신을 거쳐 보내는 코드보다, 그들이 통제하는 노코드 앱이 낫습니다. 자격 증명을 건드리거나, 당신의 저장소가 필요하거나, 실제 사용자에게 출시되는 도구를 위해서는 당신이 유지보수하는 코드를 남겨 두세요. 언제 노코드로 넘길지 아는 것은 그 자체로 하나의 엔지니어링 판단입니다.' }
