// SelfExplain prompt/answer translations keyed by first 50 chars of English prompt
import type { Language } from './LanguageContext'


// Technical track SelfExplain translations

// Technical track KO
interface SETranslation { prompt: string; modelAnswer: string }

const sv: Record<string, SETranslation> = {
  'In your own words, explain the difference between': { prompt: 'Förklara med egna ord skillnaden mellan en chattbot och en agent för en kollega. Använd en vardaglig jämförelse.', modelAnswer: 'En chattbot är som att smsa en kunnig vän — de svarar men kan inte göra något. En agent är som en personlig assistent som faktiskt söker flyg, jämför, bokar och skickar bekräftelse. Skillnaden är handling: en chattbot pratar, en agent gör.' },
  'Your manager asks: "Should we let the AI agent s': { prompt: 'Din chef frågar: "Ska vi låta AI-agenten skicka mejl till kunder utan godkännande?" Hur tänker du igenom detta?', modelAnswer: 'Jag skulle överväga risken: ett felaktigt mejl kan skada relationen. Börja med utkast-och-godkänn. Automatisera rutinsvar när kvaliteten är bevisad, behåll granskning för känsliga ärenden.' },
  'Think of a multi-step process at your company th': { prompt: 'Tänk på en flerstegsprocess på ditt företag som involverar flera system. Vilka MCP-verktyg skulle en agent behöva?', modelAnswer: 'Exempel — ny affär stängd: MCP-verktyg: CRM, e-post, kalender, projekthantering, fakturering. Arbetsflöde: (1) Uppdatera CRM. (2) Skapa projekt. (3) Boka kickoff. (4) Skicka välkomstmejl. (5) Generera faktura.' },
  'Your CEO says "I want our customer support to be': { prompt: 'Er VD säger "Jag vill att vår kundsupport ska vara helt autonom till Q4." Hur skulle du råda dem?', modelAnswer: 'Jag rekommenderar Waymo-metoden: Börja med Nivå 2 för rutinärenden i Q1. Flytta till Nivå 3 i Q2 med 98%+ noggrannhet. Behåll komplexa ärenden på Nivå 2 genom Q3. Utvärdera full autonomi i Q4 baserat på data.' },
  'Think of a task at your job that takes a lot of': { prompt: 'Tänk på en uppgift på ditt jobb som tar mycket tid. Skulle AI hjälpa? Är den regelbaserad, mönsterbaserad eller språkbaserad?', modelAnswer: 'Exempel: "Jag lägger 2 timmar varje måndag på att kategorisera supportärenden." Detta är mönsterbaserat — en LLM kunde kategorisera baserat på tidigare mönster.' },
  'Your company is about to launch a customer-facin': { prompt: 'Ert företag ska lansera en kundvänd AI-chattbot. Vilka skyddsräcken skulle du sätta upp?', modelAnswer: 'Begränsa omfattningen, kräv källor, mänsklig granskning första månaden, eskalering för känsliga ämnen, innehållsfilter, övervakningspanel.' },
  'Think about your company\'s data. What\'s structur': { prompt: 'Tänk på ert företags data. Vad är strukturerat? Vad är ostrukturerat? Vilka frågor kunde AI svara på?', modelAnswer: 'Vår CRM har rena kundposter. Men den riktiga guldet finns i ostrukturerad data: mejltrådar, mötesanteckningar och Slack har signaler om riskfyllda konton.' },
  'Your team has 10,000 support articles': { prompt: 'Ert team har 10 000 supportartiklar. En kund ställer en fråga. Beskriv hur RAG skulle hjälpa.', modelAnswer: 'Steg 1: Kunden skriver frågan. Steg 2: AI söker bland alla artiklar. Steg 3: AI läser relevanta avsnitt. Steg 4: AI genererar svar med källhänvisning.' },
  'A colleague says "I just upload everything to Ch': { prompt: 'En kollega säger "jag laddar bara upp allt till ChatGPT." Varför behöver vi ett RAG-system?', modelAnswer: 'Uppladdning fungerar för personligt bruk men har begränsningar: inte persistent, kan inte söka tusentals dokument, inga åtkomstkontroller, inget revisionsspår.' },
  'How would you evaluate whether an AI chatbot is': { prompt: 'Hur skulle du utvärdera om en AI-chattbot fungerar bra för ert kundsupportteam?', modelAnswer: 'Mäta: noggrannhet (stickprov), kundnöjdhet (tumme upp/ner), lösningsgrad, svarstid, eskaleringskvalitet, kostnad per konversation.' },
  'Your CTO says \'we should use open-source AI': { prompt: 'Er CTO säger "vi borde använda AI med öppen källkod." Vilka avvägningar vill du diskutera?', modelAnswer: 'Vi undviker leverantörslåsning men tar på oss underhåll. Dataintegritet bättre. Öppna modeller något mindre kapabla. Installation tar veckor. Hybridmetod kan fungera.' },
  'Write a system prompt for an AI assistant': { prompt: 'Skriv en systemprompt för en AI-assistent som hjälper ert team med en specifik uppgift.', modelAnswer: 'Exempel: "Du är IT-supportassistenten. Hjälp med lösenordsåterställning, programåtkomst och VPN. Använd IT-kunskapsbasen. Var tålmodig. Vid säkerhetsincidenter, eskalera."' },
  'Pick a task you do regularly at work': { prompt: 'Välj en uppgift du gör regelbundet. Skriv en specifik prompt som får AI att hjälpa effektivt.', modelAnswer: 'Exempel: "Du är en senior projektledare (roll). Ge mig: (1) Topp 3 saker som gick bra, (2) Förbättringsområden, (3) Åtgärdspunkter. Här är ett exempel (exempel). Konstruktiv ton. Max en sida."' },
  'Your company needs AI for customer support. Walk': { prompt: 'Ert företag behöver AI för kundsupport. Gå igenom hyra-vs-köpa-beslutet.', modelAnswer: 'Vi hanterar kunddata (känsligt). Startup med 50 anställda utan ML-team (hyra). Behöver något om 2 veckor (hyra). Slutsats: börja med API-tjänst, utvärdera självhosting om 6 månader.' },
  'Pick a real task from your current week. Which too': { prompt: 'Välj en verklig uppgift från din nuvarande vecka. Vilken verktygskategori passar bäst, och vad skulle du behöva specificera för att verktyget ska lyckas?', modelAnswer: 'Exempel: "Migrera vår datumhantering från moment.js till date-fns" — agentiskt kodverktyg. Jag skulle specificera: biblioteken, att testerna måste passera efter varje fil och vilka kantfall (tidszoner) att vara försiktig med. Ju tydligare resultat och begränsningar, desto bättre presterar agenten.' },
  'Think of the most repetitive multi-step task your ': { prompt: 'Tänk på den mest repetitiva flerstegsuppgiften ditt team gör varje vecka. Skulle ni kunna delegera den till ett agentiskt verktyg? Skriv briefen på ett stycke som du skulle ge det.', modelAnswer: 'Exempel: "Varje måndag sammanställer vi ett nyhetssammandrag om konkurrenter. Brief: skanna dessa 12 källor efter nyheter om konkurrenterna X, Y, Z; gruppera per konkurrent; två meningars sammanfattning per post med länk; flagga allt om priser eller uppsägningar som brådskande." Tydliga källor, format och eskaleringsregel.' },
  'Recall a recent AI answer that disappointed you. R': { prompt: 'Tänk tillbaka på ett AI-svar som nyligen gjorde dig besviken. Om du läser det som en diagnos: vilken kontext hade du missat att ge?', modelAnswer: 'Exempel: "Jag bad om ett regex för att validera e-postadresser och fick ett läroboksmönster som avvisade våra interna user+tag@corp-adresser. Jag sa aldrig vilka adressformer vi accepterar — modellen besvarade den generiska fråga jag faktiskt ställde. En mening av kontext hade fixat det."' },
  'Take a task you would normally delegate to a colle': { prompt: 'Ta en uppgift du normalt skulle delegera till en kollega. Skriv AI-briefen med alla fyra ingredienser: kontext, uppgift, format, målgrupp.', modelAnswer: 'Exempel: "Kontext: Jag leder sales ops; vår kvartalsgenomgångspresentation går till ledningsgruppen på fredag. Uppgift: gör om dessa punktanteckningar (inklistrade) till en berättande sammanfattning på en sida. Format: tre korta avsnitt — framgångar, risker, önskemål — under 400 ord. Målgrupp: chefer som skummar; led med siffror, ingen jargong."' },
  'Name a prompt or context you have re-typed to an A': { prompt: 'Nämn en prompt eller kontext du har skrivit om till en AI mer än två gånger den här månaden. Vilken stående kontext skulle du extrahera, och vad skulle den återanvändbara anropningen vara?', modelAnswer: 'Exempel: "Jag klistrar ständigt in vår API-felformatspec innan jag ber om en ny endpoint-hanterare. Stående kontext → ett projektdokument med felkuvertet, auth-middleware och valideringskonventioner. Återanvändbar anropning → \'scaffolda en hanterare för <route> enligt våra konventioner\'. Specen slutar vara något jag klistrar in och blir något verktyget redan känner till."' },
  'Pick the recurring task that eats the most of your': { prompt: 'Välj den återkommande uppgift som äter mest av din vecka. Vilken brief skulle du spara, och vad skulle du lägga i ett projekt för att göra det till ett femminutersjobb?', modelAnswer: 'Exempel: "Månatlig styrelseuppdatering. Sparad brief: kontext (vem läser den, vad de bryr sig om), trestegsformatet, tonen med raka siffror. Projektinnehåll: exporten från mätvärdesinstrumentpanelen, förra månadens uppdatering för kontinuitet, varumärkestonnoteringen. Sedan startar \'utkast till den här månadens styrelseuppdatering\' från allt den behöver."' },
  'In the session above, the agent wrote a test befor': { prompt: 'I sessionen ovan skrev agenten ett test innan den sa att den var klar. Varför är det verifieringssteget det som gör det säkert att delegera till en kodagent?', modelAnswer: 'Eftersom verifiering förvandlar en rimligt utseende diff till en kontrollerad. Ett passerande regressionstest betyder att du kan granska resultatet ("gör det här det jag bad om, och är allt fortfarande grönt?") i stället för att läsa om varje rad för att gissa om det fungerar. Utan verifieringssteget ärver du all risk och ingen av tidsbesparingen — du skulle behöva manuellt kontrollera allt agenten rörde. Testet är agenten som bevisar sitt arbete, vilket är det som låter dig arbeta på kontrollpunktsnivå.' },
}

// Technical track SelfExplain translations
sv['You have an MCP server for your CRM and another fo'] = { prompt: 'Du har en MCP-server för ert CRM och en annan för ert mejlsystem. Förklara hur du skulle komponera dessa till en Skill för "lead-uppföljning."', modelAnswer: 'MCP-servrarna ger anslutning. Skillen behöver arbetsflödeslogik: (1) Fråga CRM efter leads med status "demo genomförd" utan uppföljning på 3 dagar. (2) Kontrollera om offert skickats. (3) Skriv uppföljningsmejl. (4) Logga i CRM.' }
sv['You just adjusted the KV cache slider and saw memo'] = { prompt: 'Du justerade KV-cache-reglaget och såg minnesanvändningen ändras. Förklara varför KV-cachen växer med sekvenslängden.', modelAnswer: 'KV-cachen lagrar nyckel- och värdevektorer för varje token vid varje lager. Längre sekvenser = fler tokens = mer minne. Det växer linjärt med sekvenslängd × antal lager × dimensioner.' }
sv['You just built a system prompt using the framework'] = { prompt: 'Du byggde just en systemprompt. Förklara varför systempromten är separat från användarmeddelandet.', modelAnswer: 'Systempromten sätter persistent beteende över alla samtalsrundor. Den separerar hur man beter sig från vad man ska göra nu och behöver inte upprepas varje meddelande.' }
sv['You just compared models with different perplexity'] = { prompt: 'Du jämförde modeller med olika perplexity. Förklara varför perplexity ensamt inte räcker för att utvärdera en LLM.', modelAnswer: 'Perplexity mäter genomsnittlig token-prediktion men säger inget om uppgiftsspecifik kvalitet, instruktionsföljning, säkerhet eller användarpreferens.' }
sv['You just compared open and closed models across mu'] = { prompt: 'Du jämförde öppna och stängda modeller. Välj ett användningsfall och argumentera för vilken metod som passar.', modelAnswer: 'Exempel: En vårdstartup bör överväga öppna modeller för anpassning och kostnadskontroll, men företags-API:er med HIPAA BAA kan vara säkrare om de saknar ett dedikerat säkerhetsteam.' }
sv['You just dragged the precision slider from FP32 do'] = { prompt: 'Du drog precisionsreglaget från FP32 till INT4. Förklara avvägningen.', modelAnswer: 'FP32 har full precision men kräver 4× mer minne. INT4 sparar 75% minne med <1% kvalitetsförlust för de flesta uppgifter. Under INT4 börjar kvaliteten sjunka märkbart.' }
sv['You just explored how compute budget determines op'] = { prompt: 'Du utforskade hur beräkningsbudgeten bestämmer optimal modellstorlek. Förklara Chinchilla-skalningslagen.', modelAnswer: 'Chinchilla visade att det finns ett optimalt förhållande mellan modellstorlek och träningsdata. Många modeller var undertränande — de behövde mer data, inte fler parametrar.' }
sv['You just explored the attention heatmap and saw ho'] = { prompt: 'Du utforskade attention-heatmappen. Förklara varför attention är viktigt.', modelAnswer: 'Attention låter varje token dynamiskt fokusera på de mest relevanta andra tokens. Utan det skulle modellen behandla alla ord lika, oavsett kontext.' }
sv['You just explored the RAG pipeline stages and comp'] = { prompt: 'Du utforskade RAG-pipelinens steg. Beskriv ett scenario där du kombinerar RAG och finjustering.', modelAnswer: 'Kundsupport-bot: Finjustera för företagets ton och format. Använd RAG för aktuell dokumentation och kända problem. Finjustering hanterar stil, RAG hanterar dynamisk kunskap.' }
sv['You just explored the similarity scores and scatte'] = { prompt: 'Du utforskade likhetsscore och spridningsdiagram. Förklara vad en embedding-vektor representerar.', modelAnswer: 'En embedding-vektor kodar semantisk betydelse som geometri. Liknande betydelser placeras nära varandra i det högdimensionella rummet.' }
sv['You just inspected the weight matrices before and '] = { prompt: 'Du inspekterade viktmatriserna före och efter kvantisering. Förklara vad som händer.', modelAnswer: 'Kvantisering rundar av vikter till färre bitar. Vid 4-bit grupperas liknande värden. Modellen förlorar precision men sparar 75% minne.' }
sv['You just ran a mini pipeline that went from raw JS'] = { prompt: 'Du körde en mini-pipeline från rå JSON till ren data. Förklara varför varje steg behövs.', modelAnswer: 'Extraktion hämtar rå data. Rensning tar bort brus. Normalisering gör format konsekvent. Tokenisering förbereder för modellen. Varje steg förbättrar datakvaliteten.' }
sv['You just stepped through an agent trace where the '] = { prompt: 'Du stegade genom en agent-trace. Förklara skillnaden mellan en chattbot och en agent.', modelAnswer: 'En chattbot genererar text. En agent kan ta handlingar — anropa API:er, fråga databaser, köra kod — och använda resultaten för att fortsätta resonera.' }
sv['You just stepped through BPE merging "low", "lower'] = { prompt: 'Du stegade genom BPE-sammanslagning. Förklara varför tokenisering spelar roll.', modelAnswer: 'Tokenisering bestämmer modellens vokabulär och påverkar sekvenslängd, minnesanvändning och hur väl modellen hanterar ovanliga ord.' }
sv["You just walked through a complete LoRA fine-tunin"] = { prompt: 'Du gick igenom en komplett LoRA-finjustering. Förklara varför adaptern är så liten.', modelAnswer: 'LoRA tränar bara lågrangs-dekompositionsmatriser för några lager — ~0.1% av parametrarna. Adaptern lagrar bara delta-justeringarna, inte hela modellen.' }
sv["You just walked through the alignment pipeline (SF"] = { prompt: 'Du gick igenom alignment-pipelinen (SFT → Reward Model → PPO). Förklara varför varje steg finns.', modelAnswer: 'SFT lär formatet. Reward-modellen fångar preferenser. PPO optimerar policyn. Att hoppa över något steg lämnar en lucka.' }
sv["You just walked through the decision tree. Think o"] = { prompt: 'Du gick igenom beslutsträdet. Tänk på ett verkligt problem och bestäm vilken metod som passar.', modelAnswer: 'Exempel: Klassificera supportärenden — det finns historisk data, uppgiften kräver textförståelse, och mönster kan läras. En LLM med few-shot-exempel eller finjustering passar.' }
sv["You just watched 100 TB of raw web data shrink to "] = { prompt: 'Du såg 100 TB rå webbdata krympa till 15 TB. Förklara varför varje filtreringssteg behövs.', modelAnswer: 'Språkfiltrering tar bort icke-målspråk. Kvalitetsfiltrering tar bort spam. Deduplicering förhindrar memorering. Varje steg förbättrar den slutliga modellens kvalitet.' }
sv["You just watched the training loop animate through"] = { prompt: 'Du såg träningsloopen animeras. Förklara vad som händer i varje steg.', modelAnswer: 'Ladda batch → Forward pass (förutsäg) → Beräkna förlust (mät fel) → Backward pass (beräkna gradienter) → Uppdatera vikter (justera). Upprepa tills förlusten konvergerar.' }
sv["You're deploying a customer support agent at L2 (b"] = { prompt: 'Du driftsätter en supportagent på L2. Designa styrningsramverket.', modelAnswer: 'Autonomt: Svara på FAQ, slå upp orderstatus. Behöver godkännande: Återbetalningar >500kr, kontoändringar. Förbjudet: Kontoborttagning. Övervakning: CSAT, felfrekvens, eskaleringsfrekvens.' }

const ko: Record<string, SETranslation> = {
  'In your own words, explain the difference between': { prompt: 'AI 에이전트에 대해 들어본 적 없는 동료에게 챗봇과 에이전트의 차이를 설명해 보세요.', modelAnswer: '챗봇은 박식한 친구에게 문자하는 것과 같습니다 — 답해주지만 대신 해줄 수 없습니다. 에이전트는 개인 비서와 같습니다 — 항공편 검색, 비교, 예약, 확인서 발송까지. 핵심 차이는 행동입니다.' },
  'Your manager asks: "Should we let the AI agent s': { prompt: '매니저가 묻습니다: "AI 에이전트가 승인 없이 고객에게 이메일을 보내게 해야 할까요?"', modelAnswer: '위험을 고려합니다. 초안 작성 후 승인으로 시작. 품질 신뢰가 쌓이면 일상적 응답 자동 발송, 민감한 커뮤니케이션은 검토 유지.' },
  'Think of a multi-step process at your company th': { prompt: '회사에서 여러 시스템을 포함하는 다단계 프로세스를 생각해 보세요. 어떤 MCP 도구가 필요할까요?', modelAnswer: '예시 — 새 거래 성사: MCP 도구: CRM, 이메일, 캘린더, 프로젝트 관리, 청구. 워크플로우: (1) CRM 업데이트. (2) 프로젝트 생성. (3) 킥오프 예약. (4) 환영 이메일. (5) 인보이스 생성.' },
  'Your CEO says "I want our customer support to be': { prompt: 'CEO가 "Q4까지 고객 지원을 완전 자율화하고 싶다"고 합니다. 어떻게 조언하시겠습니까?', modelAnswer: 'Waymo 접근법 추천: Q1에 일상 업무 레벨 2로 시작. Q2에 98%+ 정확도면 레벨 3. Q3까지 복잡한 업무는 레벨 2 유지. Q4에 실제 데이터 기반 평가.' },
  'Think of a task at your job that takes a lot of': { prompt: '직장에서 시간이 많이 걸리는 작업을 생각해 보세요. AI가 도움이 될까요?', modelAnswer: '예시: "매주 월요일 지원 티켓 분류에 2시간." 패턴 기반 — LLM이 과거 패턴에 기반하여 분류 가능.' },
  'Your company is about to launch a customer-facin': { prompt: '회사에서 고객 대면 AI 챗봇을 출시합니다. 어떤 가드레일을 설정하시겠습니까?', modelAnswer: '범위 제한, 출처 요구, 첫 달 사람 검토, 민감한 주제 에스컬레이션, 콘텐츠 필터, 모니터링 대시보드.' },
  'Think about your company\'s data. What\'s structur': { prompt: '회사 데이터를 생각해 보세요. 정형 데이터는? 비정형 데이터는? AI가 어떤 질문에 답할 수 있을까요?', modelAnswer: 'CRM에 깨끗한 고객 기록. 진짜 금은 비정형 데이터: 이메일 스레드의 고객 감정, 회의록의 구두 약속, Slack의 위험 계정 신호.' },
  'Your team has 10,000 support articles': { prompt: '팀에 10,000개의 지원 문서가 있습니다. 고객이 질문합니다. RAG가 어떻게 도움이 되나요?', modelAnswer: '1단계: 고객 질문. 2단계: AI가 모든 문서 검색. 3단계: 관련 섹션 읽기. 4단계: 출처 인용과 함께 답변 생성.' },
  'A colleague says "I just upload everything to Ch': { prompt: '동료가 "ChatGPT에 다 업로드하면 되는데 왜 RAG 시스템이 필요해?"라고 합니다.', modelAnswer: '업로드는 개인 사용에 좋지만 한계: 저장 안 됨, 수천 문서 검색 불가, 접근 제어 없음, 감사 추적 없음.' },
  'How would you evaluate whether an AI chatbot is': { prompt: '고객 지원팀을 위한 AI 챗봇이 잘 작동하는지 어떻게 평가하시겠습니까?', modelAnswer: '측정: 정확도(표본 검사), 고객 만족도(좋아요/싫어요), 해결률, 응답 시간, 에스컬레이션 품질, 대화당 비용.' },
  'Your CTO says \'we should use open-source AI': { prompt: 'CTO가 "벤더 종속을 피하기 위해 오픈소스 AI를 사용해야 한다"고 합니다. 트레이드오프는?', modelAnswer: '벤더 종속 회피하지만 유지보수 책임. 데이터 프라이버시 향상. 오픈 모델 약간 덜 능력. 설정에 몇 주. 하이브리드 가능.' },
  'Write a system prompt for an AI assistant': { prompt: '팀의 특정 작업을 돕는 AI 비서를 위한 시스템 프롬프트를 작성하세요.', modelAnswer: '예시: "당신은 IT 지원 비서입니다. 비밀번호 재설정, 소프트웨어 접근, VPN 문제를 도와주세요. IT 지식 베이스 사용. 보안 사고 시 에스컬레이션."' },
  'Pick a task you do regularly at work': { prompt: '정기적으로 하는 작업을 선택하세요. AI가 효과적으로 도울 수 있는 프롬프트를 작성하세요.', modelAnswer: '예시: "시니어 프로젝트 매니저(역할). 다음을 주세요: (1) 잘된 점 3개, (2) 개선 영역, (3) 실행 항목 표. 예시 첨부. 건설적 톤. 한 페이지."' },
  'Your company needs AI for customer support. Walk': { prompt: '회사에서 고객 지원을 위한 AI가 필요합니다. 임대 vs 구매 결정을 진행하세요.', modelAnswer: '고객 결제 데이터 처리(민감). 50명 스타트업, ML 팀 없음(임대). 2주 안에 필요(임대). 결론: API 서비스로 시작, 6개월 후 셀프 호스팅 재평가.' },
  'Pick a real task from your current week. Which too': { prompt: '이번 주의 실제 작업 하나를 골라 보세요. 어떤 도구 카테고리가 가장 적합하며, 도구가 성공하려면 무엇을 명시해야 할까요?', modelAnswer: '예시: "날짜 처리를 moment.js에서 date-fns로 마이그레이션" — 에이전틱 코딩 도구. 명시할 것: 관련 라이브러리, 파일마다 테스트 통과 필수, 주의할 엣지 케이스(시간대). 결과와 제약이 명확할수록 에이전트 성능이 좋아집니다.' },
  'Think of the most repetitive multi-step task your ': { prompt: '팀이 매주 하는 가장 반복적인 다단계 작업을 떠올려 보세요. 에이전틱 도구에 위임할 수 있을까요? 도구에 줄 한 단락짜리 브리프를 써 보세요.', modelAnswer: '예시: "매주 월요일 경쟁사 뉴스 다이제스트를 만듭니다. 브리프: 12개 출처에서 경쟁사 뉴스 스캔; 경쟁사별 그룹화; 항목당 링크 포함 두 문장 요약; 가격·구조조정 관련은 긴급 표시." 명확한 출처, 형식, 에스컬레이션 규칙.' },
  'Recall a recent AI answer that disappointed you. R': { prompt: '최근에 실망스러웠던 AI 답변을 떠올려 보세요. 그것을 진단으로 읽는다면: 어떤 컨텍스트를 제공하지 못했습니까?', modelAnswer: '예시: "이메일 검증용 정규식을 요청했더니 우리 내부 user+tag@corp 주소를 거부하는 교과서적 패턴을 받았습니다. 어떤 주소 형식을 허용하는지 말한 적이 없었습니다 — 모델은 제가 실제로 물은 일반적인 질문에 답했습니다. 컨텍스트 한 문장이면 해결됐을 것입니다."' },
  'Take a task you would normally delegate to a colle': { prompt: '평소 동료에게 위임할 만한 작업 하나를 골라 보세요. 네 가지 재료를 모두 사용해 AI 브리프를 작성하세요: 컨텍스트, 작업, 형식, 대상.', modelAnswer: '예시: "컨텍스트: 저는 영업 운영을 이끌고 있습니다; 분기 리뷰 자료가 금요일에 경영진에게 전달됩니다. 작업: 이 불릿 메모(붙여넣음)를 한 페이지 서술형 요약으로 바꿔주세요. 형식: 세 개의 짧은 섹션 — 성과, 리스크, 요청 사항 — 400단어 이내. 대상: 훑어보는 경영진; 숫자로 시작, 전문 용어 금지."' },
  'Name a prompt or context you have re-typed to an A': { prompt: '이번 달에 AI에게 두 번 넘게 다시 입력한 프롬프트나 컨텍스트를 하나 말해 보세요. 어떤 고정 컨텍스트를 추출하겠으며, 재사용 가능한 호출은 무엇이 될까요?', modelAnswer: '예시: "새 엔드포인트 핸들러를 요청하기 전에 우리 API 오류 형식 사양을 계속 붙여넣습니다. 고정 컨텍스트 → 오류 봉투, 인증 미들웨어, 검증 관례가 담긴 프로젝트 문서. 재사용 가능한 호출 → \'우리 관례에 따라 <route>용 핸들러를 스캐폴딩\'. 사양은 더 이상 붙여넣는 것이 아니라 도구가 이미 아는 것이 됩니다."' },
  'Pick the recurring task that eats the most of your': { prompt: '한 주에서 가장 많은 시간을 잡아먹는 반복 작업을 골라 보세요. 어떤 브리프를 저장하겠으며, 5분짜리 작업으로 만들기 위해 프로젝트에 무엇을 넣겠습니까?', modelAnswer: '예시: "월간 이사회 업데이트. 저장된 브리프: 컨텍스트(누가 읽고 무엇을 중시하는지), 세 섹션 형식, 숫자 위주의 톤. 프로젝트 내용: 지표 대시보드 내보내기, 연속성을 위한 지난달 업데이트, 브랜드 보이스 메모. 그러면 \'이번 달 이사회 업데이트 초안\'이 필요한 모든 것에서 시작합니다."' },
  'In the session above, the agent wrote a test befor': { prompt: '위 세션에서 에이전트는 완료라고 말하기 전에 테스트를 작성했습니다. 그 검증 단계가 왜 코딩 에이전트에게 위임하는 것을 안전하게 만드는 것입니까?', modelAnswer: '검증이 그럴듯해 보이는 diff를 검증된 diff로 바꾸기 때문입니다. 통과하는 회귀 테스트는, 작동하는지 추측하려고 모든 줄을 다시 읽는 대신 결과를 검토할 수 있다는 뜻입니다("이것이 내가 요청한 일을 하는가, 그리고 여전히 초록색인가?"). 검증 단계가 없으면 위험은 전부 떠안고 시간 절약은 전혀 얻지 못합니다 — 에이전트가 건드린 모든 것을 직접 다시 확인해야 합니다. 테스트는 에이전트가 자기 작업을 증명하는 것이며, 그것이 키 입력이 아니라 체크포인트 수준에서 일하게 해줍니다.' },
}

ko['You have an MCP server for your CRM and another fo'] = { prompt: 'CRM용 MCP 서버와 이메일 시스템용 MCP 서버가 있습니다. "리드 후속 조치" 스킬로 어떻게 구성하시겠습니까?', modelAnswer: 'MCP 서버는 연결을 제공합니다. 스킬에는 워크플로우 로직이 필요합니다: (1) CRM에서 "데모 완료" 상태이고 3일간 후속 조치 없는 리드 조회. (2) 제안서 발송 여부 확인. (3) 후속 이메일 작성. (4) CRM에 기록.' }
ko['You just adjusted the KV cache slider and saw memo'] = { prompt: 'KV 캐시 슬라이더를 조정하고 메모리 사용량 변화를 봤습니다. KV 캐시가 시퀀스 길이에 따라 증가하는 이유를 설명하세요.', modelAnswer: 'KV 캐시는 각 레이어에서 각 토큰의 키/값 벡터를 저장합니다. 더 긴 시퀀스 = 더 많은 토큰 = 더 많은 메모리. 시퀀스 길이 × 레이어 수 × 차원에 따라 선형 증가.' }
ko['You just built a system prompt using the framework'] = { prompt: '시스템 프롬프트를 구축했습니다. 시스템 프롬프트가 사용자 메시지와 분리되는 이유를 설명하세요.', modelAnswer: '시스템 프롬프트는 모든 대화 턴에 걸쳐 지속적인 행동을 설정합니다. 어떻게 행동할지와 지금 무엇을 할지를 분리하여 매 메시지마다 반복할 필요가 없습니다.' }
ko['You just compared models with different perplexity'] = { prompt: '다른 perplexity를 가진 모델을 비교했습니다. perplexity만으로 LLM을 평가하기에 충분하지 않은 이유를 설명하세요.', modelAnswer: 'Perplexity는 평균 토큰 예측을 측정하지만 작업별 품질, 지시 따르기, 안전성, 사용자 선호도에 대해서는 아무것도 말하지 않습니다.' }
ko['You just compared open and closed models across mu'] = { prompt: '오픈과 클로즈드 모델을 비교했습니다. 사용 사례를 선택하고 어떤 접근 방식이 적합한지 논의하세요.', modelAnswer: '예시: 의료 스타트업은 커스터마이징과 비용 통제를 위해 오픈 모델을 고려해야 하지만, 전담 보안팀이 없다면 HIPAA BAA가 있는 엔터프라이즈 API가 더 안전할 수 있습니다.' }
ko['You just dragged the precision slider from FP32 do'] = { prompt: '정밀도 슬라이더를 FP32에서 INT4로 드래그했습니다. 트레이드오프를 설명하세요.', modelAnswer: 'FP32는 완전한 정밀도이지만 4배 더 많은 메모리가 필요합니다. INT4는 대부분의 작업에서 <1% 품질 손실로 75% 메모리를 절약합니다. INT4 이하에서는 품질이 눈에 띄게 저하됩니다.' }
ko['You just explored how compute budget determines op'] = { prompt: '계산 예산이 최적 모델 크기를 결정하는 방법을 탐구했습니다. Chinchilla 스케일링 법칙을 설명하세요.', modelAnswer: 'Chinchilla는 모델 크기와 학습 데이터 사이에 최적 비율이 있음을 보여주었습니다. 많은 모델이 과소학습 — 더 많은 파라미터가 아닌 더 많은 데이터가 필요했습니다.' }
ko['You just explored the attention heatmap and saw ho'] = { prompt: '어텐션 히트맵을 탐구했습니다. 어텐션이 중요한 이유를 설명하세요.', modelAnswer: '어텐션은 각 토큰이 가장 관련 있는 다른 토큰에 동적으로 집중할 수 있게 합니다. 없으면 모델은 맥락에 관계없이 모든 단어를 동등하게 처리합니다.' }
ko['You just explored the RAG pipeline stages and comp'] = { prompt: 'RAG 파이프라인 단계를 탐구했습니다. RAG와 파인튜닝을 결합하는 시나리오를 설명하세요.', modelAnswer: '고객 지원 봇: 회사의 톤과 형식을 위해 파인튜닝. 최신 문서와 알려진 문제를 위해 RAG 사용. 파인튜닝은 스타일, RAG는 동적 지식을 처리.' }
ko['You just explored the similarity scores and scatte'] = { prompt: '유사도 점수와 산점도를 탐구했습니다. 임베딩 벡터가 무엇을 나타내는지 설명하세요.', modelAnswer: '임베딩 벡터는 의미적 의미를 기하학으로 인코딩합니다. 유사한 의미는 고차원 공간에서 가까이 배치됩니다.' }
ko['You just inspected the weight matrices before and '] = { prompt: '양자화 전후의 가중치 행렬을 검사했습니다. 무슨 일이 일어나는지 설명하세요.', modelAnswer: '양자화는 가중치를 더 적은 비트로 반올림합니다. 4비트에서 유사한 값이 그룹화됩니다. 모델은 정밀도를 잃지만 75% 메모리를 절약합니다.' }
ko['You just ran a mini pipeline that went from raw JS'] = { prompt: '원시 JSON에서 깨끗한 데이터까지 미니 파이프라인을 실행했습니다. 각 단계가 필요한 이유를 설명하세요.', modelAnswer: '추출은 원시 데이터를 가져옵니다. 정제는 노이즈를 제거합니다. 정규화는 형식을 일관되게 만듭니다. 토큰화는 모델을 위해 준비합니다.' }
ko['You just stepped through an agent trace where the '] = { prompt: '에이전트 트레이스를 단계별로 진행했습니다. 챗봇과 에이전트의 차이를 설명하세요.', modelAnswer: '챗봇은 텍스트를 생성합니다. 에이전트는 행동할 수 있습니다 — API 호출, 데이터베이스 조회, 코드 실행 — 그리고 결과를 사용하여 추론을 계속합니다.' }
ko['You just stepped through BPE merging "low", "lower'] = { prompt: 'BPE 병합을 단계별로 진행했습니다. 토큰화가 중요한 이유를 설명하세요.', modelAnswer: '토큰화는 모델의 어휘를 결정하고 시퀀스 길이, 메모리 사용량, 모델이 드문 단어를 얼마나 잘 처리하는지에 영향을 미칩니다.' }
ko["You just walked through a complete LoRA fine-tunin"] = { prompt: '완전한 LoRA 파인튜닝을 진행했습니다. 어댑터가 왜 그렇게 작은지 설명하세요.', modelAnswer: 'LoRA는 몇 개 레이어의 저랭크 분해 행렬만 학습합니다 — 파라미터의 ~0.1%. 어댑터는 전체 모델이 아닌 델타 조정만 저장합니다.' }
ko["You just walked through the alignment pipeline (SF"] = { prompt: '정렬 파이프라인(SFT → 보상 모델 → PPO)을 진행했습니다. 각 단계가 존재하는 이유를 설명하세요.', modelAnswer: 'SFT는 형식을 가르칩니다. 보상 모델은 선호도를 포착합니다. PPO는 정책을 최적화합니다. 어떤 단계를 건너뛰면 격차가 생깁니다.' }
ko["You just walked through the decision tree. Think o"] = { prompt: '의사결정 트리를 진행했습니다. 실제 문제를 생각하고 어떤 접근 방식이 적합한지 결정하세요.', modelAnswer: '예시: 지원 티켓 분류 — 과거 데이터가 있고, 텍스트 이해가 필요하며, 패턴을 학습할 수 있습니다. Few-shot 예시가 있는 LLM이나 파인튜닝이 적합합니다.' }
ko["You just watched 100 TB of raw web data shrink to "] = { prompt: '100TB의 원시 웹 데이터가 15TB로 줄어드는 것을 봤습니다. 각 필터링 단계가 필요한 이유를 설명하세요.', modelAnswer: '언어 필터링은 비대상 언어를 제거합니다. 품질 필터링은 스팸을 제거합니다. 중복 제거는 암기를 방지합니다. 각 단계가 최종 모델의 품질을 향상시킵니다.' }
ko["You just watched the training loop animate through"] = { prompt: '학습 루프가 애니메이션되는 것을 봤습니다. 각 단계에서 무슨 일이 일어나는지 설명하세요.', modelAnswer: '배치 로드 → 순전파(예측) → 손실 계산(오류 측정) → 역전파(그래디언트 계산) → 가중치 업데이트(조정). 손실이 수렴할 때까지 반복.' }
ko["You're deploying a customer support agent at L2 (b"] = { prompt: 'L2에서 고객 지원 에이전트를 배포합니다. 거버넌스 프레임워크를 설계하세요.', modelAnswer: '자율: FAQ 답변, 주문 상태 조회. 승인 필요: 5만원 이상 환불, 계정 수정. 금지: 계정 삭제. 모니터링: CSAT, 오류율, 에스컬레이션율.' }

export function translateSelfExplain(prompt: string, modelAnswer: string, lang: Language): { prompt: string; modelAnswer: string } {
  if (lang === 'en') return { prompt, modelAnswer }
  const translations = lang === 'sv' ? sv : lang === 'ko' ? ko : null
  if (!translations) return { prompt, modelAnswer }
  // Match by first 50 chars of prompt
  const key = prompt.slice(0, 50)
  const tr = translations[key]
  if (tr) return tr
  return { prompt, modelAnswer }
}
