import type { Language } from './LanguageContext'

const UI: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'LLM Academy',
    'track.business': 'Business Track',
    'track.technical': 'Technical Track',
    'course.understand': 'Understand AI',
    'course.use': 'Use AI',
    'bridge.deeper': 'Under the hood',
    'bridge.apply': 'Try it for real',
    'review.title': 'Spaced Review',
    'review.empty': 'Complete a module\'s "Check Your Understanding" to start building your review schedule.',
    'review.start': 'Start Review',
    'review.allCaughtUp': 'All caught up! No questions due right now.',
    'review.complete': 'Review Complete',
    'review.iRemembered': 'I remembered',
    'review.needReview': 'Need to review',
    'check.title': 'Check Your Understanding',
    'check.next': 'Next →',
    'check.summary': 'See Summary',
    'check.reviewSummary': 'Review Summary',
    'check.showModel': 'Show model answer',
    'check.yourAnswer': 'Your answer',
    'check.modelAnswer': 'Model answer',
    'explain.title': 'Explain It',
    'explain.placeholder': 'Type your explanation…',
    'explain.compare': 'Compare with model answer',
    'nav.previous': 'Previous',
    'nav.next': 'Next',
  },
  sv: {
    'app.title': 'LLM-akademin',
    'track.business': 'Affärsspåret',
    'track.technical': 'Tekniska spåret',
    'course.understand': 'Förstå AI',
    'course.use': 'Använda AI',
    'bridge.deeper': 'Under huven',
    'bridge.apply': 'Prova på riktigt',
    'review.title': 'Repetition',
    'review.empty': 'Slutför en moduls "Testa din förståelse" för att börja bygga ditt repetitionsschema.',
    'review.start': 'Starta repetition',
    'review.allCaughtUp': 'Allt klart! Inga frågor att repetera just nu.',
    'review.complete': 'Repetition klar',
    'review.iRemembered': 'Jag kom ihåg',
    'review.needReview': 'Behöver repetera',
    'check.title': 'Testa din förståelse',
    'check.next': 'Nästa →',
    'check.summary': 'Visa sammanfattning',
    'check.reviewSummary': 'Sammanfattning',
    'check.showModel': 'Visa modellsvar',
    'check.yourAnswer': 'Ditt svar',
    'check.modelAnswer': 'Modellsvar',
    'explain.title': 'Förklara det',
    'explain.placeholder': 'Skriv din förklaring…',
    'explain.compare': 'Jämför med modellsvar',
    'nav.previous': 'Föregående',
    'nav.next': 'Nästa',
  },
  ko: {
    'app.title': 'LLM 아카데미',
    'track.business': '비즈니스 트랙',
    'track.technical': '기술 트랙',
    'course.understand': 'AI 이해하기',
    'course.use': 'AI 활용하기',
    'bridge.deeper': '내부 들여다보기',
    'bridge.apply': '직접 해보기',
    'review.title': '간격 반복',
    'review.empty': '모듈의 "이해도 확인"을 완료하면 복습 일정이 만들어집니다.',
    'review.start': '복습 시작',
    'review.allCaughtUp': '모두 완료! 지금은 복습할 질문이 없습니다.',
    'review.complete': '복습 완료',
    'review.iRemembered': '기억했어요',
    'review.needReview': '복습 필요',
    'check.title': '이해도 확인',
    'check.next': '다음 →',
    'check.summary': '요약 보기',
    'check.reviewSummary': '복습 요약',
    'check.showModel': '모범 답안 보기',
    'check.yourAnswer': '내 답변',
    'check.modelAnswer': '모범 답안',
    'explain.title': '설명해 보세요',
    'explain.placeholder': '설명을 입력하세요…',
    'explain.compare': '모범 답안과 비교',
    'nav.previous': '이전',
    'nav.next': '다음',
  },
}

/** Get a translated UI label. Falls back to English if key missing. */
export function t(lang: Language, key: string): string {
  return UI[lang][key] ?? UI.en[key] ?? key
}

/** Module sidebar labels per language */
export const MODULE_LABELS: Record<Language, Record<string, { label: string; businessLabel?: string; subtitle?: string; businessSubtitle?: string }>> = {
  en: {
    'ai-problem': { label: "What's an AI Problem?", subtitle: 'Not every problem needs an LLM — or even ML. Learn to classify problems and pick the right tool.', businessSubtitle: 'Not everything needs AI. Learn when it helps, when it doesn\'t, and how to tell the difference.' },
    'data-foundations': { label: 'Data Foundations', businessLabel: 'Why Data Quality Matters', subtitle: 'How data is shaped, moved, stored, and why quality matters more than quantity.', businessSubtitle: 'Your AI is only as good as the data you feed it.' },
    tokens: { label: 'Tokens & Tokenizers', subtitle: 'How text becomes numbers — and why the way you split matters.' },
    transformer: { label: 'The Transformer', subtitle: 'The architecture behind every modern LLM — attention, layers, and how it all fits together.' },
    training: { label: 'Training From Scratch', subtitle: 'How billions of random numbers become a language model.' },
    'llm-data': { label: 'Data for LLM Training', subtitle: 'Where training data comes from, how it gets cleaned, and why the mix matters.' },
    alignment: { label: 'Alignment & Safety', businessLabel: 'Trust & Safety', subtitle: 'How models go from raw text predictors to helpful, harmless, and honest assistants.', businessSubtitle: 'Why AI sometimes goes wrong, and how to put guardrails in place.' },
    architecture: { label: 'Architecture Decisions', subtitle: 'Dense vs MoE, scaling laws, attention variants, and how to choose.' },
    solution: { label: 'From Problem to Solution', subtitle: 'Prompting, RAG, fine-tuning, build vs buy, and real-world cost analysis.', businessSubtitle: 'Four ways to use AI, from simple to complex — and how to decide between renting and buying.' },
    evaluation: { label: 'Evaluation & Benchmarks', businessLabel: 'How to Know If It Works', subtitle: 'Standardized benchmarks, custom evaluation, and why leaderboards can be misleading.', businessSubtitle: 'Measuring AI performance and choosing the right model.' },
    quantization: { label: 'Quantization & Formats', subtitle: 'Making models smaller and faster without losing quality.' },
    inference: { label: 'Inference & Deployment', subtitle: 'How models generate text, serving frameworks, and optimization.' },
    industry: { label: 'The Industry Map', businessLabel: 'Who Makes What', subtitle: 'Who builds LLMs, open vs closed, the ecosystem, and where it\'s heading.', businessSubtitle: 'The key AI companies, what they offer, and what it means for your business.' },
    embeddings: { label: 'Embeddings & Vector Search', businessLabel: 'Search & Knowledge Retrieval', subtitle: 'How text becomes numbers, semantic search, chunking, and the RAG pipeline.', businessSubtitle: 'How AI-powered search understands meaning, and how to give AI access to your knowledge.' },
    prompting: { label: 'Prompt Engineering', businessLabel: 'How to Talk to AI', subtitle: 'From zero-shot to multi-step reasoning — techniques for reliable LLM outputs.', businessSubtitle: 'Getting great results from AI is about asking the right way.' },
    agents: { label: 'Agents & Tool Use', businessLabel: 'AI Assistants That Take Action', subtitle: 'How LLMs call tools, the protocols that connect them, and patterns for reliable agents.', businessSubtitle: 'From chatbots to AI assistants that actually get things done.' },
    'ai-in-org': { label: 'AI in Your Organization', subtitle: 'How autonomy changes roles, decisions, and risk.', businessSubtitle: 'The technology works. The harder question: is your organization ready?' },
    'fine-tuning': { label: 'Fine-Tuning Hands-On', subtitle: 'From deciding whether to fine-tune, through data prep, to a complete LoRA training run.' },
    'tools-landscape': { label: 'AI Tools Landscape', subtitle: 'Chat assistants, agentic work apps, coding agents — what tool for what job, and why.', businessSubtitle: 'The AI tools your teams should be using — and how to pick the right one for each job.' },
    'working-with-ai': { label: 'Working With AI', subtitle: 'Context, iteration, files, custom instructions — getting great results from a chat assistant.', businessSubtitle: 'Brief it like a colleague, iterate like an editor — make great AI results your default.' },
    'optimizing-workflow': { label: 'Optimizing Your Workflow', subtitle: 'Where AI fits your day, reusable setups, team patterns — from one-off prompts to a system.', businessSubtitle: 'Find your AI-shaped tasks, turn one-offs into systems, and roll it out to your team.' },
    'agentic-coding': { label: 'Agentic Coding', subtitle: 'Coding with an agent as your pair — task decomposition, context & memory, review loops, MCP.' },
    'agentic-work': { label: 'Agentic Work', subtitle: 'AI assistants that do tasks for you — delegate multi-step work, supervise, and set guardrails.', businessSubtitle: 'AI assistants that do tasks for you — delegate multi-step work, supervise, and set guardrails.' },
    'genai-beyond-text': { label: 'Generative AI Beyond Text', subtitle: 'Image, voice, video, and multimodal — the models and APIs, and how to integrate them.', businessSubtitle: 'Image, voice, video, and multimodal — what each is for, the tools, and using them responsibly.' },
  },
  sv: {
    'ai-problem': { label: 'Vad är ett AI-problem?', subtitle: 'Inte alla problem behöver en LLM — eller ens ML. Lär dig klassificera problem och välja rätt verktyg.', businessSubtitle: 'Inte allt behöver AI. Lär dig när det hjälper och när det inte gör det.' },
    'data-foundations': { label: 'Datagrunder', businessLabel: 'Varför datakvalitet spelar roll', subtitle: 'Hur data formas, flyttas, lagras och varför kvalitet spelar större roll än kvantitet.', businessSubtitle: 'Din AI är bara så bra som den data du matar den med.' },
    tokens: { label: 'Tokens & Tokenizers', subtitle: 'Hur text blir siffror — och varför uppdelningen spelar roll.' },
    transformer: { label: 'Transformern', subtitle: 'Arkitekturen bakom varje modern LLM — uppmärksamhet, lager och hur allt hänger ihop.' },
    training: { label: 'Träning från grunden', subtitle: 'Hur miljarder slumpmässiga tal blir en språkmodell.' },
    'llm-data': { label: 'Data för LLM-träning', subtitle: 'Var träningsdata kommer ifrån, hur den rensas och varför mixen spelar roll.' },
    alignment: { label: 'Anpassning & Säkerhet', businessLabel: 'Tillit & Säkerhet', subtitle: 'Hur modeller går från rå textprediktion till hjälpsamma, ofarliga och ärliga assistenter.', businessSubtitle: 'Varför AI ibland går fel och hur man sätter upp skyddsräcken.' },
    architecture: { label: 'Arkitekturbeslut', subtitle: 'Dense vs MoE, skalningslagar, uppmärksamhetsvarianter och hur man väljer.' },
    solution: { label: 'Från problem till lösning', subtitle: 'Prompting, RAG, finjustering, bygga vs köpa och kostnadsanalys.', businessSubtitle: 'Fyra sätt att använda AI — och hur man väljer mellan att hyra och köpa.' },
    evaluation: { label: 'Utvärdering & Benchmarks', businessLabel: 'Hur vet man om det fungerar?', subtitle: 'Standardiserade benchmarks, anpassad utvärdering och varför rankningar kan vilseleda.', businessSubtitle: 'Mäta AI-prestanda och välja rätt modell.' },
    quantization: { label: 'Kvantisering & Format', subtitle: 'Göra modeller mindre och snabbare utan att förlora kvalitet.' },
    inference: { label: 'Inferens & Driftsättning', subtitle: 'Hur modeller genererar text, servingramverk och optimering.' },
    industry: { label: 'Branschkartan', businessLabel: 'Vem bygger vad?', subtitle: 'Vem bygger LLM:er, öppen vs stängd, ekosystemet och vart det är på väg.', businessSubtitle: 'De viktigaste AI-företagen, vad de erbjuder och vad det betyder för ditt företag.' },
    embeddings: { label: 'Embeddings & Vektorsökning', businessLabel: 'Sökning & Kunskapsåtervinning', subtitle: 'Hur text blir siffror, semantisk sökning, chunking och RAG-pipelinen.', businessSubtitle: 'Hur AI-driven sökning förstår betydelse och hur du ger AI tillgång till din kunskap.' },
    prompting: { label: 'Prompt Engineering', businessLabel: 'Hur man pratar med AI', subtitle: 'Från zero-shot till flerstegsresonemang — tekniker för pålitliga LLM-resultat.', businessSubtitle: 'Att få bra resultat från AI handlar om att fråga rätt.' },
    agents: { label: 'Agenter & Verktyg', businessLabel: 'AI-assistenter som agerar', subtitle: 'Hur LLM:er anropar verktyg, protokollen som kopplar ihop dem och mönster för pålitliga agenter.', businessSubtitle: 'Från chattbotar till AI-assistenter som faktiskt får saker gjorda.' },
    'ai-in-org': { label: 'AI i din organisation', subtitle: 'Hur autonomi förändrar roller, beslut och risk.', businessSubtitle: 'Tekniken fungerar. Den svårare frågan: är din organisation redo?' },
    'fine-tuning': { label: 'Finjustering i praktiken', subtitle: 'Från beslut om finjustering, genom dataförberedelse, till en komplett LoRA-träningskörning.' },
    'tools-landscape': { label: 'AI-verktygslandskapet', subtitle: 'Chattassistenter, agentiska arbetsappar, kodagenter — vilket verktyg för vilket jobb, och varför.', businessSubtitle: 'AI-verktygen dina team borde använda — och hur man väljer rätt verktyg för varje jobb.' },
    'working-with-ai': { label: 'Att arbeta med AI', subtitle: 'Kontext, iteration, filer, anpassade instruktioner — få bra resultat från en chattassistent.', businessSubtitle: 'Briefa som till en kollega, iterera som en redaktör — gör bra AI-resultat till standard.' },
    'optimizing-workflow': { label: 'Optimera ditt arbetsflöde', subtitle: 'Var AI passar din dag, återanvändbara upplägg, teammönster — från enstaka prompts till ett system.', businessSubtitle: 'Hitta dina AI-formade uppgifter, gör engångsjobb till system och rulla ut det till teamet.' },
    'agentic-coding': { label: 'Agentisk kodning', subtitle: 'Att koda med en agent som parprogrammerare — uppgiftsuppdelning, kontext & minne, granskningsloopar, MCP.' },
    'agentic-work': { label: 'Agentiskt arbete', subtitle: 'AI-assistenter som utför uppgifter åt dig — delegera flerstegsarbete, övervaka och sätt skyddsräcken.', businessSubtitle: 'AI-assistenter som utför uppgifter åt dig — delegera flerstegsarbete, övervaka och sätt skyddsräcken.' },
    'genai-beyond-text': { label: 'Generativ AI bortom text', subtitle: 'Bild, röst, video och multimodalt — modellerna och API:erna, och hur man integrerar dem.', businessSubtitle: 'Bild, röst, video och multimodalt — vad varje sak är till för, verktygen och hur man använder dem ansvarsfullt.' },
  },
  ko: {
    'ai-problem': { label: 'AI 문제란?', subtitle: '모든 문제에 LLM이 필요한 것은 아닙니다. 문제를 분류하고 올바른 도구를 선택하는 법을 배우세요.', businessSubtitle: '모든 것에 AI가 필요한 것은 아닙니다. 언제 도움이 되고 언제 안 되는지 배우세요.' },
    'data-foundations': { label: '데이터 기초', businessLabel: '데이터 품질이 중요한 이유', subtitle: '데이터가 어떻게 형성되고, 이동하고, 저장되는지, 그리고 왜 품질이 양보다 중요한지.', businessSubtitle: 'AI는 제공하는 데이터만큼만 좋습니다.' },
    tokens: { label: '토큰 & 토크나이저', subtitle: '텍스트가 숫자가 되는 방법 — 그리고 분할 방식이 중요한 이유.' },
    transformer: { label: '트랜스포머', subtitle: '모든 현대 LLM 뒤에 있는 아키텍처 — 어텐션, 레이어, 그리고 모든 것이 어떻게 맞물리는지.' },
    training: { label: '처음부터 학습하기', subtitle: '수십억 개의 랜덤 숫자가 어떻게 언어 모델이 되는지.' },
    'llm-data': { label: 'LLM 학습 데이터', subtitle: '학습 데이터의 출처, 정제 방법, 그리고 믹스가 중요한 이유.' },
    alignment: { label: '정렬 & 안전', businessLabel: '신뢰 & 안전', subtitle: '모델이 원시 텍스트 예측기에서 도움이 되고, 무해하고, 정직한 어시스턴트로 변하는 방법.', businessSubtitle: 'AI가 때때로 잘못되는 이유와 가드레일을 설정하는 방법.' },
    architecture: { label: '아키텍처 결정', subtitle: 'Dense vs MoE, 스케일링 법칙, 어텐션 변형, 그리고 선택 방법.' },
    solution: { label: '문제에서 솔루션으로', subtitle: '프롬프팅, RAG, 파인튜닝, 구축 vs 구매, 실제 비용 분석.', businessSubtitle: 'AI를 사용하는 네 가지 방법 — 그리고 임대와 구매 사이에서 결정하는 법.' },
    evaluation: { label: '평가 & 벤치마크', businessLabel: '잘 작동하는지 어떻게 알 수 있나요?', subtitle: '표준화된 벤치마크, 커스텀 평가, 그리고 리더보드가 오해를 줄 수 있는 이유.', businessSubtitle: 'AI 성능 측정과 올바른 모델 선택.' },
    quantization: { label: '양자화 & 포맷', subtitle: '품질을 잃지 않고 모델을 더 작고 빠르게 만들기.' },
    inference: { label: '추론 & 배포', subtitle: '모델이 텍스트를 생성하는 방법, 서빙 프레임워크, 최적화.' },
    industry: { label: '업계 지도', businessLabel: '누가 무엇을 만드나요?', subtitle: 'LLM을 만드는 사람들, 오픈 vs 클로즈드, 생태계, 그리고 앞으로의 방향.', businessSubtitle: '주요 AI 회사들, 제공하는 것, 그리고 비즈니스에 미치는 의미.' },
    embeddings: { label: '임베딩 & 벡터 검색', businessLabel: '검색 & 지식 검색', subtitle: '텍스트가 숫자가 되는 방법, 시맨틱 검색, 청킹, RAG 파이프라인.', businessSubtitle: 'AI 기반 검색이 의미를 이해하는 방법과 AI에 지식을 제공하는 방법.' },
    prompting: { label: '프롬프트 엔지니어링', businessLabel: 'AI와 대화하는 법', subtitle: '제로샷에서 다단계 추론까지 — 신뢰할 수 있는 LLM 출력을 위한 기법.', businessSubtitle: 'AI에서 좋은 결과를 얻는 것은 올바르게 물어보는 것입니다.' },
    agents: { label: '에이전트 & 도구 사용', businessLabel: '행동하는 AI 비서', subtitle: 'LLM이 도구를 호출하는 방법, 연결 프로토콜, 신뢰할 수 있는 에이전트 패턴.', businessSubtitle: '챗봇에서 실제로 일을 처리하는 AI 비서까지.' },
    'ai-in-org': { label: '조직에서의 AI', subtitle: '자율성이 역할, 결정, 위험을 어떻게 변화시키는지.', businessSubtitle: '기술은 작동합니다. 더 어려운 질문: 조직이 준비되었나요?' },
    'fine-tuning': { label: '파인튜닝 실습', subtitle: '파인튜닝 결정부터 데이터 준비, 완전한 LoRA 학습 실행까지.' },
    'tools-landscape': { label: 'AI 도구 지형도', subtitle: '챗 어시스턴트, 에이전틱 업무 앱, 코딩 에이전트 — 어떤 작업에 어떤 도구를, 그리고 왜.', businessSubtitle: '팀이 사용해야 할 AI 도구들 — 그리고 각 작업에 맞는 도구를 고르는 법.' },
    'working-with-ai': { label: 'AI와 함께 일하기', subtitle: '컨텍스트, 반복, 파일, 사용자 지정 지침 — 챗 어시스턴트에서 좋은 결과 얻기.', businessSubtitle: '동료에게 브리핑하듯, 편집자처럼 반복하기 — 좋은 AI 결과를 기본값으로.' },
    'optimizing-workflow': { label: '워크플로우 최적화', subtitle: 'AI가 하루에 어디에 맞는지, 재사용 가능한 설정, 팀 패턴 — 일회성 프롬프트에서 시스템으로.', businessSubtitle: 'AI에 맞는 작업을 찾고, 일회성을 시스템으로 만들고, 팀에 확산하기.' },
    'agentic-coding': { label: '에이전틱 코딩', subtitle: '에이전트를 짝으로 코딩하기 — 작업 분해, 컨텍스트와 메모리, 검토 루프, MCP.' },
    'agentic-work': { label: '에이전틱 워크', subtitle: '당신을 위해 작업을 수행하는 AI 어시스턴트 — 다단계 작업 위임, 감독, 가드레일 설정.', businessSubtitle: '당신을 위해 작업을 수행하는 AI 어시스턴트 — 다단계 작업 위임, 감독, 가드레일 설정.' },
    'genai-beyond-text': { label: '텍스트를 넘어선 생성형 AI', subtitle: '이미지, 음성, 비디오, 멀티모달 — 모델과 API, 그리고 통합하는 법.', businessSubtitle: '이미지, 음성, 비디오, 멀티모달 — 각각의 용도, 도구, 그리고 책임감 있게 사용하는 법.' },
  },
}
